### ISSUE TITLE
fetlife/fetlife-android to fetlife/android

### ISSUE THREAD

**Issue by JohnBaku** [fetlife/android#102]
Just a small thing that is driving me crazy... anyone have any issues with us renaming this repo from `fetlife/fetlife-android` to `fetlife/android`?

cc/ @fetlife/product

**Comment by Merseygeek** [comment]
I got no issues john.

**Comment by reneklacan** [comment]
👍

**Comment by FernandoMiguel** [comment]
No issues. 
But update the release docs and fetlife posts

**Comment by joaocunha** [comment]
👍

**Comment by kistitan** [comment]
sure, I will do that

**Comment by kistitan** [comment]
done

**Comment by JohnBaku** [comment]
@kistitan thanks... Feels so much better!
