### ISSUE TITLE
HW Menu button does nothing...

### ISSUE THREAD

**Issue by akhepcat** [fetlife/android#103]
When in the app, if I press my "hardware" menu button, nothing happens.

The expected behaviour (from a UI perspective) is that the app's menu should open - in this case, it should be the same as the "hamburger" menu at the top left.

Just a simple change for consistency.

**Comment by kistitan** [comment]
New Menu solutions in Android does not support Menu buttons by default, bit it can be added manually.
Good point! We will take care of it!

Thank you!

**Comment by kistitan** [comment]
Fixed, will be part of 1.3 release.

**Comment by kistitan** [comment]
Implemented in version 1.3.0
