### ISSUE TITLE
Push notifications disappear before I can read them

### ISSUE THREAD

**Issue by g1ng3r420** [fetlife/android#104]
I just got a push notification for a new update.  When I clicked it to see what the new version I needed to find it disappeared.

**Comment by kistitan** [comment]
Confirmed. 
Push message improvement is one of the next on our list.

Thank you for reporting.

**Comment by g1ng3r420** [comment]
Wow that was a fast response. 


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: kistitan <notifications@github.com> Date: 7/10/16  3:10 PM  (GMT-05:00) To: fetlife/fetlife-android <fetlife-android@noreply.github.com> Cc: g1ng3r420 <booggeymann94@aol.com>, Author <author@noreply.github.com> Subject: Re: [fetlife/fetlife-android] Push notifications disappear before I can read them (#104) 
Confirmed. 

Push message improvement is one of the next on our list.

Thank you for reporting.

**Comment by kistitan** [comment]
Notification History Feature implement in version 1.3.0
