### ISSUE TITLE
Anyplace to report bugs on the site?  Didn't see one since it's not really a "repository"

### ISSUE THREAD

**Issue by kdom13** [fetlife/android#107]
=)

**Comment by thezerogod** [comment]
You opened this as an issue; that's the appropriate way to report a bug in
the app in my opinion. The devs can then review it and try to reproduce it,
etc.

@JohnBaku might have an opinion on whether there's an appropriate thread on
FL for non-Git users to report issues though.

**Comment by kdom13** [comment]
I guess I wasn't clear enough in the title, sorry.  I found a bug on FetLife.com and would like to report it somewhere, but don't know where, because there is no repository for the site as a whole.  I realize this topic is in the wrong place, but I'm hoping someone will tell me where I should go

**Comment by thezerogod** [comment]
In that case: https://fetlife.com/groups/693/about

**Comment by reneklacan** [comment]
Yes, you can create post in Fetlife Tech Support group linked above or you can email caretakers at caretakers@fetlife.com 

Thank you :)
