### ISSUE TITLE
Sync with Android Contacts

### ISSUE THREAD

**Issue by mist** [fetlife/android#111]
I love to have my Android contacts synced together with my Fetlife contacts, so I can see kinky pictures when my friends are calling me :)

The Fetlife App by Goldenspiral I used some time ago had this feature though it was never really stable. I'd love to have the official app to have this feature as well.

This probably has something to do with #57 and #75

**Comment by kistitan** [comment]
hmm I like the initiative, but we should be careful with it as maybe not everyone would prefer that way.

It is technically possible however.

I will add this now for future consideration.

Thank you :)

**Comment by mist** [comment]
Just thought that when you implement a local user database as mentioned in #57 it could sync with a "real" android contacts database.
And yes, of course it should only be optional and not enabled by default - as well as FetLife shouldn't ask for contacts access by default.

**Comment by thezerogod** [comment]
just want to add a "me, too" here - i would like to have a contact-sync feature so i can link my FetLife contacts to my device contacts

**Comment by kistitan** [comment]
Thank you for the feedback. 
Unfortunately we still have higher priority issues, but will be kept in the front page of the list

**Comment by nextgen-networks** [comment]
I'd like to see this feature too - would be fantastic to sync profile pictures from fl to contacts db.

**Comment by kistitan** [comment]
@nextgen-networks 
Thanks a lot for reporting it.
It really helps out to prioritise.

At this moment we are busy with implementing the Feed for the App, but it is already a highly requested feature so it will be hopefully picked up not much after that.

Thanks for you patience and understandings.

**Comment by FernandoMiguel** [comment]
Although many of us would love to have their contacts synced and properly shown, we also need to consider that if anyone runs 3rd party apps that access and sync the contacts, it can leak the personal and the kinky details of some user who wishes to remain private. 
Facebook, sync.me, and LinkedIn come to mind. 

If we offer this, we should have a profile setting in the private (off by default) to allow profile details to be synced with other users app/contacts. 

I'm aware many would never enable this setting, preventing this feature from being useful, but we must consider the privacy aspect first.

**Comment by nextgen-networks** [comment]
@FernandoMiguel 
I absolutely support your idea of profile security.
This setting should never enabled by default and there should be some kind of intelligence test ;-) before users could enable the contact provider sync. At least some kind of impressive warning message which leads in mind the possibilities as mentioned by @FernandoMiguel

**Comment by FernandoMiguel** [comment]
@nextgen to be clear, this privacy setting would be on everyone else profile, not something you just enable in one person app. 
Others have to consent to have their profile data programactly stored (and possibly synced/leaked) to other services.

**Comment by nextgen-networks** [comment]
@FernandoMiguel 
OK now I got your idea/intention.
With this in mind the complete idea of contact sync could be transferred to the cemetery :-/

**Comment by FernandoMiguel** [comment]
Privacy first. 
It should not be this app point to help leak data unless other users consent to it

**Comment by reneklacan** [comment]
Also we currently don't allow members to be discovered by email and I don't think members would like it in general.

What we can do is to implement privacy setting (with default off) for allowing other members to discover you by email but I don't feel confident about it.

@johnbaku What do you think?

**Comment by kistitan** [comment]
Thank you guys.

I like this discussion very much especially as @FernandoMiguel has some very good point.
We indeed should be very cautious with this feature and discuss also internally how to approach it.

**Comment by johnbaku** [comment]
@reneklacan 

> We currently don't allow members to be discovered by email and I don't think members would like it in general

This can be used for more bad than good! Not happening! Sorry.

**Comment by reneklacan** [comment]
> This can be used for more bad than good! Not happening! Sorry.

Thought so as well. We are sorry, for privacy reasons this feature won't probably ever exist.

**Comment by kistitan** [comment]
As of now we don't see a reasonable way to do it without facing privacy issues.
So we close this issue now, with considering reopening it if any good idea pops up.
