### ISSUE TITLE
Notifications Tab Name

### ISSUE THREAD

**Issue by Daddy** [fetlife/android#119]
Would it be a reasonable request to consider renaming the Notifications tab to "@ You" or something similiar, to match the notifications display on FetLife?

As the app's eventual goal is to display the same information and notifications as are displayed on FetLife, it would make sense to have matching titles/names for it!

**Comment by kistitan** [comment]
Good point.
Just like other menu related feedbacks I will merge this to a menu improvement issue.

**Comment by kistitan** [comment]
see issue: https://github.com/fetlife/android/issues/124
