### ISSUE TITLE
Moving Share My Profile Down

### ISSUE THREAD

**Issue by Daddy** [fetlife/android#120]
While I believe that the **Share My Profile** tab and feature is something important, I don't necessarily believe that it should be apart of the main section of navigation tabs on the menu.

The other tabs in the first section all open up actual pages with their own unique data, while Share My Profile strictly creates a temporary overlay. I think it'd make a lot more sense to move it down underneath About, and have Log Out be the final tab instead.

**Comment by kistitan** [comment]
As menu is growing we definitely need a better design for it, that is not ready yet.
I keep this open for now. Probably I will merge these into one issues about menu later.

Thanks for reporting

**Comment by kistitan** [comment]
see issue: https://github.com/fetlife/android/issues/124
