### ISSUE TITLE
Menu Tab Icons

### ISSUE THREAD

**Issue by Daddy** [fetlife/android#121]
**Description**
The current menu icons feel a bit _odd_ and don't directly relate to the tabs they are associated to.

The icon for **Conversations** is currently an Iris/Eye; this should be considered to change into an Envelope icon, as that is the focus of conversations and messages.

The icon for **Friends** is a Magnifying Glass/Search; this should be considered to change into an User/Users icon. This is currently very misleading as there is no search implemented, and also Friends eventually will also load profiles in-app.

The icon for **Share My Profile** is using the Share/External Services icon which **DOES** make somewhat sense, although from a UX point of view, this is extremely misleading to users. This icon on any other application will usually launch the Share UI to share content/data with other applications or services, and is not what the tab/feature currently accomplishes.

**Comment by kistitan** [comment]
Indeed, currently default icons are reused that do not always cover our needs.
We definitely need more meaningful icons here!

Thanks for reporting!

**Comment by kistitan** [comment]
See issue: https://github.com/fetlife/android/issues/124
