### ISSUE TITLE
Unicode Emoji support

### ISSUE THREAD

**Issue by kistitan** [fetlife/android#125]
Messages with default emojis (as per Unicode, supported my default keyboard) fail and do not go through.

**Comment by Daddy** [comment]
I feel it's important to note that this is something related to FetLife itself, and will not be resolved on the application(s) unless support is added on the service. Currently using emojis will result in failed posts and errors on the site as well.

**Comment by kistitan** [comment]
Good comment.
Client side is indeed ready to support Unicode emojis.
We should take a look what can we do server side.

However even if server side support would not be solved we can still support client to client emoji support for full chat experience escaping and transforming emojis to acceptable text reference while sending and receiving to and from the server.

We should take a look what we can do in this area.

**Comment by kistitan** [comment]
On Client side if you send an emoji within the text, upload will fail.
This will be workaround in the next version before final solution will take place.

**Comment by kistitan** [comment]
Postponed...

**Comment by kistitan** [comment]
Supported from version 1.6

**Comment by johnbaku** [comment]
Look at that... @kistitan went to bat for Emojis and got it done for the app! 

You just have this effect on me @kistitan...

![giphy](https://cloud.githubusercontent.com/assets/22100/18215212/f5d140cc-7104-11e6-84bd-7b970620aa2d.gif)

:-p
