### ISSUE TITLE
Customize notification options within app

### ISSUE THREAD

**Issue by thezerogod** [fetlife/android#127]
This is really a feature request...
- Enable selecting custom alert sound instead of using device default
- Enable toggling vibration on or off (e.g. I prefer my notifications to play a sound and not vibrate)
- Enable playing sound/vibration only for first notification if notifications have not been dismissed (the Gmail app does this and it's really nice)

**Comment by kistitan** [comment]
Hi there,
Great feature request. Thank you.
The App is really getting close to the state when we really need some settings.
These should go there too.

**Comment by thezerogod** [comment]
i think you can close this issue/merge it with #138 if you want - my intention was more or less the same!

**Comment by kistitan** [comment]
Thanks, however I would keep it open as a first step I will add turn on/off option and that later we can improve to select other customization

**Comment by kistitan** [comment]
Implemented in the lest release
