### ISSUE TITLE
"Clear All" Notifications

### ISSUE THREAD

**Issue by Daddy** [fetlife/android#128]
**Description**
Currently, there isn't a way to clear a large amount of notifications and requires manually swiping across them all. As you receive notifications for groups you're subscribed to, this can cause receiving dozens of notifications a day which can be overwhelming to swipe away.

With being an event organizer, subscribed to two popular groups, and also getting notifications whenever someone uses @Daddy (whether or not it's intended for me), it makes the notifications tab a jungle to go through.

I would recommend adding a "Clear All" button or some other way to toggle them all away.

**Comment by kistitan** [comment]
Good point. As always ;)
Thanks for the idea.

**Comment by kistitan** [comment]
Added to version 1.4.0
