### ISSUE TITLE
Timestamps on Notifications

### ISSUE THREAD

**Issue by Daddy** [fetlife/android#129]
**Description**
Currently, there are no timestamps displayed on notifications which makes someone viewing their notifications after something has been received confused as to when it occured if the dialog was dismissed. Additionally, if you receive more than one notification from a group, you have no idea which are different or when it was posted.

**Comment by kistitan** [comment]
Good point! Low hanging fruit, will be added in the next release.

**Comment by Daddy** [comment]
@kistitan Thank you! Looking forward to the release, keep up the great work. :+1:

**Comment by kistitan** [comment]
Added to version 1.4.0
