### ISSUE TITLE
Improving "Share my Profile"

### ISSUE THREAD

**Issue by Daddy** [fetlife/android#136]
Sharing your FetLife profile is a very personal experience, and is intended to be a social interaction, so why don't we make it that much better?

**Currently, to share your profile with another kinkster (NFC), the process currently works as the following:**
- Launch the FetLife application on both devices.
- Navigate to the menu.
- Click on "Share My profile".
- Tap the phones together, then navigate to Friend Requests.
- Swipe the kinkster's profile to accept it.

**Why not simplify the entire process while also cleaning up the Friend Requests tab by doing the following?**
- Launch the FetLife application on both devices.
- Tap the phones together, and a dialog will appear with the kinkster's phone with the other's profile picture, FetLife username, a short array of mutual friends, and then an accept or reject button.

Clicking accept will clear the dialog on both devices, add the kinkster to the friends list of whoever accepted it, and remove the need of having two separate lists of friend requests.

**Comment by kistitan** [comment]
You have some good points, and we definitely should be open for improvements in the share profile experience.
However there are some good arguments should be taken into consideration:

We don't want force the user to make decision right away. It also can be unpleasant in a conversation. An overlay notification however with a postpone option that automatically disappear after a while if the user doesn't accept can be a possible improvement. (I will keep this issue open for this improvement.)

Other point is that NFC beam has a technical limitation offering only one way communication. (it will be the same with the QR code extension)
So there should be an initiator and the other party doesn't need to open the app.
For same reason the initiator cannot be notified if the other user accepts or rejects the request. 
(Note: the feature should work without internet connection too)
With some complex solution two way communication might be solvable but even in that case it would be uncomfortable keeping the phone together and use the screen at both side.

But the approval pop-up with (auto) postpone option is a good idea.

thanks

**Comment by kistitan** [comment]
Share profile via NFC is now out of the App.
If it will come back, we will have a new design for it.

Closing this for now.
