### ISSUE TITLE
PIN & Fingerprint Protection

### ISSUE THREAD

**Issue by Daddy** [fetlife/android#137]
A concern that I've been made aware of recently at some local events in regard to the Android and iOS applications is a lack of **safety and security** with accessing the FetLife application.

For many individuals, being apart of the BDSM and kink community is a very secret and private matter, and the fears of friends, family, or co-workers becoming aware of someone's involvement can be a very real fear. There has been countless individuals I've spoken to who have refused to even consider downloading the new applications as there is _not currently a way to protect or hide any content or data on it._

**Proposed Solution**
While I may be incorrect, Android provides a way to require using the system-stored fingerprint, or lock-screen PIN to access features within applications or the app itself.

Once Settings has been added, the ability to toggle this option on and require the use of a fingerprint/PIN whenever launching the app (with a reasonable timeout) should be considered.

This would allow for individuals afraid to have FetLife installed on their personal devices (which friends or family can sometimes get their hands on) feel more safe and trust that their lifestyle is not at risk of being outed unintentionally.

**Comment by kistitan** [comment]
It's and interesting question that we should definitely think about.

As of now the same effect can be reached if the user explicitly log off the application.

What we can do is to auto logoff the user when the application is sent to the background.
Making it configurable of course during login. 

Fingerprint or pin would not give much gain compared to the password imo and it could bring unnecessary complexity.

But the auto logout option is something that we indeed should do.
Very good feedback, thanks you!

Side comment: not only related to the FetLife app but for all your friends who has similar concern you can suggest this or similar apps:

https://play.google.com/store/apps/details?id=com.domobile.applock

With this you can explicitly lock and/or hide apps and images from unwanted access of others.

**Comment by kistitan** [comment]
I close this and keep 
https://github.com/fetlife/android/issues/147
open
