### ISSUE TITLE
Settings to turn off notifications

### ISSUE THREAD

**Issue by kistitan** [fetlife/android#138]
- Turn on/off app notifications
- Turn on/off app notifications - friends only
- Turn on/off app notifications per user

**Comment by restrainedimages** [comment]
I have posted some new pictures and my @'s have gone crazy. (3rd world problems.)
It has made the app notifications effectively useless. I've had to disable them on my watch.

I think this should be a high priority or app notifications could be a major issue.

**Comment by kistitan** [comment]
Thanks very much for the very useful feedback.
Indeed this issue should have higher priority, based on the scenario that you described.
I will raise the priority and make it sure it will be in the 1.5 version (1.4 version is almost ready to be released, so it won't fit into that one, but 1.5 will be a smaller release and this feature will be included).
Thanks you for your patience.

**Comment by kistitan** [comment]
Version 1.4.0 is out, this issue is has the highest priority now together with : https://github.com/fetlife/android/issues/147

**Comment by kistitan** [comment]
Feature is available from version 1.5.1
