### ISSUE TITLE
Links on login page no longer work.

### ISSUE THREAD

**Issue by halsteaw** [fetlife/android#146]
Links on sign in page no longer work.

"Sign up Now!" brings you to user #2957004 with the handle "signup" due to FetLife's URL resolver handling "www.fetlife.com/<handle>" as a valid URL.

"Forgot your login info" does not bring you to a page to recover your information. It tries to go to "https://fetlife.com/retrieve_login_information" which doesn't work. Looks like it should be "https://fetlife.com/users/password/new"

fetlife/src/main/java/com/bitlove/fetlife/view/LoginActivity.java
Lines 222 and 226

**Comment by halsteaw** [comment]
https://github.com/fetlife/android/pull/148

I fixed it and submitted the above Pull Request

**Comment by kistitan** [comment]
Indeed, thanks for the fix.
It will be included in the upcoming version.

**Comment by kistitan** [comment]
It is fixed in 1.4.0, thanks to @halsteaw
