### ISSUE TITLE
Anonymity suggestion

### ISSUE THREAD

**Issue by halsteaw** [fetlife/android#147]
For those users who are seriously into no one knowing their business or trying to stop a nosy child from seeing the FetLife app, wondering what it is, and googling it.

Would it be possible to have an "Innocuous mode" setting that would change the application icon to a simple FL, the application menu text to FL, alert notifications to generic "A User has messaged you", etc?

Things people might not want example:
1) "Mom! Why is there a horned heart on your lock screen?"
2) "Mom! Why does your lock screen say that "BigCock4U" has messaged you?"

Also, assuming said child gets past the lock screen and clicks on the application link, the login screen (because the user diligently logs out) should not say "Fetlife" or have the "Sign up now"/"Forgotten Password" links for as long as they redirect to a browser.

....if "Innocuous mode" is turned on.

**Comment by halsteaw** [comment]
Also, assuming said child gets past the lock screen and clicks on the application link, the login screen (because the user diligently logs out) should not say "Fetlife" or have the "Sign up now"/"Forgotten Password" links for as long as they redirect to a browser.

**Comment by johnbaku** [comment]
I agree this is a good idea.. and not only that... might be best as the default mode!

**Comment by halsteaw** [comment]
Personally, I  don't mind the horned heart and notifications.

Perhaps it should be a question asked at your very first logon?

"Would you like Vanilla or Kinky mode?" with a brief description of each.

**Comment by Daddy** [comment]
"Pick your poision!"

**Vanilla**
Generic notifications, hidden App Name, controlled access to app?

**Kinky**
Detailed notifications, full App name, no restrictions to app (no auto log out, etc)

**Comment by kistitan** [comment]
As I wrote in the other issue, it is a very important feedback.
As a first step we are going to add an option in the logon screen if the user wants to type her/his each time she or he sends the app to the background.
An other option might be if the user wants to receive notifications even when the app is not active.
(In this case with hidden details)

The other request making the app look less kinky (app name, icon, etc) is more tricky.
Changing app launcher name and icon is not supported by Android OS by default.
There are some tricks and workarounds that can be done, but I would not go in that way,
What I am going to do is to make an automatic build of a different flavor so there will be always to type of the app, and when you download it you can decided which version you would like to use.

**Comment by FernandoMiguel** [comment]
I really like the idea of different builds for different designs. 
Sure, it's not the most pretty solution nor the less confusing, but archives the requirement. 

How do you plan to keep both code/build trees?

**Comment by kistitan** [comment]
Fortunately there is no need for 2 code trees.
Gradle supports different flavours, and you can specify different values and resources for this different app flavours.
So when you build you can just select the appropriate flavor and you get the expected result.

**Comment by FernandoMiguel** [comment]
good to know!

**Comment by kistitan** [comment]
Version 1.4.0 is out, this issue is has the highest priority now together with : https://github.com/fetlife/android/issues/138

**Comment by kistitan** [comment]
Feature is available from version 1.5.1
