### ISSUE TITLE
Version 1.4.0 shows in Applications list as "Conversations"

### ISSUE THREAD

**Issue by thezerogod** [fetlife/android#150]
Under v1.3.0 the app was called "FetLife" in the app drawer; it now appears to be called "Conversations".
![screenshot_20160809-155713](https://cloud.githubusercontent.com/assets/2320654/17531522/351462a0-5e4a-11e6-8993-476f745fa2a8.png)

**Comment by kistitan** [comment]
Hmm...
Thanks for your feedback.

It doesn't happen with our test devices.
May I ask which Android version you use?

**Comment by thezerogod** [comment]
Nexus 6, Android 7.0, patch version July 5, 2016. Baseband
MDM9625_104670.31.05.39R, kernel 3.10.40-g02be3a1. Build NPD90G.

1.4.0 was installed over 1.3.0 as an upgrade (no uninstall/reinstall).

**Comment by FernandoMiguel** [comment]
Confirmed on my Nexus 6p with Android N

**Comment by GojuSuzi** [comment]
Hmm, mine still shows as Fetlife. Nexus 6 on Android 6.0.1. Maybe it's a Nougat thing?

**Comment by kistitan** [comment]
Indeed... I will test with 7.0 
App name is in theory based on the launcher intent filter name and if it is empty it falls back to the activity's title.

Surprising it doesn't work like that on the newest version.
I will check if officially anything changed in this point.

**Comment by FernandoMiguel** [comment]
if not, file a bug against android :)
although this late in the cycle, wont get fixed for a while

**Comment by kistitan** [comment]
Should be fixed in version 1.5.1

**Comment by thezerogod** [comment]
Confirmed fixed.
