### ISSUE TITLE
Allow for optional captions when uploading Pictures

### ISSUE THREAD

**Issue by Daddy** [fetlife/android#153]
**Description**
FetLife allows for the including of optional image captions which are displayed on the service to all other members. Currently, uploading pictures results in bad UX, as it then requires the member to open FetLife on their mobile device (or Desktop), navigate to the picture, and finally edit the caption.

**Suggested Solution**
Before the image upload process, have the device display the selected picture and then a text box (marked as optional) underneath it.

**Comment by kistitan** [comment]
For sure :)
It is part of the plan.

Thank you for opening an issue for it.

**Comment by crr** [comment]
Always on top of things @kistitan! ;)

**Comment by Daddy** [comment]
Always on top of things @kistitan. ;)

**Comment by kistitan** [comment]
Added in 1.7
