### ISSUE TITLE
Log-in request on app switch

### ISSUE THREAD

**Issue by GojuSuzi** [fetlife/android#157]
Just started happening with 1.5.1, original flavour. Using Android 6.0.1 on Nexus 6.

Opening the app remembers my log in and takes me straight to my stuff, all good. However, if I minimise the app or switch to another app, and then switch back to it, it gives me the log-in screen. Whether or not I log in at this point, when I close the app and re-opwn it, it remembers my log in again. So it doesn't appear to be logging me out per se, more that after being minimised the app defaults to showing the log in screen regardless of log in status.

**Comment by kistitan** [comment]
Hi @GojuSuzi,

For privacy reasons from 1.5.1 we changed the default behavior of the App so it always ask for your password.
It doesn't actually log you out (for example you can still receive notifications) but prevent other persons to see your all content.

This behavior is however optional. 
When you see the login screen there should be a new check box (always ask for password). 
Uncheck it before you log in and you won't be bothered by being asked to provide your password.

Please reopen this issue if it doesn't work as described above.

Thank You!

**Comment by kistitan** [comment]
Note: I open a bug issue as even after force closing the app password should be asked.
