### ISSUE TITLE
Keyboard should be closed when you open sidebar

### ISSUE THREAD

**Issue by reneklacan** [fetlife/android#161]
![screenshot_20160821-182729](https://cloud.githubusercontent.com/assets/1935686/17854991/666fd128-6876-11e6-963e-28326858dacd.png)

**Comment by kistitan** [comment]
Makes sense :)

**Comment by johnbaku** [comment]
@reneklacan good catch thanks!!!

**Comment by kistitan** [comment]
Issue should be fixed in version 1.5.11
