### ISSUE TITLE
mobille data/3g  app issues.

### ISSUE THREAD

**Issue by Merseygeek** [fetlife/android#165]
I have just noticed that she. Using Vodafone e UK 3g data on my phone, app works OK as does the website. But when using other sim cards data, including the 3 network I get the error "cannot connect to server, please check your internet connection"

Checked with 3, the connection to 3G is working fine, and I have the latest app (1.5) and sufficient data allowances.

Also cleared the caches and made sure the app works fine my end. Works OK on Vodafone and WiFi, not too sure if it works fine with other 3g enabled UK sim cards.

**Comment by FernandoMiguel** [comment]
Three used to block my access to adult sites. 
Make sure your adult filter isn't ON

**Comment by kistitan** [comment]
Hmm.. indeed interesting as we have no influence on the connection level... 
If the Android OS reports it cannot reach the server we display the message. 

However we can check if it is because of Adult blocking.
Can you reach the fetlife website with your mobile browser during the blocked period?

**Comment by Merseygeek** [comment]
My adult filter is currently off. And I tried to access the site and got and error message about not establishing a secure connection.

**Comment by FernandoMiguel** [comment]
@Merseygeek what phone (and Android OS version) and browser?
I've seen reports of a few ppl with older devices, with outdate SSL certs, failing to load Fet CDN

**Comment by Merseygeek** [comment]
I use an all view viper v1, android 4.4.4, works I use the stock browser and Firefox.

Works fine on WiFi, vodafone 3g. Although the vodafp e sim is out of action hence using 3 sim. 

The phone itself is a dual sim, all other sites and apps I use work perfectly.

**Comment by kistitan** [comment]
So At least we know it is not app related as the site is also not accessible.
Can you maybe check your date settings?

If the date of your device is set to some default values (like 1970) certificates of the sites might be considered as invalid (as certificates have certain validity range)
Just wild guess but worth a check.

**Comment by Merseygeek** [comment]
Dates checked and are all fine.

**Comment by kistitan** [comment]
Thanks for checking, I will involve guys from the website support if they have any ideas.

**Comment by kistitan** [comment]
Hi there,

Unfortunately we still cannot do much about this issue and we can have only wild guesses.
All we can sat from our side is to try to get in contact with your Mobile Network Operator and ask in general what can be the reason that you can access internet but not certain websites.
Maybe an interesting test could be firsr if the sim card produces similar symptoms in different device.

**Comment by Merseygeek** [comment]
Spent a day last week chatting with the people at 3 who are the network providers for the Sim card I used. They checked their system and there was an issue on their side involving adult filters.

The main adult filter was turned off, but their system hadn't removed the filter for apps installed outside of play store so it meant that the app had been blocked, as had the site. the filter has since been corrected and the app now works.

The website still has a minor error when use on the built in android browser whilst using the 3 Network, but that is due to the certificates not registering properly with 3 themselves.

**Comment by FernandoMiguel** [comment]
wow sneaky 3... how the hell are they seeing which traffic comes from non-playstore apps?
i had loads of problems to disable my adult filter. everyone would say it was off, but i kept getting blocked.
eventually when they did their ad free day, my filters seem to have been reset. all good now...well i also left them for EE

**Comment by Merseygeek** [comment]
Wouldn't call it sneaky. It's just the way the network handles certain data.

Not sure how they know what traffic is outside play store, bit beyond my technical skills.

**Comment by kistitan** [comment]
Interesting findings. 
Thank you for sharing. 
We are happy that at least we know what was the reason.
I close this issue now.
