### ISSUE TITLE
Delete user

### ISSUE THREAD

**Issue by restrainedimages** [fetlife/android#168]
What exactly does the "Delete user" menu option do?

It worries me that it could delete the Fetlife user. This would be bad.
It is right below "Logout" and so could be selected by accident.

Think it needs renaming to something less scary. Just don't know what until I understand what it does.

**Comment by kistitan** [comment]
Hmm... very good point!
I did not think of that.

It is rather delete user data.

Log out user logs you out of the App so you have to provide your password again next time (we will block also any internet communication after logout based on your other suggestion - this is not yet implemented). You will still receive notifications while you are logged out.

Delete user is to delete all user content on the device, so if you use next time the App while you are offline, you won't see any previously downloaded content.  You will also not receive notifications any more.
But it does NOT delete your FetLife user. 

Sorry for the misunderstandings. It is my bad.

**Comment by Daddy** [comment]
@kistitan A lot of applications will have a "Delete Cache" or "Delete User Data" option usually hidden away in Settings, as it's not an average feature a member will use. There should also be a dialog warning stating it will both delete user data and log them out after.

**Comment by malachid** [comment]
I also had similar confusion and concerns when I first saw the option.

While I agree that most Android apps have that functionality inside the Android Settings app,  I can see that it might be a more common function for this specific application.

Since it only makes sense within the context of logging out, maybe it would be better if Logout gave you the option of "Clear personal data off of this device" or something?

**Comment by kistitan** [comment]
Delete user data has been moved to the settings screen with a summary and confirmation dialog.
Also an issue has been discovered with settings saving, so after upgrade unfortunately you might will need to check your notification settings if they are still correct.
Fix will be available in next release.

**Comment by kistitan** [comment]
Fixed in 1.7
