### ISSUE TITLE
Feed v2.0!

### ISSUE THREAD

**Issue by kistitan** [fetlife/android#171]

**Comment by johnbaku** [comment]
Exciting times!

Before you start the project how about you, @reneklacan, and I get together and talk through the feed project. What say you?

**Comment by kistitan** [comment]
Of course... :)

**Comment by kistitan** [comment]
Activity feed is released with 2.0.0 version.
Story is kept open as further feed item types are going to be supported.

**Comment by kistitan** [comment]
Planned improvements are postponed to next version

**Comment by kistitan** [comment]
Improvement topic merged into this from:
https://github.com/fetlife/android/issues/245

**Comment by kistitan** [comment]
Reminder: further improvement: add unfollow option to feed story item

**Comment by kistitan** [comment]
Closing due to duplication.

Feed section will be improved with all explore section features from the website.
