### ISSUE TITLE
No bug, just request for search feature.

### ISSUE THREAD

**Issue by CottonwoodBiGuy** [fetlife/android#173]
Something for a future feature, if possible, add a search feature to look for specific users/topics/kinks/places, like the searches on the site but with more options to get a more targeted response.

**Comment by CottonwoodBiGuy** [comment]
Maybe a way to IM a user in a private way without posting to website

**Comment by kistitan** [comment]
Hi @CottonwoodBiGuy 
Thanks for caring to report this suggestion.
Some search functionality (similar to the website) we surely should add in the future.
If it should has more be more targeted... It's a tricky question as we should take many arguments take into consideration.
But anyway I keep this issue open for sure ad a feature request.

Thanks again

**Comment by johnbaku** [comment]
@CottonwoodBiGuy and @kistitan this is one of those, it all depends on what happens on FetLife first. We can't offer more targeted search options in the app and not on FetLife. 

Currently, we are not offering asl search on FetLife and don't plan to. So I suggest we close this issue.

What say you @kistitan?

**Comment by kistitan** [comment]
@johnbaku 
I think we can close this issue as currently we have no plan for the exactly requested feature (detailed search). 
I suggested to keep it open as we do not have an issue yet for the same search functionality as we have for the website. And that seems to be a valid feature request.
But maybe it is better to close this and open another one later to avoid misunderstandings.

**Comment by johnbaku** [comment]
@kistitan it is valid, yes!

**Comment by kistitan** [comment]
Ok so I will close this issue now and open a new one for supporting basic search functionality.
@CottonwoodBiGuy: thanks for reporting the issue and for your patience. Extended search is not planned at the moment. Similar search than on the website will be on our todo list.
