### ISSUE TITLE
Some bugs I found....

### ISSUE THREAD

**Issue by Sirwt** [fetlife/android#174]
Hi,

Just downloaded your NEW Android App to my HTC One ( M7 ) and there are bugs, like the screen for settings is " greyed out " I see the words but can't do anything, like the friends names are cut off font is too big for the box size...

Just thought you would like to know...

**Comment by kistitan** [comment]
Hi @Sirwt,

Thanks a lot for your feedback.
We really appreciate it.
Would you mind if I ask it was possible to send us some screenshots about the issues? 
We didn't encounter on our test devices.

Thanks a lot again!

**Comment by Sirwt** [comment]
I don't mind sending you the screenshots but how do you do that on a mobile??    How old are your test devices?  My cell is a HTC One ( M7 ) which was the FIRST HTC One phone !!!

**Comment by FernandoMiguel** [comment]
@Sirwt 
you press power + volume , then upload here

**Comment by FernandoMiguel** [comment]
this app will tell the devs the resolution of your screen and DPI
https://play.google.com/store/apps/details?id=com.ben.myscreensize

**Comment by Sirwt** [comment]
It has been sent although it went to my profile on FetLife....

**Comment by Sirwt** [comment]
Also, I just found another bug, the main log page has a box asking "  Always ask for password " well when I remove the default check mark which should make the next time NO password, but it doesn't and places back the check mark...

**Comment by FernandoMiguel** [comment]
@Sirwt 
that would be bug https://github.com/fetlife/android/issues/169

**Comment by FernandoMiguel** [comment]
For reference, here is the link to the screenshot
https://fetlife.com/users/636/pictures/52514992

@Sirwt next time try uploading the screenshots directly to the ticket.
thanks

**Comment by Sirwt** [comment]
If I read bug #169 correctly I HAVE v1.7.0  and I still can't make it work properly....

**Comment by Sirwt** [comment]
@FernandoMiguel I uploaded from the mobile that doesn't have this site on it, so I could only send it the way I did..  Maybe you should make a link to this sire on the mobile upload section to help those not completely easy with computers/mobiles....

**Comment by kistitan** [comment]
Hi guys,

Sorry for the late reply. I was a bit list in implementing and somehow missed the notification about this thread.
Sorry again.

@Sirwt:
It is too bad you are facing so many issue. We are really working on to have a handful experience with the Android app.
If you can make a screenshot feel free to send it to my email : Krisztian@fetlife.com

We have some Samsungs and Nexus to test. No HTC unfortunatelly. 
I will try to set up an appropriate emulator for it.

Issue 169 is a bitch. First because it is annoying for you second because it is hard to track down.
So as far as I understood even if you uncheck the checkbox than log in, after a while (without logging out) you are forced to provide your credentials again. Is that correct?
May I ask if it happened kind of all the time when you abandon the app for a while or only rarely?

@FernandoMiguel
Thanks a lot for backing me up :)

**Comment by kistitan** [comment]
@Sirwt 
There are 2 things you can try that has a low chance to solve the issue for you (in that case we still should investigate why did it happen at all)

One is to go Setting menu in the App, and then select Profile Settings than Clear local User Data.
This will log you out so log in again with the checkbox unchecked and let's see if the issue occurs again.

If this does not help you can still try to reinstall the app (however it is unlikely that it will help after trying the first option)

If none of them is going to help, I am going to release a new version soon that will have extra logginf option. So it won't solve the issue right away but will give us more hints what's going on.

Thanks a lot again for reporting and for your patience.

**Comment by BarryFruitman** [comment]
I use a larger font than the system default an my friends names are cut off too on the conversations list. @Sirwt, is that what you're referring to? Do you use a larger-than-default font?

I have a fix for this bug. How do I submit it for code review?

**Comment by BarryFruitman** [comment]
I use a larger font than the default on my device, and my friends' names are cut off on my conversation list. This may be what @Sirwt was referring to. I uploaded a screen shot:
![untitled-1](https://cloud.githubusercontent.com/assets/463228/18807799/819cbaee-8205-11e6-9aa6-94c390018407.png)

By way of introduction, I'm a professional Android engineer and it would be awesome if I could contribute to this project. I have a fix for this bug. How do I contribute it?

**Comment by kistitan** [comment]
@BarryFruitman
Thanks a lot! It's indeed seems to be a bug ;)

And it's awesome you feel like contributing.
We really appreciate it.
Feel free to clone or repository make the changes in a separate branch and open a new change request.

After a quick review we merge it to master and it will be part of next release.

We highly appreciate for any further hint or suggestions if you had any.

Thanks again!

**Comment by kistitan** [comment]
@BarryFruitman
As the issue is obvious now I removed the link for the screenshot just to be sure we don't show your and your friends conversation in public.

**Comment by BarryFruitman** [comment]
@kistitan Thanks. Not to mention it was NSFGH (Not Safe For GitHub).

I get this error when I try to push my branch to origin:
```
$ git push origin conv_item_layout_174:conv_item_layout_174
Username for 'https://github.com': barry@fruitman.me
Password for 'https://barry@fruitman.me@github.com':
error: The requested URL returned error: 403 while accessing https://github.com/fetlife/android.git/
info/refs
fatal: HTTP request failed
```

I'm new to GitHub. Do I need write access?

**Comment by malachid** [comment]
@BarryFruitman generally, for GitHub (not this repo specifically), you would fork the repo and make the changes in a branch. When you push them up to your fork, GitHub's UI will allow you to create a pull request against this repository.

Info on the process can be found here:
https://help.github.com/articles/fork-a-repo/

**Comment by BarryFruitman** [comment]
@malachid Yes that's what I'm doing but I get the error above when I push my branch to GitHub.

I'm familiar with remote repos in general, but not GitHub specifically, so there must be some detail I'm missing.

**Comment by malachid** [comment]
@BarryFruitman The error message you posted shows you attempted to post to the official FetLife repo rather than your own fork.
The URL should have looked like https://github.com/barryfruitman/andoid.git (for example).

**Comment by BarryFruitman** [comment]
@malachid Thanks. I pushed it to my own repo: https://github.com/BarryFruitman/fetlife-android. How do I create the pull request?

**Comment by malachid** [comment]
@BarryFruitman Should see the option if you view the branch in the GitHub UI. See:
https://help.github.com/articles/about-pull-requests/

**Comment by BarryFruitman** [comment]
I figured it out. Pull request submitted.

**Comment by Sirwt** [comment]
Just for the record, I have deleted the App off my phone....

**Comment by malachid** [comment]
@kistitan fyi ^^

**Comment by kistitan** [comment]
@Sirwt
We are sorry to hear that. Thank you for giving a try.
If you feel like, come back and take a look at it again sometimes in the future. 
We are keep working on making it more convenient to use.

@malachid
Thank you for guiding Barry with the pull request.

@BarryFruitman
Thank You again for your help.
We are going to review and merge it soon.

Have a nice rest of weekend for all of you.

**Comment by BarryFruitman** [comment]
You're welcome. I found the same bug in the Friends list so I'll submit another pull request after the first one is merged.

I'd also like to help on upcoming projects like the profile page. Is there a plan yet for group discussion pages?

**Comment by kistitan** [comment]
@BarryFruitman : I merged your PL. Good job!
The same issue exist at Friends and FriendRequests.
As of now I set the not needed view's visibility to gone. That is good enough workaround for now, but of course you are more than welcome to do the appropriate removal if you feel like.

**Comment by kistitan** [comment]
@BarryFruitman 
As we discussed it at issue: https://github.com/fetlife/android/issues/175
We would like to keep discussions mainly technical at this point and open it up to the whole audience later.
For technical discussion we keep using GitHub.

Any volunteer contribution is more than welcome.
If you have any suggestion or question, feel free to open a new GitHub Issue for that.
For example as of now we use only profile link to open profiles and we do not have a GitHub issue for that.
In connection with the Profile page t is also a topic to discuss if we want to go for a full native screen for the Profile displaying or we rather go for some webview solution as soon as web Profile page is going to be responsive. 

Nothing is final yet so it might worth a thread (GitHub issue) to discuss it.

**Comment by kistitan** [comment]
@BarryFruitman And btw your changes has been released with 1.7.12 pre-release version ;)
https://github.com/fetlife/android/releases/tag/v1.7.12

After the test period, if nothing comes up we make it to the next official release.

**Comment by malachid** [comment]
@kistitan I would discourage the webview approach.  Not only do apps relying on webview tend to get extremely negative feedback, but it's a constant security nightmare.

**Comment by kistitan** [comment]
@malachid
I am not a guy who should be tried to convince to go with the native app ;)
But we also should keep our mind open for other approaches.
And there are a few successful project that worth to investigate. 

But as I wrote we don't have any plan yet to change our current strategy from going with full native app, but it's always good to sometimes rethink our paradigms.

**Comment by johnbaku** [comment]
@malachid 

> Not only do apps relying on webview tend to get extremely negative feedback, but it's a constant security nightmare.

In what scenarios are you concerned that using webview would be a security nightmare? Trying to better understand any potential issues.

**Comment by malachid** [comment]
Awhile back, Google had decided to stop providing security updates to webviews on older devices.  While that may not be a big deal for those of us that stay current, in many demographics, they still use older devices.

This is an outdated article, but a good example:
http://www.zdnet.com/article/google-why-we-wont-patch-pre-kitkat-android-webview/

**Comment by FernandoMiguel** [comment]
@malachid from android 6/7 webview updates come from chrome install
for older versions, you still get webview updates directly from play store

https://play.google.com/store/apps/details?id=com.google.android.webview
last update last week

**Comment by malachid** [comment]
That link points to:

Requires Android
5.0 and up

**Comment by johnbaku** [comment]
@malachid I don't think it's fair to constrain ourselves by supporting older OSes. I would support only 4.4+ which would cover the majority of current Android users. And the number will only go up. 

https://mixpanel.com/trends/#report/android_os_adoption

**Comment by kistitan** [comment]
What is true that using webview and JavaScript is opening a new door that with we at least should be careful

**Comment by malachid** [comment]
@johnbaku I think 4.4+ is reasonable. 4.4 still has the vulnerability.

**Comment by BarryFruitman** [comment]
Just wondering why you're even considering a WebView solution since everything else in the app is currently native. In general I'm against apps that use a hybrid of native and web code -- mainly because of integration pitfalls -- unless there's a good reason, which I don't see in this case.

**Comment by kistitan** [comment]
Guys I am very much happy because of this productive discussion.

Please keep commenting in the following thread:
https://github.com/fetlife/android/issues/178
