### ISSUE TITLE
Investigate webview solution in Android

### ISSUE THREAD

**Issue by kistitan** [fetlife/android#178]
Investigate solution that makes some hybrid apps successful:
https://signalvnoise.com/posts/3743-hybrid-sweet-spot-native-navigation-web-content

**Comment by malachid** [comment]
@kistitan maybe you can start the discussion with info on what you are looking to use it for, why you need it, etc?

**Comment by kistitan** [comment]
So answering a question from a previous thread.

The reason we consider using webviews for some smaller parts of the app is maintenance.

Like imagine we have a help and faq page on the website that we update frequently.
Should we always add all the questions and answers again to the Android app?
Or should we really make and maintain an API to retrieve all the new questions and make a dynamic screen displaying them?
If everything is there do we really need double work and maintenance?

Of course there are draw backs too and at the and we might say no for any non native solution but I would say (even if, being a native gut, believe me it almost physical hurts :D) at least we should investigate the options in some well described scenarios like for a q&a page.

**Comment by BarryFruitman** [comment]
@kistitan Fair enough. The help and FAQ page is a great example of an exception to the rule that makes sense.

Ideally, the app and website should use the same API, to avoid the duplication you described. Does the website use any APIs or are we creating all-new APIs for mobile?

**Comment by kistitan** [comment]
There are many things going on behind the scenes. We are working on making our whole ecosystem more maintainable and productive. 
The API we use currently for the Android App is relatively new and part if this goal.

**Comment by kistitan** [comment]
I have read the success story : https://signalvnoise.com/posts/3743-hybrid-sweet-spot-native-navigation-web-content
And it seems of course promising on the other hands what it makes me a bit cautious is the lack of details and source code.
In the past years I have seen 3 hybrid projects failing near to me and those 2 that survived turned out not to be significantly less effort to implement.
I still think there should be a way to use it correctly, but this article does not give much details.
(And you can easily find other stories that tries to prove the other side)

Anyway... keep investigating...

**Comment by johnbaku** [comment]
@malachid so is it only in Android 5 where the vulnerability has been fixed with webviews?

**Comment by malachid** [comment]
@johnbaku For that particular vulnerability, that is true.  All of the companies (Google, Apple, HTC, whoever) eventually stop providing security updates for older devices / firmwares.

**Comment by malachid** [comment]
@kistitan I admit that I am a bit biased since it's my day job; but I would say the correct solution would be a single REST backend  that the Android/iOS/web implementations all use.  It's not like you are going to end up with a single js/css that works across all Android devices anyway. Whenever clients say they want to use a webview in their app, I always discourage them because it leads to a bad experience and negative reviews in the store (which you don't have to worry about).

**Comment by johnbaku** [comment]
It's in my personal view, and based on what I've read from other similarly sized organizations with similarly large sites / apps, that it's not feasible to make the FetLife app 100% native nor is it worth the energy.

I would prefer the team spend more time on the core features and not waste their time on the extras.

**Comment by kistitan** [comment]
I personally agree with both of you.
I also had very bad experience with webview based solution.

We had at least 3 different project trying and after a while we always gave it up.
So as much as I can I try to avoid.

But on the other hands I also knows some project that use them successfully so I do not want to become stubborn because of my personal experiences. 

So my opinion at this moment is try it really low, for a screen that does not cause much problems (a help or faq session can be really good candidate, and see how does it go)

Maybe we will give it up right away, maybe we extend to solution to some other not so important screen with keeping all the complex ones native, we will see.
But I think we at least should give a try from our side to to see how does it go with our project structure.

But again I am also very sceptical as I personally never seen a good solution with my own eyes, but there too many "success stories" just to ignore them without taking a loot at least.

Playing around a bit at least won't hurt too much. Hopefully ;)

**Comment by johnbaku** [comment]
@kistitan we just deployed new responsive Guidelines and Legalese sections... I recommend you try with those:

- https://fetlife.com/guidelines/community
- https://fetlife.com/legalese/tou

Our Help section is not responsive yet.

**Comment by BarryFruitman** [comment]
+1 for @malachid 's suggestion. 

Every social app I'm aware of is 100% native, even for their TOU pages. It seems we've already made the decision to go native. Are we questioning that now? Or is it a matter or resources?

We've created some great APIs for conversations and friends. Can't we keep cranking out APIs and features? They can be leveraged by the website and other clients whenever they're ready, until we're all operating under the same framework.

If it's a matter of resources, I'm willing to commit my time to implementing a feature such as profile pages or discussions.

**Comment by johnbaku** [comment]
@BarryFruitman time and attention is life's most precious resource. I prefer @kistitan spent almost all of his energy and time on where FetLifer's spend there most time... the feed and PMs.

I propose that we use webviews as placeholders and people can always volunteer to convert webviews to native over time. So we get the best of both worlds.

@kistitan how does that sound?

**Comment by kistitan** [comment]
In general it is good concept.
But I let's see first how will it go with our first try before with webview and come back to this topic afterwards.

**Comment by johnbaku** [comment]
Some articles:

- https://m.signalvnoise.com/debunking-android-myths-webviews-suck-so-make-everything-native-cea5f8a8db87
- https://signalvnoise.com/posts/3743-hybrid-sweet-spot-native-navigation-web-content

**Comment by kistitan** [comment]
Again... The ultimate success stories... :)

**Comment by BarryFruitman** [comment]
Those posts make a good argument for WebViews, which I'm not against in principle, especially for apps that require very little client-side processing, like FetLife.

Am I right in hearing there are plans to make the profile web page responsive? If so, that seems like a good opportunity to compare native and WebView performance head-to-head.

What can I help with?

**Comment by kistitan** [comment]
@BarryFruitman 
Profile page on the website is going to be responsive for sure.
The question if we going to display it as a webpage in the app or as a native screen.

I think that there are several strong argument having also the profile page native (image cache, offline visit, complex screen with more data are better browsable with native experience etc)

However it is to early to make this decision as final.
Our current agreed roadmap is
- finish feed natively
- create a webview based template screen and use them for some smaller screens
- align the design of the app and the webpage

and than to sit together and make decisions about other screens based on the experiences.

On the other hand if you really feel like contributing with a native profile screen we cannot express how much would we appreciate.
The only thing we cannot make is a promise that we are going to reuse it as it is or if we start using it that we won't replace it to other design/approach.

If you do not mind this, you are more than welcome to start working on it.
I am sure that even if we end up use it differently we will still be able to reuse several parts of your work. Furthermore you will get familiar with our code base and you give us valuable remarks and suggestions.

So it is up to you :)

**Comment by johnbaku** [comment]
@BarryFruitman 

> Am I right in hearing there are plans to make the profile web page responsive?

Yes, the plan is to make all of FetLife responsive. If you check out profile you can see some of the most recent designs.

**Comment by BarryFruitman** [comment]
I'd love to work on the profile screen, even if it's just an experiment. Is there an API?

**Comment by kistitan** [comment]
Yep, there is.
I will add the call later today to the API object.

**Comment by malachid** [comment]
Oh yay. Another webview vulnerability.
http://www.trustlook.com/threat/badkernel/

**Comment by FernandoMiguel** [comment]
STAP BREAKING THE INTERNETZ

**Comment by johnbaku** [comment]
@malachid if I Google Android vulnerabilities I am sure I can find a reason not to develop for Android period! :-p

**Comment by malachid** [comment]
@johnbaku true. or for the web ;)

**Comment by FernandoMiguel** [comment]
Pigeon fet

**Comment by BarryFruitman** [comment]
WebView vulnerabilities allow malicious websites to compromise a user's device. FetLife.com is not a malicious website. What exactly are we concerned about?

**Comment by kistitan** [comment]
Part of the work is done, rest is postponed to next release cycle

**Comment by kistitan** [comment]
Some WebView screens are supported in the App.
More coming...
