### ISSUE TITLE
Notifications Problem

### ISSUE THREAD

**Issue by pinkpuckeredlips** [fetlife/android#180]
Samsung Galaxy S6 Phone - running Marshmallow 6.0.1

Hello, I receive a Fetlife notifications banners on my phone screen, cool thanks!, but when I click on them or go into the app via my mobile phone there are none there. Then if I check the app on my laptop using the web version or on the phone using the web version I don't have any notifications there either. I am not sure what is happening. Am I missing notifications that I should be seeing or is the mobile android app throwing false notifications? Thanks!

**Comment by FernandoMiguel** [comment]
I suspect the notification you got was about the new version of the app. 


Either that, or someone did a @mention, and those are not listed on the website

**Comment by kistitan** [comment]
@pinkpuckeredlips 

Thank you for reporting this issue.
As of now App notifications can be different than website notifications.
For example indeed when we have a new App version you will receive that notification only with you App, but not with the website.

From App version 1.3. you have a notification screen for App related notifications, however these are not synchronized with your web notifications as they are from different source.

However for your convenience you get some notifications (mentions, friend requests etc) both with the app and at the website.
These notifications can be also visible at the Android App's notification screen as long as you do not explicitly delete or clear them.

Please let us know if this clarifies enough the current situation or you still face some issues.

**Comment by kistitan** [comment]
As there is no more information on this I close this for now.
Please feel free to reopen in case of further question or unexpected behaviour.
