### ISSUE TITLE
User Accounts Combined or Comingled

### ISSUE THREAD

**Issue by pinkpuckeredlips** [fetlife/android#181]
I have seen this happen on both the web-based desktop app and the Android mobile app
**Desktop version** - OS/Windows 10 Home v1511, OS build 10586.589 64-bit using both Chrome v53.0.2785.116 m (64-bit) or MS Edge v25.10586.0.0 using MS Edge HTML v13.10586
**Mobile Version** - Fetlife v1.7.0 installed on a Samsung Galaxy S6 Phone - running Marshmallow 6.0.1, Chrome v 53.0.2785.124

Neither of these two scenarios happens consistently -

On the **mobile app**, when I sign in with one profile name, don't log out, and then if I switch to the web version using the Chrome browser on the phone or when the mobile app passes me to the web app where I was previously logged in as another user, on the mobile phone, I see a different profile name on the menu at the top right-hand side of the web page but the profile info displayed is for the first profile..  It is like the app is combining the two profiles.

I have also seen this on the **desktop version using both Edge or Chrome** browsers.  I log in with one profile then log out. Then I immediately sign into the app again with a new profile login name, and I see one profile name on the menu on the right but the profile displayed on the page below is for the previous profile. It is like the first profile session didn't close cleanly but let me start a new session with another username and combined the two together.

I don't have them now, but if I can catch a screen capture the next time this happens, I will pass it along.

**Comment by kistitan** [comment]
@pinkpuckeredlips
Thanks you for reporting this strange issue.

What I can say from Mobile app side is that we do not check or contribute with any browser session on the device.
When app opens a link it does not do more but send the url to the browser.
So in theory it can happen and it is normal that open a link from the App, but if you are logged in the browser with a different user you will see the page with that browser logged-in user (of course if the page has visibility restricted to the App user you won't see it with the browser user)

@reneklacan any idea about from the website side?

**Comment by reneklacan** [comment]
> So in theory it can happen and it is normal that open a link from the App, but if you are logged in the browser with a different user you will see the page with that browser logged-in user (of course if the page has visibility restricted to the App user you won't see it with the browser user)

I am sure this is exactly what happened.

But I don't think we should do anything to change this behaviour, if we implemented it I can imagine members complaining that they are getting signed off on different account when they click on notification from app.

---------

I think it was similar case with website, maybe you had still some tabs from previous session? And when you sign in on different account we can't really control your other already opened tabs.

**Comment by kistitan** [comment]
Hi there,

As close this issue after the clarifications above.
If you had any more question or remark, please feel free to let us know.

Thanks a lot
