### ISSUE TITLE
Having problems 

### ISSUE THREAD

**Issue by duhon8035** [fetlife/android#182]
Can't sign in having problems sighin into the app

**Comment by ReluctantSub** [comment]
No issues on my end. Could you give us some exact details as to what is happening, and OS version, etc?

**Comment by kistitan** [comment]
@duhon8035 
Thank you for reporting the issue.
May I ask if you are trying to login with your user name or email address?

Can you please confirm that the same credentials work with the website and fail only for the Android App?

Thanks a lot and sorry for the inconveniences.

**Comment by kistitan** [comment]
As there is no more information I close this issue now.
Please reopen it if it happens again.
