### ISSUE TITLE
I get "unable to scan" when trying to install

### ISSUE THREAD

**Issue by Multiperv** [fetlife/android#190]
There is a number after which I thought was an error code (2980) as I recall but when I tried a second time later I got a "unable to scan 2981" so I think it might just be a counter of times something couldn't scan.

And I'm pretty sure it said something about unable to DEEP scan earlier, if that helps any.

Phone:  HTC One M9  HW Version:  0003
Android version: 6.0
Android security patch level:  September 1, 2016
Software number: 3.39.531.21

Kernel version:  3.10.84-perf-g604273a
Build number: 3.39.531.21.CL690290 release-keys

On the first attempt I was running Lookout AntiVirus, the free version and in trying to get into Lookout to turn off scanning temporarily I accidentally updated to the premium version when I thought I was just logging in to a previously existing account.  At any rate the second attempt tonight was done with the activated premium version, which may account for the slightly different error message (no 'deep' the second time).

**Comment by kistitan** [comment]
Hi @Multiperv

Thanks a lot for reporting this issue.
It is weird,we never face similar.
Unfortunatly untile the app execution reaches our code we cannot do much, but we will take a look at it and see if we can find more information about the issue.

**Comment by kistitan** [comment]
@Multiperv 

After some google search in indeed turned out that your messages is provided by Lookout App.
Unfortunately I have no clue about how this apps work, but we can confirm that the Official FetLife App does not include any virus if it is installed from the following source:
https://github.com/fetlife/android/releases/latest

So to install FetLife App please 
- disable Lookout (or uninstall if there is no such an option)
- install FetLife App from the link above
- enable (install) Lookout again

Thanks again for letting us know about this issue

**Comment by Multiperv** [comment]
As an update, I lost my phone about 10 days ago.  Luckily I had phone insurance so the cost wasn't as bad.  My provider sent me a different model as a replacment, a Samsung Galaxy S6 edge+.  It also came with Lookout AV but before I selected Update I tried doing an install and it does work on this phone.  So maybe it was an issue specific to that phone or some issue with more recent releases of Lookout Antivirus.

**Comment by FernandoMiguel** [comment]
@Multiperv do yourself a favor and uninstall/disable that crap :)

**Comment by Multiperv** [comment]
Yeah, I might since I have Norton on my home machine and a subscription that let's me install it on up to 5 devices, and my Android could be one of them.

**Comment by FernandoMiguel** [comment]
no no no @Multiperv . dont use norton either. android doesnt need AV... they dont even do anything, since they cant access the apps anyway.

**Comment by malachid** [comment]
I normally have avast! running.
When I got the push notification to update the app, Lookout also gave me an
error and prevented it's install.
I don't use Lookout and have chosen not to root this particular device.
I was able to manually re-install the updated version from the website -
but I doubt the average user would do that.



Malachi de Ælfweald
http://www.google.com/profiles/malachid
