### ISSUE TITLE
Show sender meta info (age gender etc) in notification

### ISSUE THREAD

**Issue by kistitan** [fetlife/android#191]
Feature request received in PM

**Comment by kistitan** [comment]
@reneklacan What do you think?

**Comment by reneklacan** [comment]
@kistitan I have some privacy concerns about this... How would it be useful for Android App to include those info?

**Comment by kistitan** [comment]
If someone gets a lot of private messages from unknown person it can be useful to select if (s)he wants to react at once.

**Comment by kistitan** [comment]
Merging to https://github.com/fetlife/android/issues/200
