### ISSUE TITLE
update button

### ISSUE THREAD

**Issue by FernandoMiguel** [fetlife/android#192]
how about having an update button on About section that would check for a new APK and download/install?
i only remember to upgrade when either i get a push (not that often) or get the email about a new release being tagged.

having the button there would allow for folks that dont keep up with github to at least check for updates

**Comment by kistitan** [comment]
Hi @FernandoMiguel 

We always send out an update notification, not much after the new version.
(Depending on the length of an additional internal test round)

So polling is not required.

Notifications will be sent out about v1.7.18 too.

Note: if you upgrade the App before you get the notification, you won't see it at all, as we check if the notification is about a newer version or app has been already updated.

**Comment by kistitan** [comment]
Note: There was one version for that indeed no notification was sent out as we already seen some issues we wanted to fix quickly so we decided to send notification only about that one.
(Later unfortunately it turned out the fixes took longer so there was once indeed no notification for longer time)

**Comment by FernandoMiguel** [comment]
i guess i never get the notification cause i tend to install early.... but i know i didnt install several of the latest 1.7.x and didnt get any push
