### ISSUE TITLE
App features don't make sense

### ISSUE THREAD

**Issue by sgcurry** [fetlife/android#194]
I would love to see more thank just friend requests and messages through the app. As it is, I cannot go to the profile of a person who has sent me a friend request without logging into the actual site, which makes the app inconsequential. I could see this working as maybe an IM chat kind of thing, but the way it is now is just pointless.

**Comment by kistitan** [comment]
Dear @sgcurry 

Thank you very much for reporting this issue.
We are happy to let you know that the Android App development is in early state and definitely not end state.
Both Profile and Feed and many other features are on our todo list however we decided to release the app even in this state as for several users the currently supported features are also important.

Please browse our github issue for the issues we are currently working on, and feel free to open new issue with concrete suggestions.

Thanks again
