### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by SynapticTraveler** [fetlife/android#195]
attempting to install on Samsung Galaxy S4 with Android 5.0,1, allowed install from unknown sources, launched apk, scrolled to bottom of permissions, tapped next, no response of any kind, tapped cancel, apk exited. repeated with same results from file in dropbox, file on device, and after device reboot.

**Comment by kistitan** [comment]
@SynapticTraveler 

Thank you reporting this issue.
Do you use an custom launcher or dimmer app?

If you do so, please disable them and try again.

It is a common issue with dimmer and custom launchers as they do make an overlay over your device's screen and that can cause other overlay not able to be touched.

**Comment by kistitan** [comment]
As there is no more information from the user I close this issue for now.
