### ISSUE TITLE
Connection error. 

### ISSUE THREAD

**Issue by navyguyg** [fetlife/android#198]
Recieved a "Connection error. Please try again later." notification after being logged in for a few days. Could not see new messages after receiving notification for them.  Logged out and logged back in and new conversations could be seen again.

**Comment by kistitan** [comment]
Hi @navyguyg ,

It is a known bug. Please log out and log in again before version 1.7.18

You can also install our latest version that contains the fix for that:
https://github.com/fetlife/android/releases/download/v1.7.18/fetlife-1.7.18.apk

Thank you very much and sorry for the inconveniences.
