### ISSUE TITLE
About page force closes app

### ISSUE THREAD

**Issue by Fbiss** [fetlife/android#202]
I just got the newest version of the app and when I try to go to the about page I get a force close issue with the app.

**Comment by thezerogod** [comment]
I have the same issue. Nexus 6, Android 7.0.

**Comment by steelowheel** [comment]
Same here. Oneplus One, Android 6.0.1, Cyanogen 13.1.2-something.

**Comment by FernandoMiguel** [comment]
Fine on nexus 6p with 7.1.1

**Comment by halsteaw** [comment]
Same issue. 
App: 1.7.19
Phone: Galaxy S5
Android 6.0.1

**Comment by kistitan** [comment]
Hi all thank you for the report.
Indeed about page was not testes this time.
Sorry for the inconveniences.

We take care of it ASAP.

thanks again

**Comment by kistitan** [comment]
Hi all,

Issue has been fixed. Fix is available in version 1.7.20.
Already available to download:
https://github.com/fetlife/android/releases/latest

Notification will be sent out soon too.

Thank you.

**Comment by kistitan** [comment]
Hi all,

Issue has been fixed. Fix is available in version 1.7.20.
Already available to download:
https://github.com/fetlife/android/releases/latest

Notification will be sent out soon too.

Thank you.

**Comment by kistitan** [comment]
Hi all,

Issue has been fixed. Fix is available in version 1.7.20.
Already available to download:
https://github.com/fetlife/android/releases/latest

Notification will be sent out soon too.

Thank you.

**Comment by kistitan** [comment]
Hi all,

Issue has been fixed. Fix is available in version 1.7.20.
Already available to download:
https://github.com/fetlife/android/releases/latest

Notification will be sent out soon too.

Thank you.

**Comment by kistitan** [comment]
Hi all,

Issue has been fixed. Fix is available in version 1.7.20.
Already available to download:
https://github.com/fetlife/android/releases/latest

Notification will be sent out soon too.

Thank you.

**Comment by kistitan** [comment]
Hi all,

Issue has been fixed. Fix is available in version 1.7.20.
Already available to download:
https://github.com/fetlife/android/releases/latest

Notification will be sent out soon too.

Thank you.

**Comment by kistitan** [comment]
Hi all,

Issue has been fixed. Fix is available in version 1.7.20.
Already available to download:
https://github.com/fetlife/android/releases/latest

Notification will be sent out soon too.

Thank you.

**Comment by kistitan** [comment]
Hi all,

Issue has been fixed. Fix is available in version 1.7.20.
Already available to download:
https://github.com/fetlife/android/releases/latest

Notification will be sent out soon too.

Thank you.

**Comment by reneklacan** [comment]
> Indeed about page was not testes this time.

How come app tests didn't reveal it? 😛
