### ISSUE TITLE
Duplicate message being sent when reading a thread

### ISSUE THREAD

**Issue by MaryMagda** [fetlife/android#203]
I have a feeling this is going to be a hard to repro bug.

On three separate occasions, I have had the Fetlife app automatically resend the last text I sent in a thread when I read the thread.

I paid attention this time when it happened and the duplicate message seemed to already be visible in the thread and time-stamped for the exact time I opened the thread to read it.

So it looks like the app is sometimes re-sending the last text message sent when opening/reading a thread for some reason.

**Comment by kistitan** [comment]
@MaryMagda 

Hi MaryMagda,

Thank you very much for reporting this.
This bug can be indeed annoying.
And indeed hard to reproduce I gave a few try but could not.
I went through our code but did not find yet what can cause the issue.

What we can do is to add some extra checks in our code to be able to recognise when this happens, but I am afraid it will take some time, probably a few versions until we find it, but we will for sure.

May I ask if you use the latest version?

Thanks again for helping us out.

**Comment by MaryMagda** [comment]
I have updated to the latest version (1.7.20). The last time I had this happen was just the other day with version 1.7.18

The time before was about 16 days ago (so whatever version was current then).

I'm running Android 6.0

Thanks for looking into this.

**Comment by kistitan** [comment]
Extra logging added to this feature.
Waiting for the results for further investigation.

**Comment by kistitan** [comment]
Hi there,

Based on the logs we added previously we discovered a possible reason behind this issue.
We improved our code, so hopefuly it will work now as expected. 

Changes are in version 2.5.8.

Please feel free to let us know if it still occur time to time.
