### ISSUE TITLE
Fetishes: Soft & Hard Limits

### ISSUE THREAD

**Issue by Daddy** [fetlife/android#204]
**Description**

If you're at a dungeon or other venue and want to play with another individual, sometimes remembering or otherwise expressing all of your soft & hard limits can sometimes be a rather difficult task; a majority of people will bring a notebook or otherwise document on their phones that contain them all.

FetLife already has soft & hard limits, so let's make that experience even better by using the built-in system we already have with Fetishes.

**Suggested Outcome**

Add a Fetishes tab to the menu, which it's first view will display a quick link to "My Fetishes and Limits", which divides them by drop-downs and then displays them in a beautiful and clean manner. The Fetishes page will also display top fetishes on FetLife for easy browsing and to find similar minded individuals.

**Comment by kistitan** [comment]
@Daddy 

Hey Daddy :)
Long time no see!
I love your ideas.

We are at this moment working hard to get the feed in the app, but after we take a look at again what nice improvements can we pick up.

Thanks for this too!

**Comment by kistitan** [comment]
There is a separate todo list for having a feature full App, using webviews. 
As soon as we finish with it, the side effect will be that also these missing ones will be supported.
Closing this for now to avoid duplicate sources.
