### ISSUE TITLE
Double notifications

### ISSUE THREAD

**Issue by CrowandButterfly** [fetlife/android#206]
I turned on web notifications and since the update get two notifications for each tag, comment, message, etc. One comes from the website, one from the app.

**Comment by Two-Finger** [comment]
Just turn them off in the browser.
The app will keep notifying you.

**Comment by CrowandButterfly** [comment]
Nope, doing that turned off all notifications. In app and web based. 


Sent from my Sprint Samsung Galaxy S® 6.
-------- Original message --------From: Two-Finger <notifications@github.com> Date: 11/10/16  11:49 AM  (GMT-05:00) To: fetlife/android <android@noreply.github.com> Cc: CrowandButterfly <crow.butterfly11@gmail.com>, Author <author@noreply.github.com> Subject: Re: [fetlife/android] Double notifications (#206) 
Just turn them off in the browser.

The app will keep notifying you.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/fetlife/android","title":"fetlife/android","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/fetlife/android"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Two-Finger in #206: Just turn them off in the browser.\r\nThe app will keep notifying you."}],"action":{"name":"View Issue","url":"https://github.com/fetlife/android/issues/206#issuecomment-259742977"}}}

**Comment by Two-Finger** [comment]
Strange, it worked for me.

If you go to the Web Notifications tab under Settings, is there a yellowish bar reading
> Web notifications for this browser: Off Turn Them On Please

**Comment by kistitan** [comment]
Hi @CrowandButterfly 

Does the issue still occur?
Do I understand correctly that you face two issues:
- You turned off the notifications at the website but you still get email/browser notifications?
- You turned off the notification in the app but you still get app notifications?

Thanks for your help!

**Comment by CrowandButterfly** [comment]
@kistitan. If I turn notifications off in the app, they turn off for both app and web base. Same if I turn them off from web. So it's double or nothing, literally.

**Comment by CrowandButterfly** [comment]
Lmao, and now I'm getting two emails for every notification. My luck.

Sent from my Sprint Samsung Galaxy S® 6.
-------- Original message --------From: kistitan <notifications@github.com> Date: 11/11/16  8:01 AM  (GMT-05:00) To: fetlife/android <android@noreply.github.com> Cc: CrowandButterfly <crow.butterfly11@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [fetlife/android] Double notifications (#206) 
Hi @CrowandButterfly 

Does the issue still occur?

Do I understand correctly that you face two issues:


You turned off the notifications at the website but you still get email/browser notifications?
You turned off the notification in the app but you still get app notifications?


Thanks for your help!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/fetlife/android","title":"fetlife/android","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/fetlife/android"}},"updates":{"snippets":[{"icon":"PERSON","message":"@kistitan in #206: Hi @CrowandButterfly \r\n\r\nDoes the issue still occur?\r\nDo I understand correctly that you face two issues:\r\n- You turned off the notifications at the website but you still get email/browser notifications?\r\n- You turned off the notification in the app but you still get app notifications?\r\n\r\nThanks for your help!"}],"action":{"name":"View Issue","url":"https://github.com/fetlife/android/issues/206#issuecomment-259952504"}}}

**Comment by kistitan** [comment]
Hi there,

If you turn off in the app there is no server communication is made. 
So FetLife server has no information about.
It is a local setting that actually hide the notification from your tray so it cannot effect on receiving email notification or not.
However I do understand you face strange behaviour so we will run extensive testing and check what can go wrong.

Thank you for your patience.

**Comment by kistitan** [comment]
Hi @CrowandButterfly ,

One more note:
Basically if you use the app and also have you email notification turned on, you indeed can receive in notification both in the App and in email. This works as designed.

But you should be able to turn off both notification separately.
We tested these settings and did not manage to reproduce the issue and also did not receive similar feedback recently.

Can you please reopen this ticket if you still face the same behaviour?

Thank you for your understandings.
