### ISSUE TITLE
No notification sound in the latest app

### ISSUE THREAD

**Issue by MaxiM-PL** [fetlife/android#208]
Actually, I should say in every version I've got installed so far. I'm getting the notification in the tray, but when I tap it, the notification list within the app is completely empty, always. 

Issue #2 is that the tray notifications only work if I have them turned on in Chrome on my android device, but then I'm getting a notification from both the browser and the app. Once I turned off the web notifications in Chrome, FL app stopped notifying me at all.

Phone info: Samsung I9505 Galaxy S4, Android 5.0.1

**Comment by kistitan** [comment]
Hi @PixelPolish ,

Thank you for reporting this issue.
We will take a look at it as soon as we can.

**Comment by PixelPolish** [comment]
Errata: After testing, app notifications do show up in the tray, even when web notifications are off, but they are completely silent. The issue with empty notification list still stands though.

**Comment by kistitan** [comment]
Hi @MaxiM-PL,

Can you please confirm that the notifications are still silent even if your phone itself is not set to silent?
Notifications from FetLife app should use the default notification settings of your device.

Thank you.

**Comment by GojuSuzi** [comment]
Hey, I have this too although doesn't bother me. When not on silent, it
vibrates but no sound. Setting for the app itself are not set to silent,
and all other apps do their chirp. Been since the 2.0 preview right up to
2.0.4 on Android 7.0 on Nexus 6

**Comment by kistitan** [comment]
Thank you.
We will look unto this.

**Comment by kistitan** [comment]
Hi @GojuSuzi ,

May I ask if you still facing the issue?
We could not reproduce the issue on our test devices so to be the same side, can you please check the following settings on your device:
(The following location are for default Android OS, for Samsung they might be in a different state, but still should be similar)

Settings > Notifications > FetLife App
Please make sure both Block All and Show silently settings are turned off.

Settings > Sound > Default notification ringtone
Please make sure it is not set to none. Even if not please change it to something else than change it back and make sure you hear the notification sound you set.

Other applications might use their own ringtone, we use the device default, so let's make it sure it is set correctly first.

Thank you for your help

**Comment by GojuSuzi** [comment]
Oops, sorry, forgot to come back to this.

As of 2.5.0 it's all working fine (might have fixed prior, can't remember
when exactly it started bleeping at me again, apologies). So all resolved
from my side at least.

**Comment by kistitan** [comment]
Thank you for the feedback :)
