### ISSUE TITLE
V2.0 Preview - Feed - Comment pictures no link

### ISSUE THREAD

**Issue by Fbiss** [fetlife/android#210]
In the V2.0 Preview feed, when someone loves a picture you can click on the picture to see the picture bigger. When someone comments on a picture it does not have this same functionality yet (not user if it just hasn't been added yet).

**Comment by kistitan** [comment]
Hi @Fbiss,

Thank you for reporting this issue.
This will be fixed in the upcoming version!

Have a nice day and thank your for your help
