### ISSUE TITLE
v2.0 - Reading Message in App does not mark as read on website

### ISSUE THREAD

**Issue by kdom13** [fetlife/android#211]
Self-explanatory

**Comment by kistitan** [comment]
Hi @kdom13,

Thank you for letting us know about this issue.
In theory we invoke a call each time you take a look at a message on your phone to make it read at the website.
So the feature if there.

Please keep in mind, when the app receives notification about new message we retrieve the new messages right away. It can happen however that when you open the messages screen the set_message_read call does not arrive to the server in case of connection issues.

Can you confirm that this feature does not work for you with active internet connection?
Thanks a lot!

**Comment by kistitan** [comment]
Issue has been found and will be fixed in next version.
Thank you for the patience.
