### ISSUE TITLE
v2.0 preview - Buttons on pics too high

### ISSUE THREAD

**Issue by Two-Finger** [fetlife/android#212]
When you open a picture full-screen, especially one with caption that encompasses multiple lines, the "love" and "eye" buttons are pushed way too close to the center of the screen.
Exactly where the thumb will be used to slide down or sideways.
I, for one, feel like I'm gonna press them by mistake.

If they are always at the bottom of the screen (as in Twitter, for example) it will feel quite better.

**Comment by Two-Finger** [comment]
I just "loved" a pic from the app and it turned out that it's not that likely to be done by mistake, as only the icon itself is active.

Still, the layout is a bit misleading. Although there are no visible borders, the very alignment suggests that the buttons are cells in a table, and I thought the whole "rectangles" are active.
(Instagram have the buttons left-aligned, with no significant padding between them, and that makes it clearer that only the icons are active.)

**Comment by kistitan** [comment]
@Two-Finger 

Thank you very much for your suggestion and sorry for the slight delay in reply.
You first suggestion is already implemented. Description texts will be limited to 7 rows.

About the second suggestion:
I am going to make the hit area of the buttons a bit bigger so they will be easier to hit.

Thank you.

**Comment by Two-Finger** [comment]
@kistitan my suggestion was that the buttons were moved to the bottom of the screen.
So they are far from the area where one slides down/sideways and can tap them by mistake.

**Comment by kistitan** [comment]
@Two-Finger 

Thank you for the suggestion. It is also an option, we tried that too but in these case they get close to the navigation buttons what also caused several missclicks.

**Comment by Two-Finger** [comment]
@kistitan I see. I guess you can close this then, if it has been tried and proven worse.
As I already said, I never had a misclick with the current layout. It just felt this way.

Thank you!

**Comment by kistitan** [comment]
Ok so let me close this now as it was improved with the recent changes...
