### ISSUE TITLE
Suggestion on binding xml elements in activities

### ISSUE THREAD

**Issue by petkata** [fetlife/android#213]
Have you considered using [butterknife](http://jakewharton.github.io/butterknife/) for field annotations? It saves a lot of code and is very useful in my opinion.

**Comment by malachid** [comment]
Or the official Android databinding?

**Comment by kistitan** [comment]
hmm... I was never really got bothered by the usual way.
But maybe it worth the give a try and let's see how much development time does it actually save.

I will have some clean up task anyway after 2.0 I will give a try within that one.
Thanks!
