### ISSUE TITLE
Feed as first screen 

### ISSUE THREAD

**Issue by MetalHolic** [fetlife/android#216]
Would like a setting where you can set de feed as "homescreen/first screen" you see in the app

**Comment by PixelPolish** [comment]
I concur. Funny thing, I was looking for that option in the app just 20 minutes ago.

**Comment by reneklacan** [comment]
+1

**Comment by kistitan** [comment]
Sure, good suggestion.
In upcoming release we are going to make it to the first screen or make it configurable at settings.

Thank you for opening this issue,
