### ISSUE TITLE
Issue with people updating there getish list

### ISSUE THREAD

**Issue by MetalHolic** [fetlife/android#220]
When everything someone updaten there fetish list it will look weird and will only show 1 or 2 things.
In the picture is only one. While the person added 6 different things

**Comment by MetalHolic** [comment]
![screenshot_20161126-173040](https://cloud.githubusercontent.com/assets/23719944/20641725/76dd350e-b3fe-11e6-836e-c16432ea1887.png)

**Comment by MetalHolic** [comment]
![20161126_173447](https://cloud.githubusercontent.com/assets/23719944/20641741/acf447c2-b3fe-11e6-998c-c4267f05a6d8.png)

**Comment by kistitan** [comment]
Hi @MetalHolic,

Thank you for reporting this.
It definitely seems to be a bug.
We will loo into it.

Thanks

**Comment by kistitan** [comment]
Hi @MetalHolic,

I tried to reproduce the issue, but it seems to be working for me.
Depending on the time, fetishes grouped or added individually but it is still there and visible.
Can you see any different in grouping compared to the website?

What do you mean weird looking? What would you change?

**Comment by MetalHolic** [comment]
![screenshot_20161201-175435](https://cloud.githubusercontent.com/assets/23719944/20803409/6954ae68-b7ef-11e6-9eb4-24972471703e.png)
In this case it litterlly doesnt show any 1 of the added fetishesh

**Comment by kistitan** [comment]
Hi @MetalHolic ,

Thanks you now it is clear...
So the fetish story itself is handled only the message is not displayed.
That's a big help Thank you

**Comment by MetalHolic** [comment]
Well, when you look at the first pic in this threat, you can see it does display sometimes

**Comment by kistitan** [comment]
Postponed as not being able to reproduce yet

**Comment by kistitan** [comment]
Hi there,

This issue is solved in version 2.1.3

Thank you for your patience.
