### ISSUE TITLE
Automaticly logging off

### ISSUE THREAD

**Issue by MetalHolic** [fetlife/android#223]
Whenever i Wright a message to someone it will automaticicly log me off.

**Comment by kistitan** [comment]
Hi @MetalHolic,

This is a very strange issue.
May I ask if you use the remember me / always ask for password (depending on the version) checkbox during the login?

Thank you

**Comment by kistitan** [comment]
Hi there,

We have seen a connection issue with new conversations.
It might have been the same issue as you seen. 
Fix will be released in new version.
I close this issue now as it is not reproducible/duplicated.
