### ISSUE TITLE
URL for upgrade invitation

### ISSUE THREAD

**Issue by scottfurry** [fetlife/android#226]
When a new version is pushed out, on my Samsung Galaxy Note at least, a pop up notification is given. When I press that notification to start the download it takes me to a "**http://**github.com..." address. The download not initiate.

I end up going into my bookmarks, open up a page to project Readme.md page, and press the URL install link. The URL uses the "**https://**github.com..." and download begins instantly.

**Comment by kistitan** [comment]
fixed in version 2.1
