### ISSUE TITLE
App doesn't have a concept of "follows"

### ISSUE THREAD

**Issue by instit** [fetlife/android#227]
I've noticed that there's no way to see the list of people I follow/following me.
Also, feed doesn't include stories from people I follow.

I think it would be very useful to add that. Tried to contribute and try adding this myself but it looks like the API doesn't support follows yet.

**Comment by kistitan** [comment]
Hi @instit,

First of all thank you very much for trying to contribute. We are more than grateful for you browsing our code and playing around with it.

Indeed you cannot browse followed users at this moment only friends.
And it is a good feature request.
@reneklacan what do you say from API side?

On the other hand activity feed in the mobile app (should) DO include stories from followed persons too. If not that it is an issue, but according to my quick test it works fine for me.
Please let me note that app activity feed does not have the full story support as the website version has.
But most common story types (likes, new photos etc) should be supported both for friends and followed users.

**Comment by reneklacan** [comment]
@kistitan I am all for adding it to API, it should be doable in short time.

Stories of people you follow are definitely present on feed on Android App.

**Comment by kistitan** [comment]
This feature is available in the latest version.
