### ISSUE TITLE
Friend list doesn't update

### ISSUE THREAD

**Issue by darkside-xposure** [fetlife/android#228]
When I unfriend people  or vice versa, their username still appears on my friend list when I click the friend tab on the menu.

**Comment by darkside-xposure** [comment]
Thanks @kistitan

**Comment by kistitan** [comment]
Correction: Please use Settings > Profile Settings > Clear local User Data to have the workaround.

Fix for the original issue will be releases in the next version.

**Comment by kistitan** [comment]
fixed in version 2.1
