### ISSUE TITLE
No "Subject" line in new conversations.

### ISSUE THREAD

**Issue by TheKildar** [fetlife/android#231]

**Comment by TheKildar** [comment]
Steps to reproduce:
1. Create a new conversation

Only one unlabeled text field appears.  There's no separate area for "subject" and the body of the message.

**Comment by kistitan** [comment]
Hi @TheKildar,

Unfortunately I have to say this works as designed.
We are still working on the final design of web/app conversation and we might won'r have subject line in the future.
If you start a conversation from the App as of now the first message will be used as a subject.

Thank you for your understandings.
