### ISSUE TITLE
Starring a new message

### ISSUE THREAD

**Issue by MetalHolic** [fetlife/android#244]
If i am on fetlife on my browser.
And pressie the message button to someone i havent have a conversation with yet. It will open the app but wont give me a new message.
It will just go to the conversations menu on the app.

**Comment by kistitan** [comment]
Hi @MetalHolic,

Thank you for reporting this issue.
Please go through the following steps:
1. Go to your device settings
2. Select Apps
3. Select FetLife
4. Select Open by Defaults
5. Clear Defaults

Depending on Android version the steps above might be a bit different.


Basically whenever the you are about to open a link to conversation you can make decisions if you want it to be handled by you app or by the browser.
Some links can be already handled by the App, some links cannot be handled yet.
However if you selected once that you always want the app to be opened your device won't offer you to make a decision even though the App cannot do much with the link.

We will revise our current solution for handling links before full support in the app based on you feedback.  
 
Thank you for your patience.
