### ISSUE TITLE
Wall post links broken.

### ISSUE THREAD

**Issue by halsteaw** [fetlife/android#245]
Wall post links in the feed are broken.

1) The verbiage is weird E.g: "uploaded a new wall post"?
The website uses: "<user> wrote on <user>'s wall"

2) If I click on the link, I get a URL like: "https://fetlife.com/users/[user number]/wall_posts/[another number]" which doesn't work at all. I get FetLife's 404 page.

If I reduce it down to "https://fetlife.com/users/[user number]/wall_posts/", then I don't see the wall posts from the feed, I see things posted on the poster's wall.

**Comment by kistitan** [comment]
Hi @halsteaw ,

Thank you for reporting this issue.

@reneklacan Do you still any possibility that we receive an incorrect url via the API?

Thank you

**Comment by reneklacan** [comment]
@kistitan checking

**Comment by halsteaw** [comment]
I poked some more into the issue and this is the URL difference:

Website: fetlife.com/users/[target user]#wall_post_[wall post ID]

App Feed: fetlife.com/users/[source user]/wall_posts/[wall post ID]

**Comment by kistitan** [comment]
@halsteaw 
Thank you very much for your investigation, this seems to be useful.

@reneklacan

**Comment by halsteaw** [comment]
Appears to be fixed in 2.2 Preview.

"[user] uploaded a new wall post" is still awkward phraseology.

I think going with the website's "[user1] wrote on [user2]'s wall" would be better.

**Comment by kistitan** [comment]
Hi @halsteaw ,

Thank you for letting us know the result.
I keep the issue open for improving the English text

**Comment by kistitan** [comment]
Text update is merged into : https://github.com/fetlife/android/issues/171
