### ISSUE TITLE
Feature request: groups access

### ISSUE THREAD

**Issue by tclarke** [fetlife/android#248]
It would be great to have access to groups in the app, even if it's just a link in the signature to the website.

**Comment by jcogilvie** [comment]
@kistitan Are you guys planning on reusing the old APIs you built for us when you get around to doing this?  If so, I might feel like submitting a PR for at least some cursory ability to read a discussion on a group.

**Comment by kistitan** [comment]
Hi there,

Groups are supported by the latest preview version.
Thanks a lot for your patience.

@jcogilvie 
It is a shame I did not answer for this message earlier. 
I am really sorry, I try my best to keep track all of it, but appearantly sometimes I do mistakes.
Feel free to ping me directly via fetlife or email or here again if it happens again.

Thank you
