### ISSUE TITLE
Messages not always in the order sent

### ISSUE THREAD

**Issue by sjdebdaly** [fetlife/android#251]
If I sent messages to someone in quick succession (anywhere under 10 seconds between messages) they aren't always in the right order.  One of the previous messages will get stuck at the bottom of the pane, and new messages will be on top of it

**Comment by ReluctantSub** [comment]
# Ahah! 
Yes, I noticed issues like that tonight too. At first I thought it was my fault, as I was tinkering around with code near the adapter classes. Then remembered you had mentioned something like this. 

Thank god, or I would have most likely wasted ~5 hours trying to hunt down a bug which I DIDN'T even create!

**Comment by sjdebdaly** [comment]
I'll add that the timestamps under each message appear in the right order, but I definitely didn't send them in that order!!

**Comment by kistitan** [comment]
Hi sjdebdaly,

Thank you for keep investigating but you should not be bothered by the time stamps.
I think @ReluctantSub only expressed I think it happens to him as well.
It should be an issue on our side.
It is already under investigation.

Thank You

**Comment by kistitan** [comment]
Hi all,

We found one reason that might cause the issue.
If there are more than one pending messages and the first one is failed to be sent at the first trial we just move to the next one and try that.
This can cause the unexpected order.
We are going to change this in version 2.3.

Thank you for your patience.

**Comment by kistitan** [comment]
Fix available in version 2.3.0

**Comment by Seelenoede** [comment]
I just experienced this problem while using 2.3.0

**Comment by kistitan** [comment]
hmm.. that's strange.
Reopening than....

**Comment by kistitan** [comment]
Issue managed to be reproduced.
After fixing a client side issue, we found one more on server side.
A temporary workaround will be added in 2.3 and the final solution will be implemented in 2.4.

Thank you for your patience.

**Comment by kistitan** [comment]
Workaround in 2.3 will make the occurence bit less likely, but still will be there until better solution expected in 2.4

**Comment by AthenaUnbound** [comment]
Hi, I'm beta-ing 2.4 and it's still happening for me. Far less frequent than in previous releases, but still present.

**Comment by kistitan** [comment]
@AthenaUnbound ,

Thanks for reporting.
May I ask you if it happens again (or if you still can get back to those messages) to check the time of the messages in incorrect order?
Based on the time indication under them, are they sent in the same second, or in different seconds?

Thanks a lot!

**Comment by AthenaUnbound** [comment]
In different seconds; often it's like I've sent my reply *before* the
message that I'm replying to, even if I wait a full minute by my phone's
clock to reply.

Incidentally, to the person I'm talking to, the message appears out of
order *and* they're not notified of its arrival.

I'll see if I can get a screenshot of one.

Secondarily, messages sent via the app are compiling oddly on the website.
I'll screenshot that as well.

**Comment by AthenaUnbound** [comment]
OK, so here's an example of sending a few seconds *before* I received a
message.

**Comment by AthenaUnbound** [comment]
OK, and messages are now compiling correctly on the site.

**Comment by kistitan** [comment]
@AthenaUnbound ,

Thank you for all your effort.
We know already some issues that we are working on but we would like to narrow down the problem if this is a new issue or similar.
Do I understand correctly that you had a conversation with using the app having a chat partner who used the website?
Did you notice the order of your own messages mixing up or was it only the order of your messages and the replies?

Thanks again

**Comment by AthenaUnbound** [comment]
It was the order of both. In the app, apart from the timestamp issue I sent
the screencap of, everything was displaying fine. But apparently using the
messenger on the website, all of his comments came in a block, followed by
all of mine (no back-and-forth, if that makes sense.)

**Comment by AthenaUnbound** [comment]
OK, so here's what I'm talking about with messages appearing out of order
on the website. This screenshot is from the website; it's my reply to the
bottom message (sent via FL App), up there at the top of the screen. It's
got the correct timestamp, but it's completely out of the order of the
conversation.

**Comment by kistitan** [comment]
Hi all,

During the past weeks we discovered and fixed several small issues that might cause in theory this issue, however after a while it turned out the main reason was that one of our server instance was out of sync in time.
Our latest code changes can be found in our current preview version 2.5.

Thank you for your patience.

Please feel free to keep reporting this issue again if you still see it is happening.
