### ISSUE TITLE
Rotating app crashes foreground activity on Settings and About

### ISSUE THREAD

**Issue by jcogilvie** [fetlife/android#254]
...on my Android 7.x Nexus 6P.  App v2.2.

**Comment by kistitan** [comment]
hi @jcogilvie,

Thank you very much for reporting this issue. 
I could not reproduce it yet on same environment and Nexus 5X but we are looking into it.

**Comment by kistitan** [comment]
hi @jcogilvie,

We still cannot reproduce the issue. Also did not see and crashes that we could connect to this behaviour.

May I ask if you use any special developer settings?
Is it happen all the time or did happen only once?
Crash you mean real crash or just the given screen (about, settings) is closed (what actually works as designed)

Thank you

**Comment by jcogilvie** [comment]
It's not an uncaught exception (not a force close) but the expected behavior would be to reorient the screen I'm on to the direction my phone is facing, or else lock the activity in portrait mode. Closing the activity without me explicitly asking to gave me the appearance of a crash.

(This is @svtdragon by the way; I worked with Malachi on the unofficial fet app.)

**Comment by kistitan** [comment]
Fix available in version 2.3.0
