### ISSUE TITLE
2.2.1 (Inconsistent Certificates)

### ISSUE THREAD

**Issue by ReluctantSub** [fetlife/android#257]
I can not seem to get our 2.2.1 apk to install on any of my emulators because of Inconsistent Certificates...

Though this may be partly due to my newbieness to Android's ecosystem... Had no issues with prev releases on Arc Welder or BlueStacks.

**Comment by kistitan** [comment]
Hi @ReluctantSub ,

For security reasons we do SSL Pinning so only communication to FetLife API will be accepted.
If you use and emulated API or use the API via other server communication will fail.

If you would like to play around with the App, you should disable the SSL Pinning our add the appropriate certificate.
SSL Pinning is done in FetLifeService class.

Let me know if you needed more help.
