### ISSUE TITLE
From settings clicking in-app back or back soft button closes app

### ISSUE THREAD

**Issue by BmetaMax** [fetlife/android#258]
Android 7, phn xt1650. From settings clicking in-app back or back soft button closes app; when I go into settings, regardless of submenu, tapping either the back arrow in the app (left of menu name) or my phone's back soft-button closes the app entirely instead of backing out of menu. The same actions work correctly in messages, I checked twice.

**Comment by kistitan** [comment]
Hi @BmetaMax ,

Thank you for reporting this issue.
Can you please let us know the App version?
Do you use the Feed or the Conversations as your starting screen?

**Comment by BmetaMax** [comment]
No problem, its version 2.2.0, and starting is conversations.On Jan 12, 2017 14:22, kistitan <notifications@github.com> wrote:Hi @BmetaMax ,
Thank you for reporting this issue.
Can you please let us know the App version?
Do you use the Feed or the Conversations as your starting screen?

**Comment by kistitan** [comment]
Fixed, Fix will be available in 2.3 preview version.

**Comment by BmetaMax** [comment]
Great thanks for the follow up too!On Jan 14, 2017 9:57 AM, kistitan <notifications@github.com> wrote:Fixed, Fix will be available in 2.3 preview version.

**Comment by kistitan** [comment]
Fix available in version 2.3.0
