### ISSUE TITLE
Starting a conversation with users who are not friends

### ISSUE THREAD

**Issue by kistitan** [fetlife/android#259]
Follow up from : https://github.com/fetlife/android/issues/205

**Comment by trinitymaywen** [comment]
So on my Galaxy S7 edge, I had set the app to be the default for replying to messages.  I just tried to message a person not on my friends list, was sent to the app, no way to put them in.  So I went into my settings and removed all preferences, closed the app.  Tried to send a message to said person, and it is still defaulting to the app.  Do we have a work around, or do I need to uninstall/reinstall at this point?   So far the few issues with the app I have are not to bad, but this will be a deal breaker on it unless it is fixed.  How are we supposed to contact people not on our friends list if the app does not let us?

**Comment by thezerogod** [comment]
until/unless the devs get around to adding messages to users that aren't
already your friends, you have to message non-friends from the browser. to
manage this, you should modify the default behaviour (and enable messaging
within the browser) by changing the following setting:

*phone settings > apps > fetlife > open by default > open supported links*

you can change this setting to "ask every time" or "don't open in this app".

i got this setting path from a nexus 6 runing android 7.1.1; your option
names may look slightly different.

**Comment by kistitan** [comment]
Issues has been discussed in private message. Removing default somehow did not work on the user's device. App should have been reinstalled.

Opening conversation link with App will be removed until full support.

**Comment by threetwoonezero** [comment]
Just an FYI - this link is back in the 2.6.11 preview version.

**Comment by kistitan** [comment]
@threetwoonezero 
Indeed... Even earlier :(
It was a merge mistake from myself.

Thanks a lot for letting me know about.
Will remove it again in next version.

**Comment by kistitan** [comment]
It is supported in new versions,

Thank you for your patience.
