### ISSUE TITLE
Clicking a users profile tries to open it in my browser instead of the app

### ISSUE THREAD

**Issue by jabar22** [fetlife/android#260]
???

**Comment by jabar22** [comment]
Almost everything is doing this, not just profiles...

**Comment by ReluctantSub** [comment]
This is working as intended (for now).
You can't browse groups, etc, within the app (yet).

**Comment by kistitan** [comment]
Hi @jabar22,

Thank you for reporting this issue.
Indeed the In App Profile screen is still under design. 
Current solution is only temporary.
Please follow up this issue for more details : 
https://github.com/fetlife/android/issues/188
