### ISSUE TITLE
Getting logged out when switching from FetApp to another app.

### ISSUE THREAD

**Issue by NYCQueen** [fetlife/android#261]
I was logged in to the FetApp when I got a message, went to view it and when I came back to the FetApp I had to log in again. It happened x 3.

**Comment by kistitan** [comment]
Hi @NYCQueen,

Can you please confirm that when you log in the "Remember me" check box is checked?
By default you are indeed automatically logged out each time you leave the app.
Unless you check the "Remember me" checkbox.

Thank you

**Comment by NYCQueen** [comment]
Even when it is just going to read a expected message?  

Even when you didn’t close the app?  

Logging me out when I close the app or request logging out is more conducive to using the app.

**Comment by kistitan** [comment]
Hi @NYCQueen,

Yes. This is an important security feature for some users who really care about their privacy even in those case. Like in case they are disturbed by a phone call or giving away their phone to someone else.
Obviously FetLfe App won't track your activity so we cannot know if you read a message or answering a phone call or just switch quickly to the home screen before your roommate enters your room. All we know that you abandon the App.

But this behaviour obviously can be avoided by using the "Remember Me" checkbox during login.

**Comment by NYCQueen** [comment]
OK, I get why you do it that way. The remember me box was not selected.

Thanks for the info.
