### ISSUE TITLE
API access - OAuth client registration

### ISSUE THREAD

**Issue by xiinite** [fetlife/android#263]
I saw in the code that you are using an API that's authenticating through OAuth.
Is there a way for other developers to registers clients for OAuth?

**Comment by kistitan** [comment]
Hi xiinite,

Thank you for raising this question.
As of now for testing you can use the api client id and client secret that is presented in the repo.
For the actual release version we use different client id and secret.

For future... it should be a subject of an internal discussion.

@reneklacan 
What do you think?

**Comment by xiinite** [comment]
Thank you kistitan, but won't the OAuth server refuse my request because my return uri is invalid / different from your app?

**Comment by kistitan** [comment]
Current API is designed for Apps so it has a specific hard coded return uri (also can be found in the repo), to make it work you indeed should use that one.

**Comment by xiinite** [comment]
Ah, I understand, I'm a JavaScript guy, I was looking to possibly built a chrome extension. Guess that will have to wait.

**Comment by kistitan** [comment]
Yes I am afaraid it will take a bit longer, but if it happens we will announce it for sure.

Thank you for your question :)

**Comment by xiinite** [comment]
Hi guys,

Any more information about this? I've been browsing groups recently, and I'd love to make some social media games with FetLife accounts through OAuth. Specifically, I've seen a lot of games play the 'fuck or pass' game, and I think I could make a fun web app around that.

Kr,

Joey

**Comment by kistitan** [comment]
@johnbaku @reneklacan 

Do we have any plans for opening up our API any time soon?
