### ISSUE TITLE
Incorrect image orientation in the cropping view for some devices. 

### ISSUE THREAD

**Issue by NyRyan** [fetlife/android#268]
Greeting support staff of FetLife,
I'm contacting you to inform you that you're new update is causing the picture to turn from Portrait to Landscape... even though I want the picture to specifically be in Portrait (Unless this was intended)...  

How to replicate the bug:
1) Open up the FetLife App [v.2.4.0]
2) Open up the Menu
3) Select "Upload Photo" option
4) Optional: Select Camera or Gallery... Both replicates the same action, but for this example let's just select camera.
5) Take a regular Portrait photo
6) Hit accept and you'll notice your Portrait photo just turned into a landscape portrait and upon uploading it to your account will result in a landscape picture.

Android Detail:
Manufacture: Samsung
Device Name: Galaxy Grand Prime
Model#: SM-G530T UD
Android Version: 5.1.1

**Comment by kistitan** [comment]
Hi NyRyan,

That can be annoying.
Thank you for reporting.

May I ask if you did use the cropping tool?
Did you make any rotation with the cropping tool?
Did it look correctly in the cropping view?

Thanks a lot again.

**Comment by NyRyan** [comment]
Hey Kistitan,

Woops ;~; --- Didn't realize the rotate button D:

To answer your question now... 

Okay, so I went back into the application and notice the rotation too and it does set it back to the Portrait view... and the upload on the profile showed up as it should be now...

However--- still minor bugs (or what I believe to be minor bugs).

1)Taking a Portrait photo from the either the Camera or Gallery still causes the cropped function to automatically assume that the picture was taken in Landscape and sets the picture to 90° counter clockwise... In order to set the picture you need to click it the rotation tool.. Once...

2) Lol... since I like to break stuff... I was curious to see what happens if I use the 'Selfie' Camera... I don't plan on showing my face yet... But I was still curious... Apparently --- any pictures taken with the Selfie Camera... Including those in the Gallery will automatically rotate the camera 90° Clockwise... Which means the user would have to rotate the picture 3 times to get it in it's correct position--- I have yet to see what happens if I upload it however. So sorry Kistitan.

**Comment by kistitan** [comment]
Hi @NyRyan,

Thank you very much for your deep investigation :)
I tried to reproduce the minor bugs you mentioned but I could not do it with our test devices.
Might be camera specific?

May I ask what device, OS version etc do you use?

Thanks a lot

**Comment by NyRyan** [comment]
It's a Samsung Galaxy Grand Prime, Model Number is SM-G530T.

Since the Android Version is 5.1.1... It's going to be Lollipop.

As for the camera: 
Front Camera: 5 MP  
Rear Camera: 8 MP

**Comment by kistitan** [comment]
Thanks, again...

Well actually still no issues found in our code that could cause this issue.
On all test devices it work correctly.

What we can do maybe to try different cropping library, but it can take some time...

**Comment by kistitan** [comment]
Hi there,

As we did not hear other issue about the current cropping and workaround exist I close this issue now.
In the meanwhile we keep updating out used library to he latest version.

Thank you

Thank you
