### ISSUE TITLE
Notification Sounds

### ISSUE THREAD

**Issue by Matrixunlimited** [fetlife/android#269]
Any chance of someone adding a notification sound option to settings. Very annoying that phone vibrates but no sound notification.

**Comment by kistitan** [comment]
Hi @Matrixunlimited,

Thank you for reporting this issue.
FetLife App notification in theory uses the default notification settings of your phone.
Can you please confirm your notification settings is not set to vibrate only and you have a valid notification sound set?
Can you please also let us know what device do you use?

Thanks a lot

**Comment by Matrixunlimited** [comment]
Samsung s6. Sound is on, but it's doesn't make a noise.

**Comment by kistitan** [comment]
Hi @Matrixunlimited ,

Thank you for the info.
We could not reproduce the issue on our test devices so to be the same side, can you please check the following settings on your device:
(The following location are for default Android OS, for Samsung they might be in a different state, but still should be similar)

1.
Settings > Notifications > FetLife App
Please make sure both Block All and Show silently settings are turned off.

2.
Settings > Sound > Default notification ringtone
Please make sure it is not set to none. Even if not please change it to something else than change it back and make sure you hear the notification sound you set.

**Comment by Matrixunlimited** [comment]
I will try it again to see it works

**Comment by kistitan** [comment]
thanks

**Comment by kistitan** [comment]
Hi there

We still not able to reproduce this issue.
Please feel free to reopen if it is still occuring.

Thanks
