### ISSUE TITLE
Missing translations in release

### ISSUE THREAD

**Issue by Seelenoede** [fetlife/android#270]
Not really an issue, I think.

I noticed that the recent german translations (and the fixes for the typos) are not in the recent releases (both 2.3.2 and 2.4.0).
According to the commit number they should be in there.
The translations are there if I build the apk myself from the recent master branch.

Maybe I am missing something but I think it is kinda weird.

**Comment by kistitan** [comment]
Hi @Seelenoede ,

This is indeed strange as all pull requests got merged to master.
Do you remember a specific string or change I can look for to see if it is lost and if yes, where?

Thank you.

**Comment by Seelenoede** [comment]
My last two pull requests are missing. 
For example the typo "liebte einn Text" (<string name="feed_title_like_writing">liebte einn Text</string>) is still there. I changed that in #265.
Also the translations for the settings for the app flavor are missing.

**Comment by Seelenoede** [comment]
Fixed in 2.5.0
