### ISSUE TITLE
Single photo display problem

### ISSUE THREAD

**Issue by vizman2** [fetlife/android#271]
I've been experiencing an issue on my Lenovo P780 with displaying single photos in the feed list. Whenever someody posts or likes a single photo I can only see a thin vertical line. No such problem exists with multiple photos being liked or posted by a user. Take a look at [this screenshot](http://i63.tinypic.com/b54orp.png) that shows the issue.

Thanks for any suggestions.

**Comment by kistitan** [comment]
Hi @vizman2,

Thank you very much for reporting this issue.
Well unfortunately no suggestion yet. It is very weird.
We are going to look at this.

**Comment by vizman2** [comment]
I agree that this is very unusual.
I also noticed that the area with the mis-displayed photo bursts like a bubble when tapped.
You make take a look at [this video](https://sendvid.com/r8mp6y3a) that better explains what I mean.

**Comment by kistitan** [comment]
Thank you for helping us out.
We are on it

**Comment by kistitan** [comment]
Hi @vizman2,

I added some changes to our latest preview version that might help with your issue.
Unfortunately as I cannot reproduce it I cannot test if it really helps.

Would you mind give a try and give us some feedback?

Thanks a lot:

New version:
https://github.com/fetlife/android/releases/download/v2.5.4/fetlife-2.5.4.apk

**Comment by vizman2** [comment]
Looks like you have found a solution :-)
Here's [a couple of screenshots](http://pl.tinypic.com/r/2q2ects/9) of how the photos are displayed now.
The photo will now open in a new screen when tapped, so it seems to act as expected.
Thanks again!

**Comment by kistitan** [comment]
Hi @vizman2 

I am glad it works.

Thanks for reporting.

May I ask you to remove now the screenshots and video uploads, to be sure the privacy of the users will be kept safe?

Thanks again.

**Comment by vizman2** [comment]
Hi  @kistitan,

The problem described in this thread was solved until I downloaded the recent version 2.12.9.
Multiple pictures aren't diplayed in the Feed again on my phone. Screenshot attached.

![2017_11_17_14 50 15](https://user-images.githubusercontent.com/25622476/32950792-f26c32a8-cba7-11e7-99cf-46ea24021508.png)
