### ISSUE TITLE
Connection Failed, Please Try again Later

### ISSUE THREAD

**Issue by Holsann** [fetlife/android#272]
The message "connection failed, please try again later" comes up every time I open the app.  It happened every once in a while before,  but with 2.5.0, it's now every time.  I'm using a S6. I'm guessing this and the inability to have messages go through are connected.  The feeD updates, all other apps work, and I have full connection on my phone for both wifi and data. It's a bit maddening, watching all my replies just stay in limbo.

**Comment by kistitan** [comment]
Hi @Holsann,

Thank you for reporting this issue.
Would it be possibly for you to help out with the following investigation?

1. 
Please go to your device's Settings > App Settings > FetLife 
and there use Force Stop than go to Storage info and use Clear Data.
Please try again.

2.
If it does not help, can you please reinstall 2.4.0 version?
Does message sending work with 2.4?
If it does, can you please reinstall 2.5 and check if it still not working?

Thank you.

**Comment by kistitan** [comment]
If neither of them helps please install our new pre-view version I added some extra logging so we will have a slightly better chance to track this issue down.

Thanks a lot.

Or newest preview version:
https://github.com/fetlife/android/releases/download/v2.5.4/fetlife-2.5.4.apk

**Comment by Holsann** [comment]
Forcing to stop and clearing data worked perfectly!! Thanks so much!

**Comment by kistitan** [comment]
Hi @Holsann,

I am happy it work, we will try to improve our code to not have this issue occuring again.
If it would, please feel free to let us know about.
