### ISSUE TITLE
Feature request : Add events to API

### ISSUE THREAD

**Issue by erickgirard** [fetlife/android#273]
Following the discussion on #238 I thought it would be best to put it here. 

Would it be possible to expose via the API and/or App the events ?

**Comment by kistitan** [comment]
Hi @erickgirard,

Event is a bit lower on our priority list but it definitely going to be part of our API.
Let me ask our API developer:

@reneklacan What do you think?

**Comment by erickgirard** [comment]
Good to know. At least if this could be accessible via the API it would be interesting for a project that I am creating. @Hypersapien also expressed the interest in such feature. :smile_cat:

**Comment by alias1** [comment]
I would also really love to have this ability. It seems I rarely log on to FL these days, but still want a nice way to be able to see what events are coming up, and sync them into my calendar, etc.

**Comment by kistitan** [comment]
Event features are already supported.
Closing this for now
