### ISSUE TITLE
Cannot remove deleted conversations from the app

### ISSUE THREAD

**Issue by BullDaddy** [fetlife/android#274]
I have deleted conversations from the desktop yet, they reside in the app. In the app, I get "connection failed. Please try again later" when I try to tap on the conversation to delete it.

**Comment by kistitan** [comment]
Hi @BullDaddy

Thank you for reporting this issue.
To be honest I have just recently closed the same issue as I could not reproduce it anymore.

May I ask what version of the app do you use?
Can you confirm that your phone is connected to the internet when the conversation is still visible?
(It can take some time to sync with the server).

Can you please go to App Settings > Profile Settings > Clear local user data?

It should remove the deleted conversation.
Can you please confirm that?
Thank you

**Comment by BullDaddy** [comment]
Version 2.4.0

Im connected to the net and 'clear local user data" did work. Thanks


On Feb 20, 2017 12:03 PM, "kistitan" <notifications@github.com> wrote:

Hi @BullDaddy <https://github.com/BullDaddy>

Thank you for reporting this issue.
To be honest I have just recently closed the same issue as I could not
reproduce it anymore.

May I ask what version of the app do you use?
Can you confirm that your phone is connected to the internet when the
conversation is still visible?
(It can take some time to sync with the server).

Can you please go to App Settings > Profile Settings > Clear local user
data?

It should remove the deleted conversation.
Can you please confirm that?
Thank you

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fetlife/android/issues/274#issuecomment-281180768>, or mute
the thread
