### ISSUE TITLE
Group Conversations and Posts

### ISSUE THREAD

**Issue by tracicollins** [fetlife/android#275]
Please add more group functionality to the app. On the feed page of the web site one of the menu items is to choose the group feed. It would be wonderful to have a similar option here, even better if that could be made a default.  And of course, having the group feed means you can go to the groups to read, post and reply.

**Comment by kistitan** [comment]
Very good suggestion, thank you.

As of now our next big feature will be the in-app profile screen.
After that one option will be the next version of the feed that can involve that feature too.
Let us think about a bit of the priorities.

Thanks again

**Comment by kistitan** [comment]
Group functionality is part of the App now, so closing this issue.
Feed page is planned to be imporved as part of a different issue.
