### ISSUE TITLE
Chat/Profile Push Buttons

### ISSUE THREAD

**Issue by summer242009** [fetlife/android#278]
In the new pre-release version of the Fetlife App whenever I touch one of the push buttons for the shortcuts to view other members profile while talking to them online the App stops working abruptly kicking/forcing me off of it.

**Comment by kistitan** [comment]
Hi @summer242009 ,

Thanks you for reporting this issue.
Please keep in mind for the new version you have to log in again and if you want the app keep you signed in please don't forget to check the remember me check box when you log in.

Can You please confirm this solved your issue?

Thank You

**Comment by mocafet** [comment]
I have the same issue.  When I press on someone's profile picture and it loads up their profile, all of the different panes (photos, friends, status') work but as soon as I touch one the buttons for profile or message or friend I get 

Fetlife stopped responding and closed.  Once I clear the message the app reopens to the same spot.

**Comment by mocafet** [comment]
Correction:

The error is "unfortunately, fetlife has stopped"

**Comment by kistitan** [comment]
Hi @summer242009  and @mocafet 

Thank you for reporting this issue.
Can you please check the newest version and let us know the result?

https://github.com/fetlife/android/releases/download/v2.6.5/fetlife-2.6.5.apk

Thank you

**Comment by summer242009** [comment]
Right after I downloaded the app it closed the app with the notification that it "stopped working" right away.

Best Regards, 



Krystal Reynolds
503-713-8867
summer242009@yahoo.com 
 
  On Thu, Mar 23, 2017 at 3:31 PM, kistitan<notifications@github.com> wrote:   
Hi @summer242009 and @mocafet

Thank you for reporting this issue.
Can you please check the newest version and let us know the result?

https://github.com/fetlife/android/releases/download/v2.6.5/fetlife-2.6.5.apk

Thank you

**Comment by mocafet** [comment]
@summer @Kistitan,

Likewise when I downloaded the app it was pretty much instant force close. 

I went into my settings > apps > manager and cleared the data and cache. 

I logged back in and now it is working as designed.

**Comment by summer242009** [comment]
Yes, it's now working on my phone too. Thank you for your help Kistitan.

Best Regards, 



Krystal Reynolds
503-713-8867
summer242009@yahoo.com 
 
  On Thu, Mar 23, 2017 at 4:57 PM, mocafet<notifications@github.com> wrote:   
@summer @Kistitan,

Likewise when I downloaded the app it was pretty much instant force close.

I went into my settings > apps > manager and cleared the data and cache.

I logged back in and now it is working as designed.

**Comment by kistitan** [comment]
Thank you!

Can you please check 2.6.6?

Thanks!

**Comment by mocafet** [comment]
Hey @kistitan

I just pulled down the 2.6.6 and tried it out. The in app profile screen is working. The icon links all work for friend/follow/message/profile. As well as the various panels for status/photos/about

Thanks for all your help!

**Comment by SqueekyST** [comment]
My profile buttons are also saying unfortunately fetlife has stopped. The apk links above are giving me 404 errors

**Comment by kistitan** [comment]
Hi @SqueekyST ,

Yes indeed int the meanwhile we have new version:
Can you please use this link?
 https://github.com/fetlife/android/releases/download/v2.6.11/fetlife-2.6.11.apk

Or later only: 
https://github.com/fetlife/android/releases/

Thanks a lot

**Comment by SqueekyST** [comment]
The buttons now work, although the buttons don't fit fully on the page, the 4th one is just barely visible enough to select and I can't see what the icon is.

**Comment by kistitan** [comment]
@SqueekyST 

Thank you for letting us now.
We will work on the screen issue.

**Comment by kistitan** [comment]
Merging this into 
https://github.com/fetlife/android/issues/292
