### ISSUE TITLE
Profile Compass link causes crash

### ISSUE THREAD

**Issue by BejeweledReverie** [fetlife/android#279]
When I attempt to click the compass/navigation image next to a person's profile image on their profile page it crashes the app.

**Comment by BejeweledReverie** [comment]
This is with the v2.6.0

**Comment by kistitan** [comment]
Hi @BejeweledReverie ,

Thank You for reporting this issue.
We are on it.

**Comment by kistitan** [comment]
Hi there,

Issue should be fixed in 2.6.2.
(Further improvements can be expected before 2.6 released as final version)

Thanks again!
