### ISSUE TITLE
No pics/vids thumbs displayed in user's profile

### ISSUE THREAD

**Issue by vizman2** [fetlife/android#280]
I have Lenovo P780 and noticed that on the latest pre-release no pics/vids thumbs are displayed when I enter a user's profile. All thumbs appear as rows of thin lines. Please take a look [here](http://www.tinypic.pl/3r6hy9oug91z). Some time ago I reported a similar issue with pictures in the main feed and it was quickly fixed.

**Comment by kistitan** [comment]
Hi @vizman2 ,

Sorry for facing the same issue again.
In code level the previous solution was kept, but made some changes that could help again.

Can you please newest version?
https://github.com/fetlife/android/releases/download/v2.6.5/fetlife-2.6.5.apk

Thanks a lot

**Comment by vizman2** [comment]
Hi @kistitan ,

Now I can see all thumbs properly.
Thanks again for a quick fix
