### ISSUE TITLE
Feature Request: latest activity; in app profile 

### ISSUE THREAD

**Issue by mocafet** [fetlife/android#281]
Hey everyone,

Not sure if this was brought up before, I took a quick scan and I didn't see anything so I figured I would mention it. 

I know the in app profile only recently dropped and I love it!  What I would like to see is maybe a panel with latest activity.  Even if it was a condensed version.  In my opinion it would fit right in with the bio, about and status updates etc.  

Keep up the awesome work!

**Comment by kistitan** [comment]
Hi @mocafet ,

Thank you very much your feedback!
It would be indeed a great improvement. 
It is definitely on our list.
Please give us a bit of time as we also refactoring a bit the main activity feed and this two are related and best to done together.

Thank you for your help and understandings.

Note: Also In App Profile Screen is still in preview mode, further changes are coming soon (for example pagination for images / videos etc. do not work yet)

**Comment by kistitan** [comment]
Hi there,

I close this issue is it has been already added.

Thank you

**Comment by DinahJochebed** [comment]
There still seems to be some difficulty with the preview feature of profiles. I try to touch the preview button at the top of the screen of profiles but it doesn't seem to work. Is there an updated version of the most current app? Has there been any other reports since then about this issue? Thanks for the help.

**Comment by navyguyg** [comment]
@DinahJochebed The "Preview" at the top of the screen is letting you know that you are using a preview version of the app. It has no function. https://github.com/fetlife/android/releases/ is the location to find the latest releases of the app.
