### ISSUE TITLE
follow button in the profile page

### ISSUE THREAD

**Issue by MasterBlueEyes88** [fetlife/android#283]
with the new update i saw a compass in my own profile. 
so i thought is was to see my location .
i was like wtf they now where i am now?
but it is the follow button.
 now is the problem is i tried the button
 i can follow myself but cant turn it off.
what can i do now?

with kind regards

MasterBlueEyes88

**Comment by mocafet** [comment]
I was able to replicate on 2.6.6

I went into the app settings and cleared the local data. That succeeded in cleaning the follow icon on the app, but the website still shows me as following myself.

**Comment by kistitan** [comment]
Hi @MasterBlueEyes88 , @mocafet ,

It is indeed a bug in current version.
We will release soon an App version where you can turn off following.
Please give us a bit of time to solve the frequent crashes first, and come back to this issue after.

Thanks a lot for your understandings.

**Comment by Two-Finger** [comment]
@mocafet, you can still unfollow yourself on the website. Just go to View Your Friends, Followers tab, find yourself  and click "unfollow". I made the same mistake :-)

**Comment by mocafet** [comment]
@twofinger

Brilliant! Worked like a charm. Thanks!

**Comment by kistitan** [comment]
Hi all,

@Two-Finger Thank you for helping us out with the workaround.
It did not come into my mind. Thanks :)

The mistake btw was not yours but ours ;)
We will fix it soon!

Thanks again

**Comment by kistitan** [comment]
Will be fixed in next version...
