### ISSUE TITLE
[2.6.6] - possible bug - Love icon lit up

### ISSUE THREAD

**Issue by mocafet** [fetlife/android#284]
Hey everyone, 

I may have stumbled across a possible bug in 2.6.6. When I was looking at my feed I noticed that every photo was already 'loved' the heart was already red.  Even on one's I have not seen before. 

Steps to reproduce: 
Choose any shared photo or uploaded photo in feed 
Attempt to love that photo.

Expected behaviour:
The love icon to be grey so that I could tap it to 'love' a photo
Or
The love icon to be red so that I could unlove a photo

Actual behavior:
Nothing happens as it is 'already loved' and tapping it does not unlove. 

Please see screenshot for example. It has been edited to protect privacy
![2017-03-24_02 37 19](https://cloud.githubusercontent.com/assets/24795197/24281559/86c3c7ae-103c-11e7-87e2-fbab73b5847d.jpg)

**Comment by kistitan** [comment]
Indeed. It is an annoying bug!
Going to be investigated.

Thank you for reporting!

**Comment by kistitan** [comment]
Hi @mocafet,

Thank you again for reporting this issue.
It should be solved in version 2.6.8

Thanks again.

**Comment by DinahJochebed** [comment]
@kistitan,  @mocafet Hi has this issue been resolved in the latest version of Fetlife Apps for Android? I seem to be having difficulty with the app downloading the most current app. Is there a newer updated version? Thanks for your help.
