### ISSUE TITLE
Incorrect setup message given when trying to downgrade

### ISSUE THREAD

**Issue by sjdebdaly** [fetlife/android#286]
I noticed this with multiple versions while there was the unstable preview build yesterday.

If you have a newer version installed and try to just reinstall an older version, you get an error saying "App not installed.  The package appears to be corrupt".

It took me a few tries to realise I needed to uninstall first.  If this is not an Android issue, maybe something saying "you have a newer version installed, or an option to roll it back?

**Comment by kistitan** [comment]
Hi @sjdebdaly,

Yes I am sorry, but this is indeed coming from the Android OS.
We have no influence on this message :(

But we try to do it better so you won't need to downgrade next time.

Sorry for the inconveniences.
