### ISSUE TITLE
photo upload 

### ISSUE THREAD

**Issue by zenwarrior88** [fetlife/android#288]
Crashed app twice trying to upload a photo from gallery.

**Comment by kistitan** [comment]
Hi @zenwarrior88 

Thank you for reporting we are looking into this.

**Comment by kistitan** [comment]
Hi @zenwarrior88 

May I ask what version of the App do you use?

Thank you!

**Comment by darkndty** [comment]
I am using v2.6.11 on a Galaxy Note 3 and the upload photo isn't working any more (was in previous version)

It let's you select a picture but doesn't go to the crop screen and goes straight back to the conversations list.

**Comment by kistitan** [comment]
@darkndty 

Thanks for the information.
We saw some device permission issues with photo upload.
Could you please give a try with version 2.6.15 and let us know if it work with it?

Thanks a lot

https://github.com/fetlife/android/releases/download/v2.6.15/fetlife-2.6.15.apk

**Comment by darkndty** [comment]
Hi Kistitan,  it is working with version 2.6.15.  Many thanks.
