### ISSUE TITLE
having to login after a period of inactivity 

### ISSUE THREAD

**Issue by zenwarrior88** [fetlife/android#289]
Even though the "login settings" Always ask for a password....is unchecked I've had to keep logging in after an unknown period of inactivity.  Insta

**Comment by kistitan** [comment]
Hi @zenwarrior88 

May I ask what version do you use?
In newer version we use the "Remember me" check box.
Did you updated recently?

Can you please check what is the actual text?

Thank you!

**Comment by zenwarrior88** [comment]
v2.6.8

**Comment by zenwarrior88** [comment]
And yes I've checked Remember me every time.

**Comment by kistitan** [comment]
Hi @zenwarrior88,

Yes in this case it is indeed a bug, that might be related to the recent crashes.
That was caused by issue with the user database update.

Can you please check 2.6.11?
It was just released a few seconds ago.

Thank you!

**Comment by zenwarrior88** [comment]
That seemed to resolve the login issue

**Comment by kistitan** [comment]
Hi there,

Thanks for letting us know :)
It is good news.

**Comment by zenwarrior88** [comment]
Hasn't happened with 2.6.15 yet today 4/3/17
