### ISSUE TITLE
Frequent logins

### ISSUE THREAD

**Issue by SqueekyST** [fetlife/android#291]
My app is suddenly making me log in several times a day even though I keep selecting to remember my login.

**Comment by TipsyInk** [comment]
I'm having the same issue!

**Comment by sockpopstar** [comment]
Same here. I've had to log in every time I open the app.

**Comment by zenwarrior88** [comment]
Having the same issue again.

**Comment by kistitan** [comment]
Hi all,

Thank you for reporting this issue.
May I ask which version do you use?
Did you do any recent App update?

Can you check with our latest version if it is still happening?

https://github.com/fetlife/android/releases/download/v2.6.15/fetlife-2.6.15.apk

Thanks a lot for your help and patience

**Comment by SqueekyST** [comment]
The issue was with 2.6.11
I've had it installed a few days, but this issue only appeared today. I'll test the new one.

**Comment by kistitan** [comment]
@SqueekyST 

Thank you for giving a try, however there was not relevant change in this area between the two versions.
So as far as I understood it worked perfectly with 2.6.11 in the last days and today suddenly started to behave like that?

If this is the case it sounds more like a server related issue. But we will find it anyway.

**Comment by SqueekyST** [comment]
That's right, installed March 29 or 30. Accessed multiple times daily. But only started losing my login in the last 18 hours.
Mine is frequent, but not every time I switch between apps, so there's no quick test to immediately tell if it's resolved.
As an aside, after the new install, this is the first time it's told me it will be accessing my SD card and the first time avast flagged it as a security risk.

**Comment by kistitan** [comment]
@SqueekyST 

Yes that's right. To make the video and photo upload feature work properly we had to add this permission in order the user to be able to select image/picture from the sd card to upload.
In newer Android versions the user will be prompted to provide the permission only when it is needed, on older Android version unfortunately this should be granted automatically.

**Comment by kistitan** [comment]
Hi all,

Did you face the frequent login issue recently with version 2.6.15?
For different reason but in upcoming version we refactor the session management so any issue with current version might not be related in future version, but still any feedback on 2.6.15 beahviour is welcome.

**Comment by kistitan** [comment]
Issue identified!
Will be fixed in next version!

Thank you for your patience!

**Comment by SqueekyST** [comment]
2.6.15 asked for login info once when first installed, then never again.

**Comment by SqueekyST** [comment]
It's back to asking for login every launch. Still using the same version.

P.S. it would sure be sweet if the about page linked to the latest download page.

**Comment by TipsyInk** [comment]
I'm using the latest version and it was fine for awhile,now its back to askimg me for my login info everytime

**Comment by sockpopstar** [comment]
Same here. I have had to log in any time I opened another app after
minimizing the FetLife app

**Comment by kistitan** [comment]
Hi guys, 
We discovered an issue that make the app asking for password when it is closed fully and not keeping in memory. That can happen anytime as it managed by the OS.
We made an attempt to fix in 2.6.18.

Can you please confirm you use that version and it is still present?

**Comment by SqueekyST** [comment]
I'm on 2.6.15. Is there a link to the version you'd like me to try?

**Comment by kistitan** [comment]
Hi there,

Sure:
https://github.com/fetlife/android/releases/download/v2.6.18/fetlife-2.6.18.apk

Thanks you all for checking our preview versions!

**Comment by wolfxlittlered** [comment]
V2.6.15. Uninstalled app. Re-installed from downloads folder. Seems to have fixed the issue. Will update in a few hours of performance.

**Comment by wolfxlittlered** [comment]
Uninstall and re-install resolves the issue for v2.6.15. Updating to v2.6.18 now.

**Comment by wolfxlittlered** [comment]
@Kistitan v2.6.19 has resolved this issue. Thank you for the time you've put in on this issue.

**Comment by ckuffman** [comment]
I wasn't paying attention to the versions, but I had this problem, it went away for a short bit last month, and then it has reappeared again in the last couple of revisions with gusto. My observations seem to match the time line of other posters, and I generally update within a day or two if the new releases. I am currently on 2.6.26. Going to try reverting to .18 and see if problem persists.
