### ISSUE TITLE
Icons on profile page missing or misaligned

### ISSUE THREAD

**Issue by Grawmpy** [fetlife/android#292]
I have an A464BG Alcatel One Touch Pixi 3, running Android 4.4.2 and a relatively small screen. When I bring up a profile, the icon on the right is only slightly showing at the edge, the "Follow" icon shows "Fo" and below that "llo", and then under that the "w". All the icons direct to the right section except for the one all the way to the right, because I can't really touch it. Maybe if you allowed it to scroll?

**Comment by kistitan** [comment]
Hi @Grawmpy ,

Thank you for letting us know.
This issue has been already reported, so we will definitely figure out something.
We did some small improvements in one of our version, I am not sure if you already have it.

Do you use our latest version?
https://github.com/fetlife/android/releases/download/v2.6.15/fetlife-2.6.15.apk

**Comment by Grawmpy** [comment]
Yes, I get the latest release and the beta when released. My handle at FL
is CottonwoodBiGuy and have accounts at outlook and Google with it. With
this handle, one of my regular, I am trying to get into design at the
Andor's Trail (andorstrail) git, but lack some of the tools at this time.

**Comment by kistitan** [comment]
Hi @Grawmpy 

Can you maybe give us a screenshot about your screen?
Please make sure the profile photo and text is covered for privacy reasons.
Or you can send it privately to krisztian@fetlife.com

Thanks

**Comment by Grawmpy** [comment]
On Apr 6, 2017 3:49 AM, "kistitan" <notifications@github.com> wrote:

Hi @Grawmpy <https://github.com/Grawmpy>

Can you maybe give us a screenshot about your screen?
Please make sure the profile photo and text is covered for privacy reasons.
Or you can send it privately to krisztian@fetlife.com

Thanks

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fetlife/android/issues/292#issuecomment-292137473>, or mute
the thread

**Comment by kistitan** [comment]
Can somebody give a feedback if this is still the case?

Thank you!

**Comment by SqueekyST** [comment]
I see all 4 labels. The view icon is now fully visible with the word "view" word wrapped on 2 lines below.
Aka it looks funny. But it fits and functions.

**Comment by Grawmpy** [comment]
Here is a current shot of v2.11.8. I have a small 3.5" A464BG Alcatel Pixie
3. I hope this helps

On Oct 18, 2017 11:59 PM, "kistitan" <notifications@github.com> wrote:

Can somebody give a feedback if this is still the case?

Thank you!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fetlife/android/issues/292#issuecomment-337817210>, or mute
the thread

**Comment by kistitan** [comment]
Profile page is going to be redesigned and will be webview based.
Probably we not gonna fix this before the new version.

Sorry for the inconveniences
