### ISSUE TITLE
Web Pages Opening in Private Mode

### ISSUE THREAD

**Issue by mnjones612** [fetlife/android#297]
When the program decides to open a Web Browser, it needs to open in Private Tab. My phone is Synced Across multiple devices, which means computers, televisions and other technology items have access to my web history. This is especially noticed when you click on a user's name, it opens a regular FireFox Tab.

This is an item that would be fixed fairly easily, and keep the security of the accounts.

![screenshot_20170408-175942](https://cloud.githubusercontent.com/assets/22207886/24832819/5da4938e-1c86-11e7-83fe-ba13e248ebdb.png)
![screenshot_20170408-175957](https://cloud.githubusercontent.com/assets/22207886/24832820/5dc205e0-1c86-11e7-9a71-bd476b1d3c1c.png)

Another Issue is that the Program Updates even when its closed, the update should not Display an Xrated Image or the Users Name. 
Instead "New FL File Update" Notification.

**Comment by kistitan** [comment]
Hi @mnjones612 

Thank you for your suggestion.
About the browser page, we are working on the App improvement to have all the page part of the App, so we hope this issue will be less and less relevant.
In our current preview version user profiles already open within the App and not in a browser page.

The second issue is not perfectly clear at the moment.
Can you please give us a bit more information what scenario you would like to improve?
Are you referring to the New App version notifications? That should not contain any XRated photo or user name.
Can you please send us a screenshot about that issue too?
For privacy reason for that please feel free to use krisztian@fetlife.com

Thanks a lot

**Comment by kistitan** [comment]
Hi all,

Profile pages are now opened in the App, so I close this issue.
There are a few more outside link opened from the App but we are going to make them less and less.

Thank you
