### ISSUE TITLE
Delete Conversation Threads.

### ISSUE THREAD

**Issue by wolfxlittlered** [fetlife/android#298]
Enhancement. Swipe left or multiple select to delete conversations using the app. Currently only permission is read and send messages.

V2.6.15

**Comment by SqueekyST** [comment]
I really, really wish we had the ability to archive our conversations. I hate having penis avatars in my chat list.

**Comment by kistitan** [comment]
@SqueekyST 

I do understand.
Does this mean that archiving it via the website does not work for you either?
Or you just wish it was more convenient via the app

**Comment by SqueekyST** [comment]
It does work from the website. But since I do all my messaging from the app, it would be much better having it there.

**Comment by Germanbight** [comment]
Archiving works on the Web site though doesn't always copy on the mobile app. I'm currently showing considerably more mobile messages than are live on my Web profile.

**Comment by RedKitten13** [comment]
I also wish there was a way to either archive and/or delete PMs (private messages) within the app, because the only way I see how to do it as of right now is to **completely** uninstall the app and then **reinstall** it  - which, in turn, **completely** resets the settings you have, well, **set** within the app, so.

**Comment by TNBelle82** [comment]
Not quite so complicated. If you have deleted via web version, there is an option in settings to delete local user data. I don't know what else it effects, though it does delete conversations that have been deleted online. It will log you out, though, and you will have to re-enter username and password.

**Comment by kistitan** [comment]
Conversations screen will be fully replaced by a Webview based screen so all the website features like dele will be available.
Closing this for now
