### ISSUE TITLE
Notifications always vibrate

### ISSUE THREAD

**Issue by Darkhub** [fetlife/android#299]
Notifications always activate vibration, even if device is set to audio only.
Can you just add a vibration on/off selection box or disable it completely while waiting to add the option?
Thanks.

**Comment by kistitan** [comment]
Hi @Darkhub 

Sorry for the late answer.
FetLife App by default uses the default notification and vibration settings of your device.
As many App uses it's own settings for notifications sometimes it is not obvious what are the default settings. 
To check and set your default notifications settings and how to put your device in vibrate mode please follow the following guideline:

https://support.google.com/pixelphone/answer/2819577#notification_settings

Please let us know if it helped to reach the desired state.

**Comment by Darkhub** [comment]
Thanks for reply, I know how to set the various notification options on my devices, the problem is relative to this particular app instead.
All other apps respect sound/notification mode activated on device but this one in any case triggers the vibration, even if it's disabled.
Only when in 'do not disturb' mode there's only the notification led activated but that's an extreme case.
So it would be nice to select if activate or not the vibration and, now that I named it, maybe also the color of notification light.

**Comment by kistitan** [comment]
Hi all,

FetLife App offers setting for vibration in the latest version.
Thank you for your patience.

**Comment by Darkhub** [comment]
Thanks, much better now! :)
