### ISSUE TITLE
App keeps logging me out. 

### ISSUE THREAD

**Issue by MaxiM-PL** [fetlife/android#300]
Despite the option to "remember me" being selected, every time I launch the app I have to log back in. Wasn't a problem for months since I've started actively using the app.

**Comment by wolfxlittlered** [comment]
What version? There is an open issue with this already titled "Frequent Logins" with a link in the comments to download preview v2.6.18.

**Comment by Willow-Rose** [comment]
It's happening to me too. I have version v2.6.15

**Comment by MaxiM-PL** [comment]
Whoops, sorry. I was never notified about the latest version so I was on 2.6.15 as well. At least for the moment problem seems to be gone on .19

**Comment by wolfxlittlered** [comment]
If you wish to continue using 15 uninstall then reinstall from downloads. Resolves the issue temporarily. I suggest updating to the most recent version if possible.

**Comment by Willow-Rose** [comment]
Where can the latest version be found?

**Comment by MaxiM-PL** [comment]
@Willow-Rose https://github.com/fetlife/android/releases

**Comment by kistitan** [comment]
Hi guys,

Can you please confirm that 2.6.19 solved this issue?

Thank you!

**Comment by Willow-Rose** [comment]
It solved the issue for me

**Comment by MaxiM-PL** [comment]
For sure. So far I haven't been logged out once.
