### ISSUE TITLE
Status updates.

### ISSUE THREAD

**Issue by wolfxlittlered** [fetlife/android#301]
Enhancement. Text bar at the top of the feed screen with incorporated buttons for "Status update", "Photo upload", and "Video upload". Current v2.6.19.

**Comment by kistitan** [comment]
Hi @wolfxlittlered,

Thank you for your feedback.
Enhancing Feed screen in the App is on our mid-term list and this feature seems to be one that should be part of it.

Thank you!

**Comment by kistitan** [comment]
Merging into https://github.com/fetlife/android/issues/171
