### ISSUE TITLE
Latest version of app?

### ISSUE THREAD

**Issue by xeroace** [fetlife/android#302]
I'm currently on 2.6.15 and looking on here I see there are later versions. Is there a link to the latest version of the app?

**Comment by johnbaku** [comment]
@xeroace good question... @kistitan will correct me if I am wrong but all the latest versions can be found here: https://github.com/fetlife/android/releases

**Comment by kistitan** [comment]
Yes @johnbaku thank you, this is correct!

You should get notification about every new releases, but I have just started to work on "check for updates" menu item so even if you miss it you can always get link to the latest one from the App itself.

**Comment by xeroace** [comment]
Thank you both!
