### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Jem3001** [fetlife/android#305]
The install on my phone gives an error and it won't let me install. I have unknown sources checked. It downloads the file but will not let me install it on my phone.

**Comment by navyguyg** [comment]
If your using Chrome it won't let you install from the browser. You have to us the My File or a file Explorer to install it.

**Comment by kistitan** [comment]
Hi @Jem3001 ,

Can you please check @navyguyg 's answer?
Indeed new versions of chrome does not start install of apk files.

Please let u know if it works for you.

Thanks

**Comment by Jem3001** [comment]
This has worked for me. I was using chrome on my device and I changed browsers and it installed straight away. 

Thanks.
