### ISSUE TITLE
Duplicate feed activity.

### ISSUE THREAD

**Issue by wolfxlittlered** [fetlife/android#306]
Bug. Low priority. V2.6.22. Activity feed duplicates final story upon loading next page. {Hit rock bottom when scrolling. After app loads next set, scroll down. First story on next page is the same as the final story on the previous page.} *Randomly and unintentionally replicated issue 3 times in this version. **Multiple replications on previous versions.

**Comment by kistitan** [comment]
@wolfxlittlered 

Thank you for reporting this issue.
We are going to investigate.

**Comment by wolfxlittlered** [comment]
V2.7.0 Replicated on first boot. 3rd Page down. 1st story on 3rd page same as last story on 2nd page.

**Comment by wolfxlittlered** [comment]
Duplicated. V2.8.1 May be a connectivity issue.

**Comment by doglitbug** [comment]
I've seen a similar issue before, could it be due to another item being added to the top of the news feed between loading of first page and loading of second("pushing" down items and overflowing the page)?

**Comment by kistitan** [comment]
Feed and explore section are going to be webview based screens.
When it happens this issue will be auotmatically solved.
We won't fix this before, to avoid duplicate effort on the same issue.
Thank you for your understandings.
