### ISSUE TITLE
Inaudible Notifications

### ISSUE THREAD

**Issue by MaxiM-PL** [fetlife/android#307]
Ever since I started using FL on my Samsung Galaxy S4 i9505 the notifications were inaudible, only vibrating. I thought it's intentional (posted a feature request long time ago) but now that I've installed the app on my LG G Tab 8 tablet I'm actually getting notifications with the default sound. 

I'm running Android 7.1.2 on my phone, but the same thing was happening on 5.1.2 and 6.0. App has all the notifications turned on in system settings (even gave it highest possible priority in the system).

**Comment by kistitan** [comment]
Hi @MaxiM-PL ,

Thank you for the info. It is very useful.
Actually our App does not give any notification setting to the Android OS when we display notifications and that means the device's default settings should be used.

However we received several user complain that some of the devices do not handle this properly so we plan to add additional notification settings in one of the upcoming two feature release. 

Thanks again!

**Comment by MaxiM-PL** [comment]
@kistitan Simple option to choose a custom sound from the phone would be amazing. I've got a whip crack sound waiting exclusively for that function ;)

**Comment by kistitan** [comment]
Hi @MaxiM-PL 

Improvements in Notification Settings have been releases in our latest version.

Thank you for your suggestion
