### ISSUE TITLE
Disable picture and writing loves

### ISSUE THREAD

**Issue by restrainedimages** [fetlife/android#309]
I need to disable notifications for likes on pictures I post as otherwise I get too many notifications. I suspect people who write may have a similar problem. However I would like to keep other notifications especially for comments. However I can also see someone wanting to disable notifications for comments too, especially if there are suddenly lots.

It's not clear which of the notification opens I need to disable. It's also not clear what other notifications I will lose as a result.

So...
URGENT - Can we list all the different types of notification and which switch currently enables / disables them.
IMPROVEMENT - Then can we redesign the options to maximize control while keeping it user friendly.

It may also be useful to have a single set of notification controls with the ability to turn on/off the different types of notification all from one place. (Email / App / ???) That would allow someone to decide in one place how to handle the different notifications.

**Comment by kistitan** [comment]
Hi @restrainedimages 

Thank your for your suggestion.
Settings improvements have been release in our latest version.
