### ISSUE TITLE
About screen - version history is incomplete

### ISSUE THREAD

**Issue by restrainedimages** [fetlife/android#310]
Version v2.7.14
The about screen correctly lists the version number but the version history doesn't include any changes since 2.7.0

I think this may be a process issue where the changes about being captured / updated as new versions are released.

**Comment by IRDeNial** [comment]
Well, version history strings are found here...
https://github.com/fetlife/android/blob/master/FetLife/fetlife/src/main/res/values/strings.xml

So, they just have to update the information in strings.xml for that to update.

No issues here.

**Comment by kistitan** [comment]
@restrainedimages 

Thank you for your feedback.
Usually we pay more attention to it before we make a release up to date.
Also we do not add every fix as it usually effects only on subset of the users, that is why only feature releases are mentioned.

Version code by default looks like this:

[major release].[feature release].[bug fix release]

But indeed it makes sense to keep it up-to-date even for interim releases.

It will be updated as soon as next version become a stable release.
Thank you!
