### ISSUE TITLE
Auto Logout.

### ISSUE THREAD

**Issue by wolfxlittlered** [fetlife/android#314]
V2.8.1. App logged me out again. Clearing cache and app data fixed issue for now. Replicated 3 times before clearing.

**Comment by kistitan** [comment]
@wolfxlittlered,

Thanks you for reporting this issue.
Did it appear since?

**Comment by wolfxlittlered** [comment]
Not yet. But will comment as soon as I duplicate.

**Comment by TheGingerPDX** [comment]
Mine keeps logging itself off too. Did the steps the other fellow did, but makes no difference. Even if I just logged back in 20 minutes ago. And the remember me check doesn't work. It forgets me, so i have to not only enter the password, but the email too. Why? Can't I be allowed to determine my own security procedures? My phone is locked, and my fetlife account has fewer naughty pics of me than my phone has. What gives?

**Comment by kistitan** [comment]
@TheGingerPDX 
Except some rare occasionally password enforcement you definetly should be able to stay logged in.
If the remember me checkbox does not work, that is definitely a bug.

May I ask you if you are at the latest version?
Does it help if you use the menu option / Settings / Profile Settings / Clear local User Data?

If you were not can you please also update to the latest version?

Thank you

**Comment by kistitan** [comment]
Hi all,

Issue has been found.

If your profile is downloaded (opening your own profile screen, or browsing a friend's friend list where your profile is also represented) logon information get cleared so next time you have to login again.

Will be fixed in next version.

Thank you for your patience and understandings.

**Comment by kistitan** [comment]
Fix has been released.
