### ISSUE TITLE
Does the API support retrieving all friends at once?

### ISSUE THREAD

**Issue by iLukey** [fetlife/android#317]
Hi, 

Just wondering if the API supports way of retrieving all friends in a single call or not please? If not is it likely to be added? 

Some users have got a very high number of friends (35,000 is the highest I've seen) so multiple calls will hammer the API, though returning 35,000 records may also be too much? 

Thanks,
Luke

**Comment by kistitan** [comment]
Hi @iLukey 

I am really sorry for the delay in answer.
I started to type you the reply earlier but apparently it did not go through :(

Unfortunately current API has pagination feature with maximum 50 members per request.
It is indeed not very handy for requesting all the 35.000 people, but also the use case is unlikely that somebody would like to browse through all the 35.000 friends at once.

To support better this situation we recently added search functionality to our member page so all members (so including your friends) can be searched by username or part of the username.

If you had any idea for further improvements feel free to let us know.

**Comment by iLukey** [comment]
Hey @kistitan, 

No worries at all :) 

Yeah, honestly I didn't realise people would have such a vast number of friends, and returning that much data is pretty impractical to retrieve and for me to process. 

What I'm trying to do is figure out whether a given person is my friend or not, so that I can provide relevant options to the user. 

One thing that's been tricky though is that the profile retrieval API method uses a user ID that's not presented anywhere on a typical Fetlife page, so I'm having to do two requests - the first is a search using their username, which seems to always return exact matches first (so searching for JohnBaku would return the user with JohnBaku first, then JohnBakuuuu etc), then take the first result from that search, grab the user ID, and use that to retrieve profile details for them (to work out if we're friends or not). 

I couldn't figure out exactly how the search query string should be formatted, but doing ?query=$username seems to work fine :) 

I guess it'd be good it it were extended to be a POST request that takes documented key/value pairs instead, so you could search on a specific thing (id=blah, username=JohnBaku etc.)

**Comment by kistitan** [comment]
Hey there,

Members in the meanwhile has attribute:
relation_with_me

This will tell if the user is a friend or no.

I hope it helps!
