### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by hburbage88** [fetlife/android#318]
The app logo says i have 7 notifications but when i go into the app the notifications are not loading. I have uninstalled and reinstalled but not sure  else to try.

**Comment by hburbage88** [comment]
How do i clear the cache?

**Comment by kistitan** [comment]
Hi @hburbage88 ,

Sorry for the late reply.
May I ask if you use anonym notifications or normal ones?
Notifications include messages, friends requests, and other notifications.
Messages and friend requests are not presented in the notification screen.

For clearing app cache you can go your device's Settings > Apps > FetLife App > Storage > Clear Data or Clear Cache.

**Comment by kistitan** [comment]
Hopefully clearing data solved the issue.
Closing for now
