### ISSUE TITLE
Relationship Status

### ISSUE THREAD

**Issue by Sparkiechu** [fetlife/android#320]
I have changed my relationship status with a few people since I have downloaded the app. These changes have appeared on the main website but not inside the application. Is this a bug? I don't want it to be showing me in a relationship with someone that I am not.

**Comment by kistitan** [comment]
Hi @Sparkiechu,

You should see the changes in the App soon after the changes when you open your profile again with working Internet connection and wait until the progress indication disappears 
Can you please send me your profile name to 
dreamlite@fetlife.com?

**Comment by LexiRyedale** [comment]
I am seeing this on my profile too.

**Comment by kistitan** [comment]
Hi @LexiRyedale , @Sparkiechu 

Thank you for reporting this issue.
We found a bug in the App caching mechanism that we are going to fix in the next version.

FYI I checked both of your profile and as of now there is no difference in your relationship status in the App and on the website.

Thank you for your patience.

**Comment by kistitan** [comment]
Fix has been released
