### ISSUE TITLE
@mentions are being hijacked by the app

### ISSUE THREAD

**Issue by MaxiM-PL** [fetlife/android#327]
Way back when I was reporting that some notifications show up on the phone, but they're not mirrored on the website. At the time I thought it was random, but now I'm 100% it's just @mentions. Whenever somebody mentions me in a comment or photo caption, my Android app sure gets the notifications, but when I go to https://fetlife.com/ats, same mentions are nowhere to be seen. For lack of a better word, the app is completely hijacking them, making going back to them later on PC pretty much impossible, unless you remember where you were mentioned and you navigate there yourself.

**Comment by kistitan** [comment]
@MaxiM-PL 

Thank you for reporting this.
Let me check with the website team what is the policy for displaying notifications in the notification history.

**Comment by kistitan** [comment]
Hi @MaxiM-PL ,

Sorry for getting back to you late.
We have discussed internally and actually it is not the App that hijacks the mention notifications.
Some notification types (like mentions are not supported in the notification history view of the website). You can however see them in the App.
What you can also do is to turn on email notifications and set any email notifications read automatically in your email app so you won't be bodhered by them but you can still recover them if needed.
We know it is far from ideal and we are sorry for your inconveniences. Current notification handling both in the App and at the website lacks some refactoring that we should do sooner than later.
As soon as we get there we will open a broader issue about it.

Thank you for your understandings

**Comment by MaxiM-PL** [comment]
Ah, that explains it I guess. Thanks for the info.
