### ISSUE TITLE
Android web link formatting bug

### ISSUE THREAD

**Issue by SufferingForArt** [fetlife/android#328]
I've just sent someone a message containing a website link using the normal formatting rules using text within square brackets followed by the URL inside adjacent round brackets. In the case of the Fetlife standard website the link is shown correctly as underlined text, whereas in the Android app the linked website address is shown in full in yellow text. So clearly the coding doesn't yet support linking in this way.

**Comment by kistitan** [comment]
Hi @SufferingForArt.

Thank you for reporting this issue.
Unfortunately this is nit a bug but works as designed.
We had a long conversation about this also here at GitHub so we understand it is uncomfortable, however we plan to move rather to an Instant Messaging experience than a formatting message solution also at the website, it would not make much sense to implement the formatting at the android than removing it later.

Sorry for your inconveniences and thanks for your understandings.

**Comment by SufferingForArt** [comment]
Thank you. I raised it in case it was something you weren't aware of, rather than it being an inconvenience. However, your future messenger developments sound really cool :-)
