### ISSUE TITLE
How does  FeedRecyclerAdapter.loadItems() load Stories

### ISSUE THREAD

**Issue by erikswed** [fetlife/android#331]
Going through the source code Thanks grate stuff. 
Wanted to ask a question about the below FeedRecyclerAdapter.java method `loadItems()` and specifically the  `getFeed()`(below in code), thats gets a general feed and when user is signed in the `getProfileFeed()` returns user feed. But my question is does the `getProfileFeed()` include the data that `getFeed()` returns? 
```
    private void loadItems() {
        //TODO: think of moving to separate thread with specific DB executor
        if (memberId != null) {
            itemList = fetLifeApplication.getInMemoryStorage().getProfileFeed();
        } else {
            itemList = fetLifeApplication.getInMemoryStorage().getFeed();
        }
    }
```

**Comment by reneklacan** [comment]
@erikswed Result of `getProfileFeed()` doesn't include the same data as the result of `getFeed()` but they have the very same format/type which is `List<Story>`.

`memberId` in this case is only defined in member's profile view when you are browsing their latest activity. And `memberId` is `null` in the personal activity feed view.

**Comment by kistitan** [comment]
@reneklacan well said, thank you

**Comment by erikswed** [comment]
thanks grate
