### ISSUE TITLE
Feature Request: GPS

### ISSUE THREAD

**Issue by EugeneF2017** [fetlife/android#332]
Ability to see nearby members based on GPS location

**Comment by ironjan** [comment]
IMHO a feature like this may be interesting, however it *must* be opt-in only. Also, this is not an app-only change; most likely the API would need to be adapted.

It may also be that this doesn't reflect the spirit of FetLife. There are multiple threads on the suggestion area about "dating site/app"-features which are discussed controversially.

---

A similar feature to this suggestion called hangout is part of the couchsurfing app/site. Per default, it is turned off. If you choose to "hangout", your rough location gets shared with other people near you. You can only see the distance to other "hangout" people. you don't need to be friends, butt both need to have hangout turned on.

**Comment by kistitan** [comment]
Hi @EugeneF2017,

It would be indeed a very nice feature for several users, however we should be careful as some users might think differently about this.
And as @ironjan said if we start supporting this the support would first go for the website.
As soon as it happen we will reopen this issue and implement in the App too.

Thank you for your understandings
