### ISSUE TITLE
Location State

### ISSUE THREAD

**Issue by cpowell1687** [fetlife/android#334]
Not sure if there is an official feature suggestion location or of this is the appropriate place. But I've found it very confusing and lacking basic information on the profiles only seeing the city and not the state. Whether it be browsing new contacts and not knowing if they are even nearby based on city alone. Or speaking with intermittent acquaintances we often check location for a quick reference. I think it would be a beneficial addition to add the state in the profile viewable location data.

As a somewhat related but secondary issue, browsing places is notably missing from the app and I wonder if this is coming or going to be added?

**Comment by kistitan** [comment]
Hi @cpowell1687 ,

Really sorry for the late reply.
Good finding.
We are going to add the Administrative area in the next version of the App.

Unfortunately I cannot confirm if we are going to add places in the near future.
Or main todo list contain Groups as the firs big items and after we will do a moderate refactor in our App code to reduce maintenance. 
All other comes only after this.

Thank you for your understandings.

**Comment by kistitan** [comment]
Improvement has been released.
