### ISSUE TITLE
Fetlife icon is not conform android 7 guidelines

### ISSUE THREAD

**Issue by KremerH** [fetlife/android#336]
After installation of fetlife app 2.9.11 on an android phone that is recently upgraded to Android 7.0 the app icon gets a grey border (as well as any other app that was installed under Android 6.

**Comment by malachid** [comment]
Actually, Android 8 was released yesterday and has new guidelines for adaptive icons.

**Comment by kistitan** [comment]
Hi @KremerH,

If you are using a Samsung device for example, than you can remove icon frames going through these settings:
http://techindroid.com/remove-icon-frames-galaxy-s8-s8-plus/

And indeed as @malachid said there are new icon guidelines and we plan to adapt our icons soon.

**Comment by kistitan** [comment]
It should be now :)

Closing...
