### ISSUE TITLE
I really love the app if we could run it off SD card 

### ISSUE THREAD

**Issue by jaredsay1974** [fetlife/android#337]
I only have 8g onboard but I have 128g SD card SD so right now I really can't run fetlife app  till someone can make it like Facebook run off SD card

**Comment by kistitan** [comment]
Hi @jaredsay1974 ,

Thank you for reporting this issue.
We will add this support in the next version.

**Comment by jaredsay1974** [comment]
Thank I hope it comes out soon

**Comment by kistitan** [comment]
@jaredsay1974 

Probably this week.
Thank you for your patience.

**Comment by kistitan** [comment]
Hi there,

Latest version should work like that.
Please reopen this issue if you still face some issue according to this:

https://github.com/fetlife/android/releases/tag/v2.11.8
