### ISSUE TITLE
REQUEST, Jump to pictures shortcut.

### ISSUE THREAD

**Issue by qwksilver** [fetlife/android#339]
On a profile page, tapping the center profile thumbnail does nothing.  Can you cause it to advance the lower section to pictures.  This shortcut will eliminate about 4 swipes and data base calls for all the items we don't need at this time.  

I personally would find this feature very useful when trying to figure out if I know somebody before accepting a friend request.

**Comment by kistitan** [comment]
Hi @qwksilver,

I think it is a very nice idea. 
Indeed many users would like to browse the picture as a first step and indeed can save swipes and also some backend calls.
I am going to add this to out todo list.

Thank you

**Comment by kistitan** [comment]
It should work as requested in the latest preview version.
Closing this issue now.
