### ISSUE TITLE
Silent notification does not work

### ISSUE THREAD

**Issue by DucoServitium** [fetlife/android#341]
I have notifications for the app turned on, and the notification sound within the app set to Silent, yet whenever I receive a notification, the default notification sound for my phone plays.

Not sure if this is a limitation on my phone, or the app.

I would really like to keep my notifications turned on but silent.

**Comment by kistitan** [comment]
@DucoServitium 

I am really sorry for the delayed answer.
We are at the moment busy with the mandatory security update.
We are going to look into this after it is done.

Thank you for your understandings

**Comment by nielsenramon** [comment]
You can fix this by setting the ringtone to 'None' in the Media Storage.
