### ISSUE TITLE
Video playing intent

### ISSUE THREAD

**Issue by JapanYoshi** [fetlife/android#342]
What intent does the app send out when trying to play a video? It looks like it's different from the intent that file manager sends when playing a local file.
From local: ![screenshot_20170907-015842](https://user-images.githubusercontent.com/8707990/30121940-575173e2-9370-11e7-827e-818adac0ed9c.png)
Intercepted intent: ![screenshot_20170907-015859](https://user-images.githubusercontent.com/8707990/30121938-57317cae-9370-11e7-9fc1-9163a2a94dbe.png)
From FetLife:

**Comment by kistitan** [comment]
Hi @JapanYoshi ,

Thank you for letting us know about this issue.
We use the following code to send out the video intent:

`               Intent intent = new Intent(Intent.ACTION_VIEW, uri);
                intent.setDataAndType(uri, "video/*");
                holder.imageView.getContext().startActivity(intent);`

To be honest I don't see the point why the other player do not appear as a suggested player.
Can you give an App name that is not offered as a choice by FetLife but it is offered from your file browser, so we can play around with?

Thank you!

**Comment by JapanYoshi** [comment]
Hi, @kistitan,

I am trying to send the intent into [Photo Editor](https://play.google.com/store/apps/details?id=com.iudesk.android.photo.editor), [Intent Analyzer](https://play.google.com/store/apps/details?id=com.apartapps.android.intentanalyser), or [Intent Intercept](https://f-droid.org/packages/uk.co.ashtonbrsc.android.intentintercept/). I'm not sure if it's an issue with those programs, or if it's a problem with FetLife, but either way, only the native video player and VLC pop up on FetLife, and not the three others.

**Comment by kistitan** [comment]
After keeping this open for a while and checked it the times we can confirm we open the videos with content type video/*, so the OS should show all Apps that are intended to play videos.

Aside that we could address the most popular video players directly, but that would cause coupling between specific version, what could cause issues in the future.

We are sorry we could not help, but we do not see any more we can do at our side at the moment.
