### ISSUE TITLE
Server could not be reached

### ISSUE THREAD

**Issue by Nermandia** [fetlife/android#343]
Hi

Every time I try to log in it show me this message that says: "SERVER COULD NOT BE REACHED. PLEASE CHECK YOUR INTERNET CONNECTION". I have tried different WiFi's and mobile network, this is happening since yesterday, not sure what it is.
![screenshot_20170907-112542](https://user-images.githubusercontent.com/31739708/30174165-c00a8faa-93bf-11e7-925e-2bcba2fc884e.jpg)

**Comment by wolfxlittlered** [comment]
Same issue with no found work around.

**Comment by kistitan** [comment]
All App instances facing the same issue.
We are working on it.
New version will be released in few hours.
Sorry for the inconveniences.

**Comment by kistitan** [comment]
Hi all,

Issues has been fixed now, but please keep in mind you should update to latest version (2.10.0 or up) before 11th of September 2017 or the App will stop working.

Thank you for your understandings.

**Comment by Coneyisland39** [comment]
Still having the same issue with 2.10.0
