### ISSUE TITLE
Mandatory 2.10.0 not working

### ISSUE THREAD

**Issue by TyD59** [fetlife/android#345]
I've updated often & currently running beta v2.9.11 . It won't update this time. Even pasting the URL https://github.com/fetlife/android/releases/download/v2.10.0/fetlife-2.10.0.apk directly into the stock Chrome Android browser on this Samsung S7 Edge doesn't do it as usual. 

I received two different files, same name (the second w/a (1) on it). They had different file sizes... 

The last filename was fetlife-2.10.0 (2).apk.crdownload & 510kB.
The download before that was fetlife-2.10.0 (1).apk , 0kB.

WTF?

Thanx,
TyD

Where can I get a reliable download for this mandatory update?

**Comment by ironjan** [comment]
The different names are the result of previous file downloads of this APK. The different are likely to be caused by an instable internet connection, i.e. the download failed before the download completed (file 1) or before it even started.

Could you try again with WiFi?

**Comment by kistitan** [comment]
Hi @TyD59,

Indeed @ironjan seems to be right.
.crdownload is usually a temporary file expressing it is being downloaded.
I can confirm that the location is a stable, trustable location.
Can you maybe try it indeed with WiFi connection?

Thank you!

**Comment by TyD59** [comment]
Thanx for the quick & informative replies. I'm on satellite internet most of the time. When the premium bandwidth runs out we're throttled down to 1Mb/s. It is sometimes unstable too. I was able to download & install the new version today, early in the morning while throttled bandwidth is better.
Best Regards & thanx!
