### ISSUE TITLE
Why does the website have more features?

### ISSUE THREAD

**Issue by raggeddoll9302** [fetlife/android#346]
Wondering why the app doesn't have all the features that the website had? I get on fet on my phone and it kills my battery to jump from the app to the browser constantly.

**Comment by kistitan** [comment]
Hi @raggeddoll9302 ,

The Android App started much later than the website and it takes time to catch up especially as there are also new features on the website.
On the other hand you are perfectly right and we are just changing track from optimizing features for Android towards to have a full features App.
We are going to add several WebView based pages in the near future to cover more and more features of the website.
