### ISSUE TITLE
Status update in app

### ISSUE THREAD

**Issue by skul6663** [fetlife/android#348]
I didn't see anything about this so thought to suggest. It would be nice to be able to change status in the app

**Comment by kistitan** [comment]
Sorry, just noticed I only added the labels, but did not say thank you for your suggestion.
It is a good one, but added to our todo list.

**Comment by kistitan** [comment]
We are right now working on the make the App feature full to have all the screens form the wwbsite in webviews, as soon as we get there this issue will be automatically solved.
As have separate issue tracker for that progress I close this for now.

Thank you for your understandings.
