### ISSUE TITLE
New update download not launching

### ISSUE THREAD

**Issue by SqueekyST** [fetlife/android#349]
My notification bar indicates there's a prerelease available, but when I click it, it launches my browser and attempts to go to a github address, then reverts to whatever my browser had open last. The notification is not clearing when I do this.
I've tried:
- opening a new blank tab in my browser first
- launching with my browser open
- launching with FL open
- requesting an update from the app (it tells me there is one, but nothing else)
- trying to copy/paste the destination from the address bar, but it's too fast.

**Comment by ironjan** [comment]
Can you try if you're able to download the newest version from https://github.com/fetlife/android/releases/tag/v2.10.3 (APK link)? If this link does not work it may indicate that your phone or browser prevents the download.

Which phone/browser/Android version are you using?

**Comment by SqueekyST** [comment]
Thanks for the reply. I managed to solve this but hadn't posted yet.
I disabled the default browser so it would prompt me to choose the native browser. That worked on the first try.

**Comment by ironjan** [comment]
Great to here. Is "close issue" enabled for you? If a it'd be great if you do so ;)
