### ISSUE TITLE
Receiving notifications but not seeing @'s in the app

### ISSUE THREAD

**Issue by DDeity** [fetlife/android#350]
I am getting a notification that someone has liked/followed me in my tablet's notification tray, but when I open the app, the notification section is completely empty. I have the most updated version of Android and the FetLife app.

**Comment by kistitan** [comment]
Hi @DDeity,

Liked, followed notifications should be indeed visible in the Notifications screen.
Messages, Friend Request notifications on the other hand will be displayed in their own screens.

Which Android version does your table use?

**Comment by DDeity** [comment]
I'm using Android 8.0.0

Deity

**Comment by Bbybutterfly** [comment]
Android 7.0.0 no issues with last update but this one keeps sending me notifications to messages I've already read and/or responded to

**Comment by kistitan** [comment]
Merging this issue to:

https://github.com/fetlife/android/issues/363
