### ISSUE TITLE
Tapping Profile picture in Member Profile does nothing

### ISSUE THREAD

**Issue by DerangedMind** [fetlife/android#351]
When on a member's profile, I impulsively tapped their profile picture to view their profile, but it did nothing. I realized that I had to swipe a few times to the right to get to the images. When looking over someone's shoulder as they were using the app, I noticed the same impulse.

It's anecdotal, but tapping the profile picture to access a member's images seems like it would be a positive change. :-)

**Comment by kistitan** [comment]
Hi @DerangedMind ,

We already have this feature request :)
I will add it soon.

Thanks for the suggestion.

**Comment by kistitan** [comment]
This feature is added in the latest preview release.
So closing now :)
