### ISSUE TITLE
Notifications.

### ISSUE THREAD

**Issue by Lilchik2086** [fetlife/android#352]
I downloaded the latest update v2.10.3.  Ever since then, I have received no notifications even though when I go to the app it shows a ton of people loved on my stuff or even commented. before this update I wasn't getting a notification on the lock screen unless there were a bunch of different notifications.   As if it was trying to protect my privacy, but I checked all the settings to not be set on vanilla.

**Comment by kistitan** [comment]
Hi @Lilchik2086

Really sorry for the delayed answer.
I typed first reply right after your message but apparently I didn't send it.
Sorry for that.
We didn't find any reason for not receiving notifications yet. Notifications can be turned off one by one in the All settings but I assume they all turned on right?

Are you on Android Oreo already?
Do you don't get them at all or they only not visible on the lock screen or your notifications screen.

Thank you

**Comment by kistitan** [comment]
Closing this for now as we have no new information and there is another open ticket about investigating notification issues.

Thank you
