### ISSUE TITLE
Dreamlite@fetlife.com Email

### ISSUE THREAD

**Issue by DinahJochebed** [fetlife/android#353]
This Email is Sending Error Messages to my Email Account when it's in the System noted as being a contact for Fetlife.com

**Comment by reneklacan** [comment]
@DinahJochebed Sorry, looks like it never existed, created an alias to make sure @kistitan will receive all emails from dreamlite@fetlife.com

Thank you for reporting this.

**Comment by DinahJochebed** [comment]
Dear Ms. René Klačan,
Good Evening, I hope that you're having a goos day today. I just received
this email tonight even though it is backdated several days. Is there any
way to resolve the issue with Kistitan? He seemed to have been monitoring
all of my communications through Fetlife for the past 2 and half years
almost 3 years now now on Fetlife.com through the GitHub website and
monitoring my telecommunications through other venues as well through
Beaverton Nike Campus and through other friends. There is a lot of
depression and anxiety about having Kistitan monitoring my
telecommunications that many people keep passing judgment on me and my
depression and my best friend, Spirit_Master. I have no idea how to put a
restraining order against certain people when people keep passing judgment
on everything about my disabilities. I don't want to put a restraining
order against anyone but it causes me a lot of difficulties in trying to
communicate with people in my life about my depression. I hope that you're
having a good night.

Best Regards and Blessings,

Krystal Pudelski
503-298-6504 (WI-FI Only)
Dinah.Jochebed@gmail.com

On Oct 2, 2017 6:37 PM, "René Klačan" <notifications@github.com> wrote:

Closed #353 <https://github.com/fetlife/android/issues/353>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fetlife/android/issues/353#event-1275151663>, or mute
the thread

**Comment by FernandoMiguel** [comment]
@DinahJochebed this is not the proper place to have this discussion, given it's a public forum.
please delete your message to protect your identity.

**Comment by johnbaku** [comment]
@FernandoMiguel good observation... I deleted the comment.
