### ISSUE TITLE
Groups: View button crashes the app, sort is by original post date, not last comment.

### ISSUE THREAD

**Issue by threetwoonezero** [fetlife/android#355]
I'm not sure what the view button is supposed to do, but it just crashes the app for me.  Discussions are not sorted as they are on the website either (is by post date, not last comment date).

Version is 2.11.0, on Android 6.0.1 (Galaxy Tab A 8.0)

**Comment by Two-Finger** [comment]
It doesn't crash on my Android 4.4.4, but always opens the Discussions tab in the browser, even if I'm on Description or Rules tab in the app.

**Comment by kistitan** [comment]
Hi there,

The crashing issue should be solved now.
The other two are indeed missing features, that we are trying to find a solution.
As there are already open issue for those, I am closing this for now.

Thank you!
