### ISSUE TITLE
In FEED, tapping icon opens wrong page

### ISSUE THREAD

**Issue by SirDom72** [fetlife/android#357]
In FEED, when tapping on the line below your friend's name, your friend's profile opens. 

i.e. A friend has a new connection. It shows up in the FEED. The line below there is an indication of the person he/she is now connected to. Clicking on this line opens the rfiend's profile. Not the new connection of the friend.

**Comment by SirDom72** [comment]
This bug was introduced in 2.11.0

**Comment by steeljm1** [comment]
Confirmed this bug on Samsung Galaxy J5. Introduced in 2.11.0

**Comment by kistitan** [comment]
Hi @SirDom72 and @steeljm1 

Thank you for letting us know.
We are on it!

**Comment by SirDom72** [comment]
Working fine in the new release!! 

Excellent!
