### ISSUE TITLE
Group - tap "view" - app stops responding 

### ISSUE THREAD

**Issue by steeljm1** [fetlife/android#359]
When tapping the "view" icon on the top of any group tab the app freezes/stops responding, presents error dialog box. After tapping "ok" you are redirected to your group list page.

**Comment by steeljm1** [comment]
Bug already logged.

**Comment by steeljm1** [comment]
Re-opened as logged bug results in different redirection after crash.

**Comment by kistitan** [comment]
Hi all,

Issues should be solved now, with the latest release.
Please reopen this issue if it was not the case.

Thank you
