### ISSUE TITLE
Group notification

### ISSUE THREAD

**Issue by Custheyder** [fetlife/android#362]
Clicking the group notification takes you to the group page with no indication of which group the comment was in. I think it would be better to take you to the end of the relevant topic within the group.

**Comment by FernandoMiguel** [comment]
i agree
at least before it would send you to the site to the right thread/comment 
now is totally useless :(

**Comment by kistitan** [comment]
Hi there,

Yes, we know about this limitation. We added also to the announcements.
We are working on it.

Thank you for your patience.

**Comment by kistitan** [comment]
This should be fixed now.

Feel free to reopen if it was not the case
