### ISSUE TITLE
Delayed messages

### ISSUE THREAD

**Issue by MuckleShiny** [fetlife/android#364]
Just updated the app. Since then, message notifications are coming through up to 40 mins after a message has been sent from the other party.

**Comment by MuckleShiny** [comment]
Also, keep getting message notifications when there's no new message.

**Comment by kistitan** [comment]
Hi @MuckleShiny ,

Thank you for reporting this issue,
May I ask if this issue is permanent or only happens sometimes?

Push messages go through several systems and it is hard to track down sometimes where is the delay from, but we are working on a way to narrow it down.

**Comment by raworre** [comment]
Just wanted to pop in and verify that I am also seeing this issue. Seems pretty consistent right now. I will keep an eye through the day.

**Comment by raworre** [comment]
I wonder if this is an issue with the primary FL services. I just noticed that email notifications seem to be lagging as well.

**Comment by MuckleShiny** [comment]
Hi,

It only seems to happen sometimes. Thanks for looking into it.

**Comment by kistitan** [comment]
We can confirm this issue.
Unfortunately it is happening after our recent sever upgrade.
Sometimes in case if too high number of sudden messages, messages queue has to be backed up and several of pending messages will face significant delays.

We are working on it to find a solution for this issue.

In the meanwhile we are asking for your patience.

Thank you

**Comment by kistitan** [comment]
There were several improvements at the website queue so this issue should mostly solved now.
Delays in other system still be possible but they should be reasonable rare.
Please let us know if the issue become again frequent.
