### ISSUE TITLE
Clicking on Received Android notification crashes app

### ISSUE THREAD

**Issue by dsa157** [fetlife/android#366]
1. I have an Android notification for a discussion I am following
2. I select it from the notification list
3. get dialog "Unfortunately, Fetlife has stopped" Close app
4. Open the app and go to app notification list - it is empty

Fetlife 2.11.11
Verizon LGV20
Android 7.0

**Comment by kistitan** [comment]
Hi @dsa157 ,

Thank you for reporting this issue with the preview version.
We have found that crash.
Gonna release a fix most probably tomorrow.

Thank you for your patience.

**Comment by dsa157** [comment]
great! really appreciate the app and your development efforts. happy to help (at least on testing and bug reporting - my coding skills are way too rusty :( )

**Comment by kistitan** [comment]
Hi all,

This issue should be solved in 2.11.13 and also partly in previous version from server side.
Please reopen this issue if it was not the case.

Thank you for your patience
