### ISSUE TITLE
Search by place

### ISSUE THREAD

**Issue by mrdoctor666** [fetlife/android#369]
Really good job!! Btw I can't find any kind of user browsing by place, thanks

**Comment by kistitan** [comment]
Hi @mrdoctor666 ,

Thank you for your kind words and also for opening this issue.
Indeed unfortunately searching for members by place is not possible in the App.
We would like to extend our search options, but we are working on some connecting improvements both at server and client side so it is going to happen somewhat later.

**Comment by SkotSix** [comment]
How about an instant messager. So I can quit sending people to kik

**Comment by kistitan** [comment]
@SkotSix 

Instant messager is part of the Android App.
Or what exactly do you mean?

**Comment by kistitan** [comment]
Closing this for now.
Webview based search screen will be part of the App in short/mid term, so the same search funcionality will be supported in the App as at the website.
