### ISSUE TITLE
LG G4 Smart Phone "server cannot be reached" Connection Issue

### ISSUE THREAD

**Issue by BaneWilliams** [fetlife/android#372]
Hi there,

Please see the message we received from a member:

> I have an LG G4 Smart Phone I have downloaded the Fetlife APP, however when I try to log in, I get "server cannot be reached, polease check your internet connection.", I contacted my Internet provider, and everything is working fine, I contacted LG support, they informed me that I needed to contact you, since it appears that this website cannot be accessed from my device. If you could look into this and get back to me, it would be greatly appreciated...Thanks in advance for your time

I confirmed the following:

- User has no problem using the website through a browser
- User has the issue regardless of on wifi or on cellular
- When accessing through browser, this is there signature: Android 6.0 - Chrome Mobile 61.0.3163.98

I can facilitate further communication with the member (internal use: 1329756 ) so if you have any comments or recommendations or questions, please let me know.

**Comment by kistitan** [comment]
@BaneWilliams

Thank you for reporting this issue.

The only reason I can think of in a first step is that the user using an older version or the certificate that is used the check the Fetlife certificate is stucked from an old version.

So as a first step I would try
- Go to App settings of the device and Clear All Data for the FetLife app
- Uninstall FetLife App
- Install latest stable version from
https://fetlife.com/android

Thank you

**Comment by BaneWilliams** [comment]
You smart cookies! All solved.

I'm adding this to the tech support run through 👍

**Comment by Keen-man** [comment]
Hi, 
I have same problem with "Server could not be reached. Please check your internet connection".
Internet connection on my phone is ok. Other apps are working well.
This situation is on app version 2.13 -> 2.14.7
I tried Clear all data in app and also in device settings. Uninstall app and install app from https://fetlife.com/android -> did not help
What can I do, or what I do wrong?
