### ISSUE TITLE
Bug: not going to profile from avatar in group discussion 

### ISSUE THREAD

**Issue by flgnl** [fetlife/android#375]
Latest pre-release version

If I tap on an avatar from someone I'm not following in a group discussion, I'm redirected to my feed instead of the user's profile. If I am following the user I'm directed to their profile just fine.

**Comment by kistitan** [comment]
Thanks for letting us know.
Looking in it

**Comment by kistitan** [comment]
This issue should be solved now.
Please feel free to reopen otherwise.
