### ISSUE TITLE
Multiple photos display problem

### ISSUE THREAD

**Issue by vizman2** [fetlife/android#376]
As of Fetlife app 2.12.9 I have a similar problem as described in the issue #271 .
The former problem was with displaying single photos, now multiple photos aren't displayed.

**Comment by kistitan** [comment]
Yes, sorry it a regression issue.
Will deliver a fix later today.

Thanks for letting us know

**Comment by vizman2** [comment]
To be honest I am not sure when the photos stopped being displayed. I was sure it happened as of 2.12.9, but I downgraded to 2.12.0 and couldn't see multiple photos either. I tried clearing cache, but it didn't help. I downloaded version 2.11.16 from FetLife.com and can confirm that the photos are displayed correctly on this version. I am sure I had a newer version before, but can't remember which one. Anyway, I noticed the problem when upgrading to 2.12.9, but now it seems it must have appeared in some earlier version. If that's a problem to fix, I will stick to 2.11.16 where everything works correctly.

**Comment by kistitan** [comment]
Hi @vizman2,

Didn't it get solved in 2.12.12?

https://github.com/fetlife/android/releases/download/v2.12.12/fetlife-2.12.12.apk

Sorry, I just released it on Saturday night and was too tired to update this message.

(Note: this is a strange issue as officially it should work how it is, and unfortunately the old workaround is not possible any more to be used so in 2.12.12 I tried anew workaround but as none of our test devices has this issue I couldn't test it.
So I would appreciate if you tried 2.12.12 too but if it doesn't work you might need to downgrade again until I figure out other workaround)

**Comment by vizman2** [comment]
Hi @kistitan ,
It looks like the problem isn't as of 2.12.9 as I mentioned before. I must have missed in during former upgrades. What I'm sure about is that app. ver 2.11.16 displays photos correctly while they are not displayed on apps. ver 2.12.9 & 2.12.12.
I took 2 screenshots at exactly the same feed position on 2.11.16 and 2.12.12.

**Feed on 2.11.16:**
![2017_11_20_18 29 39](https://user-images.githubusercontent.com/25622476/33033082-7e77c816-ce23-11e7-91ec-cbf12ae23c23.png)

**Feed on 2.12.12:**
![2017_11_20_18 33 15](https://user-images.githubusercontent.com/25622476/33033094-9012c9e0-ce23-11e7-9fad-e34c1b98c5fc.png)

As I mentioned before, I can use the version that works best for me. Sooner or later I'll change my phone to a newer model, so won't be facing the issue anymore :-)

**Comment by kistitan** [comment]
Some other workaround implemented.
Please feel free to reopen if it dud not help.
