### ISSUE TITLE
No notification shown on lockscreen

### ISSUE THREAD

**Issue by mist** [fetlife/android#377]
Since not a long time I have no notification shown on the lockscreen anymore on both of my devices. I'm not sure if it is related to an Android Update but I believe it came with an app update.

The privacy Settings on my system are "Show everything on the lockscreen" system-wide and in my FetLife Notification System-Settings. And anonymous notifications turned off in the app.
This does not apply to "Update Available" notifications though.

I searched for something related in commit messages and issues, only found  #187 maybe being related (but the problem is newer).

Android 7.1.2 | Secpatch 2017-09-05 | AOKP 2017-10-05
Android 7.0 | Secpatch 2017-08-01 | Samsung Stock

**Comment by kistitan** [comment]
Hi @mist ,

This is probably because by default our notifications are set to secret.
We will see if we can add this to the settings or just simply change the value to private.

Thank you for bringing this up

**Comment by kistitan** [comment]
This issue should be solved now.
Please feel free to reopen otherwise.
