### ISSUE TITLE
Tapping on update notification doesn't download APK

### ISSUE THREAD

**Issue by thezerogod** [fetlife/android#378]
When the app notifies me that a new version is available and I tap the update, a new Chrome tab opens and closes but the APK file does not download.

Expected behaviour: either the releases page opens and presents a link to the APK file, or the APK file download is initiated immediately.

**Comment by FernandoMiguel** [comment]
This as always been the case and even if you are given the link directly, it does that.
I suspect it is related to the way github exposes the mimetype to android browsers.

To make things worse, visiting the github project page from a mobile device, makes the site load a mobile layout that doesn't show the release tab.
A user has to switch to desktop mode to reach it.

I would probably recommend fetlife team to host the apk elsewhere in their CDN allowing the app to pull it directly on updates, solving this long time issue.

**Comment by kistitan** [comment]
From version above 2.13.0 all new updates will be downloaded by internal download manager so this issue should be solved from then.
Thank you for your patience and help
