### ISSUE TITLE
Navigating using the top-left "back" button exits the app

### ISSUE THREAD

**Issue by thezerogod** [fetlife/android#379]
When I use the top-left "back" button to navigate back from a thread in a group, I am navigated back to my device home screen or to the app I was using before switching to FetLife.

Expected behaviour: the "back" button should take me back to the screen I have designated as my starting screen for the app (in my case, Feed).

**Comment by FernandoMiguel** [comment]
Confirming same behaviour and it's very annoying.
I have to kill the app and open again to go back to the starting screen

**Comment by kistitan** [comment]
Should be fixed in latest version
