### ISSUE TITLE
Groups content is slow 

### ISSUE THREAD

**Issue by FernandoMiguel** [fetlife/android#380]
I love the new layout to read and comment on group posts.

The only problem seems to be that while the original post loads instantly, all other comments do take many many seconds to load, giving the user the idea no comments are available.

It would seem the backend call to the api that fetches the comments of group posts needs considerable improvements, as it is doing probably a very slow query to the database

**Comment by kistitan** [comment]
Thanks for letting know.
We didn't notice any significantly low speed compared to other API call, but we will keep an eye on it.

**Comment by kistitan** [comment]
There was a performance issue found connecting to the experimental markup support.
It has been fixed for a while, so closing this for now, 

please feel free to reopen or open a new one if signifcant performance issues would appear again.
