### ISSUE TITLE
Groups missing in list and returning and dissappearing etc

### ISSUE THREAD

**Issue by flgnl** [fetlife/android#384]
When I open the groups list, some of my groups are missing. When I scroll to the bottom, I see the loading icon and then the missing groups appear. Then I open a group, go back to the list and the same groups are gone again. These are groups throughout the alfabet, can't find anything in common. Quite an annoying bug.

Latest version

**Comment by kistitan** [comment]
@flgnl 

Thank you for reporting.
Must be a sync issue between server and app, on it.

**Comment by kistitan** [comment]
This issue should be solved now in latest releases.
Please feel free to reopen otherwise.
