### ISSUE TITLE
Landscape message posting

### ISSUE THREAD

**Issue by PhilosophersSage** [fetlife/android#385]
Using version 2.12.19 on a Google Pixel XL (original) running Android 8.0.0. When the phone is in landscape position I can enter a message to a user or group but cannot send message using the keyboard send key. I must rotate phone back to portrait position and use the application send button.

**Comment by kistitan** [comment]
Thank you for reporting this issue.
Investigating...

**Comment by kistitan** [comment]
We did improvements in our layout, but I forgot to ask if it actually solved the issue. 
I hope it is solved, however we are going to replace our messages screen with webview based screens in short term, so the issue will be obsolote soon.

Closing this for now.
