### ISSUE TITLE
Kinky and Popular section

### ISSUE THREAD

**Issue by timywimy** [fetlife/android#387]
Hey there,
First of all thank you for this great app...I really appreciate the development.

I have a feature request...is there anything going on regarding the k&p section?..
It would be awesome if I could browse around this section (or fresh or stuff I loved) with your app. By now I have to start my browser and it is not that comfortable there :)

**Comment by kistitan** [comment]
Yes, both of them in our short term list.
First we need to reduce the number of issues here a bit, and do some slight refactoring and then comes the explore section.

Thank you for your patience.

**Comment by kistitan** [comment]
Merging issue into: https://github.com/fetlife/android/issues/276
