### ISSUE TITLE
unable to install 2.12.21

### ISSUE THREAD

**Issue by thezerogod** [fetlife/android#389]
downloaded the APK twice, but my phone won't install it; I get a message that the package appears to be corrupt.

**Comment by CyBradMachina** [comment]
Same here says unable to install and downloaded 3 times and still same message and on Android 5.1.1 lollipop LG K7

**Comment by Two-Finger** [comment]
Same here, on Android 4.4.4.

If it's any help, the install screen was oddly listing only a "USB read" permission.
I remember the app needed quite a few more.

**Comment by danielcor** [comment]
Didn't see a reason, but on Android 8.1 beta, I'm getting repeated failures to install the latest version today.

**Comment by LupaCattiva** [comment]
I also got the error that the package appears to be corrupt. I tried downloading and installing twice. I am running on Android 7.0

**Comment by kistitan** [comment]
Hi guys,

Thanks for letting us know about.
We are investigating it.
Maybe file got corrupted during upload.

We will keep you updated

**Comment by kistitan** [comment]
It should be fixed now.

There was a versioning issue.

Sorry for the inconveniences.
