### ISSUE TITLE
Not loading new preview build

### ISSUE THREAD

**Issue by VaanAuron** [fetlife/android#390]
On my phone I have notification that there a new preview build but won't let me download it and there no where I can download the build on get hub I'm running Android 5.1.1 lollipop LG

**Comment by Seelenoede** [comment]
You can always find the newest builds here: https://github.com/fetlife/android/releases

**Comment by kistitan** [comment]
Hi @Seelenoede ,

Thank you for helping us out with the link.
In our latest preview build we already integrated a new download manager for newver versions of the App, so hopefully from now on future releases will be less troublesome do download.

Thank you

**Comment by kistitan** [comment]
Versions after 2.13.0 will be downloaded with the new internal download manager, so this issue should be solved after. Thank you for your patience.
