### ISSUE TITLE
REQUEST: "Restricted to:" in groups and default text for empty rules

### ISSUE THREAD

**Issue by Seelenoede** [fetlife/android#391]
The "restricted to:" section in the group overview is still missing in the app. It would be nice if it could get into the "Rules" tab.

And groups that don't have any rules set, have an empty "Rules" tab, which looks kinda weird. I don't think it is a problem on the website as rules are together with the description but in the app some could think that it could be a bug. So I suggest a default text for groups with no special rules or rules stated in the "Rules" section like "There are no further rules." or something similiar.

**Comment by kistitan** [comment]
Hi @Seelenoede ,

These are good suggestion to further improve the current group section.

Thank you

**Comment by kistitan** [comment]
Hi there,

this issue will be solved with the new App concept, using webviews and display the website content directly.
We have a separate issue tracker for that progress, so closing this for now, to avoid duplication.

thanks for your understandings
