### ISSUE TITLE
Group you aren't member of allows posting....

### ISSUE THREAD

**Issue by scruffynerf** [fetlife/android#393]
Just realized the app took me to a group I wasn't a member and 'allowed' me to post in a discussion...except it didn't allow it, it took the entry but the text stayed red.  Joining the group and reposting the comment worked as expected, but it shouldn't have let me comment at all, if I wasn't in the group.

**Comment by kistitan** [comment]
Hi @scruffynerf,

Good point.
We gone fix it,

Thank you for reporting it!

**Comment by kistitan** [comment]
This should be fixed by now
