### ISSUE TITLE
App won't open

### ISSUE THREAD

**Issue by AmarisAquata** [fetlife/android#394]
I go to open the app and it just gives me the message of it unfortunately stopping without even bringing the app up.

**Comment by AmarisAquata** [comment]
I have Android App v2.13.0 downloaded and this problem has only started today

**Comment by kistitan** [comment]
Hi @AmarisAquata,

I am really sorry for your inconveniences. It is weird, I cannot really see what can cause the issue.

Can you please try to go to your device's settings, go to Apps, select FetLife, "storage" and "clear all data".

Please try to login after and let me know if it helps.

Thanks and sorry again

**Comment by AmarisAquata** [comment]
It's ok, and it fixed itself.. I kinda think it just has something to do with my phone.
Thank you for your help though 🙂

**Comment by kistitan** [comment]
Thank you for letting us know.
Closing it now..
