### ISSUE TITLE
Events - server error messages

### ISSUE THREAD

**Issue by ntysecrets** [fetlife/android#396]
When accessing events get message "server can not be reached. Verify your internet connection"

Same message whether connected wireless or 4G.  Stopped working around vers 2.10.  Android 7.0

**Comment by ntysecrets** [comment]
Also completely cleared app data, removed, reinstalled app but didn't fix.

**Comment by kistitan** [comment]
Hi ntysecrets,

Thank you for reporting.
We are investigating the issue.

Can you please help us out with letting us know the device type?

**Comment by ntysecrets** [comment]
LG G6 
Android 7.0 
software version  Vs98814a 
Build NRD90u 
Nov 6 2017 security patch

**Comment by kistitan** [comment]
Hi @ntysecrets ,

Just a quick update, that we did not forget about this issue. 
We took a look at our reported device logs and with your device type there are indeed some timeout issues, but these are coming from the internal code of the device.
Usually these happans in case of slow connection or slow server API. Based on our tests are other feedbacks our API is not that slow and as far as I understood your connection was also stable.
So we are in a little bit in dark here, but still thinking about possible improvements here.

**Comment by ntysecrets** [comment]
The error occurs immediately with no wait time..

**Comment by kistitan** [comment]
@ntysecrets ,

That's makes it even more interesting.
Does it happen only with events?

**Comment by ntysecrets** [comment]
Only occurs with events so far.. I thought it may have been a dns issue so changed servers and same error.. Disabled wireless and went 4g.. Same error immediately

**Comment by kistitan** [comment]
That must be very annoying.
I am sorry but we still dont see the reason.
Would you mind maybe install a special version with extra logging to be able to collect some more information?

**Comment by ntysecrets** [comment]
I can do that.. Assuming the logging isn't too intrusive

**Comment by kistitan** [comment]
@ntysecrets ,

Sorry for letting you down you for long with this issue.
Still could not see any reason for why is it happening.

Is it still the same btw? - just checking it to be sure.

If it is still happening I will make the extra logging app this week.
Deifnitly nothing intrusive. Just the response from the network API, if there is any more information from client side why the connection could not be established.

**Comment by ntysecrets** [comment]
Yep.. Still get error immediately.. First thing I check with each new release...

**Comment by kistitan** [comment]
@ntysecrets 

I am really sorry for the long delay again. 
Can you please download the following test version and reproduce the issue several time, preferably with several hours in between?
https://github.com/fetlife/android/releases/download/untagged-626a658fcb26fe991079/fetlife-debug-2.14.8-TEST.apk

Thanks a lot
Your help and patience is appreciated

**Comment by ntysecrets** [comment]
I get 404 not found from your link..

**Comment by kistitan** [comment]
That's not good :(

Would you mind sending an email to me so I can send the apk in email?
krisztian@fetlife.com

**Comment by ntysecrets** [comment]
Email sent

**Comment by ntysecrets** [comment]
Just fyi.. I tried the latest release on an android tablet running an older version of the OS with the same resulting immediate error.. I look forward to getting the test version so the issue can hopefully get resolved.

**Comment by kistitan** [comment]
hi @ntysecrets ,

I went through bunch of logs, but havn't seen the added extra logs.
As we gather all logs anonymously can you help me to narrow my search?
You still using 7.0 right?
Do you happen to know your device build number? (LG G6 can be from LG-H870 to LG-h873)
Do you remember when did you reproduce the issue last time?
Or can you maybe reproduce it again and let me know the approx time when it happened?

Thanks a lot for your further help

**Comment by ntysecrets** [comment]
You never sent the test version apk to my email account when your download link didn't work..  Happens all the time every time immediately with no wait time.. Even tried different device with different android with same result.  I already provided info earlier in thread but here it is again and all I could find.

LG G6
Android 7.0
software version Vs98814a
Build NRD90u
Nov 6 2017 security patch

**Comment by ntysecrets** [comment]
Accessed events now and got same error as usual..

**Comment by kistitan** [comment]
@ntysecrets ,

I tried to contact you several times via email, but after several days the mail's got return with error message that the message is too large.
I am sorry for didn't notice earlier 

I will send a new download link than.

Thank you for your further patience.

**Comment by ntysecrets** [comment]
I look forward to the new download link

Thanks

**Comment by ntysecrets** [comment]
Test version still had the same error upon initial download.. After using for a while, events suddenly started working tonight.. Guess will see how long it lasts

**Comment by kistitan** [comment]
@ntysecrets 
Are they still working?
I checked the extra logs, but did not see any reasons why could it happen.

**Comment by ntysecrets** [comment]
Test version events is still working.. I dunno..

**Comment by Keen-man** [comment]
I have same problem with server in app. 2.13 and 2.14.7

Device:
Xiaomi Redmi 1s
Android 4.4.4
MiUI 9.2
Internet connection is OK

**Comment by kistitan** [comment]
Sorry for abandoning this issue for so long, we were doing an experimental work for changing the whole code that would likely to solve issues like that., but we had to close the experimental work for several reasons, so we have to look at this issue again.

I have to ensure you it is annoying, but as it is difficult to reproduce it from our side, we are a bit still in darkness.

**Comment by ntysecrets** [comment]
The issue has resolved itself with one of the app updates or my upgrade to Oreo.
