### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by nightkillslove** [fetlife/android#397]
Notifications are appearing on my lock screen and before they didn't. And when I unlocked my cell id get the info for the notification

**Comment by 927589452** [comment]
You should be able to change this going to notifications searching for fetlife and disable the show in Lockscreen

AFAIK

**Comment by kistitan** [comment]
Hi @nightkillslove,

Sorry for the late answer.
Actually @927589452 is right (thanks for the comment), you are able to change the setting at your device's App settings anytime.

The only thing we changed is that now we are relaying on this device settings instead of overruleing it.
