### ISSUE TITLE
Enhancement Request: Messaging

### ISSUE THREAD

**Issue by kamakazi414** [fetlife/android#398]
When starting a new message, display edit text box for Subject in addition to message body.

**Comment by kistitan** [comment]
Hi @kamakazi414 ,

Unfortunately I have to say this is an intentional design decision as in longer term we might will go for one discussion per user what will make subject obsolate.
If we change that track we will add the subject entry option.

Thanks for your understandings.

**Comment by kistitan** [comment]
With the new App concept we are going to have webview based screens displaying the wbesite content directly, so we are going to have subject screen soon.

We have a separate issue tracker for that progress so closing this for now to avoid duplication.
