### ISSUE TITLE
Quirks in api

### ISSUE THREAD

**Issue by PdMFL** [fetlife/android#399]
# Login
I Found that login is a bit hard and that I had to use multipart login

In issue: #238 is described that there should be no need for the multipart.

The post that I make (my workaround):
```C#
//Params contains client_id and client_secret
string url = https://fetlife.com/api/oauth/token" + param;
string body = $@"--{boundry}
Content-Disposition: form-data; name=""username""

{username}
--{boundry}
Content-Disposition: form-data; name=""password""

{password}
--{boundry}
Content-Disposition: form-data; name=""grant_type""

password
--{boundry}--
";
```

Other request I can do normally without this multipart but couldn't get CURL or other methods working.

# Image downloading/showing in application
The second issue that I have is displaying images. When I get a response from '{base_url}}/{{api_version}}/me/' I get a valid response. 
When I try to open the avatar variants image link I get a  403 with the body: 'Not Allowed: Hot Linking' How could I retrieve a image without triggering the Hot Linking?

**Comment by kistitan** [comment]
Hi @PdMFL ,

To access images you also need the valid token in the url.
Without a living token, it would be easy to access them without being a FetLife user.

For login we use an OAuth2 engine so we rely on its implementation, but as it is OAuth 2.0 verified in theory it should not cause any trouble.
Maybe it would worth to play around with an OAuth2 client library?

**Comment by kistitan** [comment]
Closed this for now.
Please reopen it in the future in case of need of further assists
