### ISSUE TITLE
Tapping on a writing in Stuff you Love opens it in an external browser

### ISSUE THREAD

**Issue by ghost** [fetlife/android#400]
Doing the same in the Feed, or in a profile's Activity tab, opens it in the app.

(Also, the "you" in "Stuff you Love" should probably be capitalized, as in the web site.)

Happy and kinky new year!

**Comment by kistitan** [comment]
Hi @Two-Finger ,

Thanks for letting us know.
Investigating.

Best wishes for you too for the new year! :)

**Comment by kistitan** [comment]
This issue shoudl be fixed now, feel free to reopen if it was not the case
