### ISSUE TITLE
 grouped notifications unexpected behaviour

### ISSUE THREAD

**Issue by 927589452** [fetlife/android#401]
When clicking on the grouped Notifications one of the notifications is opened in the browser instead of the application

**Comment by kistitan** [comment]
Hi @927589452 ,

Thanks for letting us know.
We could not reproduce the issue so far, but keep investigating.

**Comment by CyBradMachina** [comment]
I also experience this too still like a mention in a thread or comments added to thread I'm following but when the multiple threads getting notifications it defaults to asking about opening a browser

**Comment by kistitan** [comment]
Hi there, 

This issue should be solved in the latest version 
Can you please confirm it?

**Comment by kistitan** [comment]
Please feel free to reopen if it does not.

**Comment by FernandoMiguel** [comment]
i have 2.15.4 and it still groups everything.
and when i click it, it goes to Groups, not notification tab
