### ISSUE TITLE
No comment field in group discussions when opened from feed. 

### ISSUE THREAD

**Issue by flgnl** [fetlife/android#402]
When I open a group discussion from an 'X commented on a group post' item in my feed, the comment field is missing at the bottom. When I open the same discussion from the group itself, the comment field is shown.

Latest preview version.

**Comment by kistitan** [comment]
Hi @flgnl,

Can you please check if you are actually member of the group?
You have to join to the group in order to send message.

Thank you

**Comment by flgnl** [comment]
Hello, 

Yes I am a member. Earlier today I noticed the same issue from the group discussion list as well. It was a thread I had opened from my feed before. After that I opened another discussion with had the field. Then I returned to the original thread and the field was present again.

What I do notice when I open a group, is that at first it doesn't indicate I'm a member (at the top, it says join). After about a second this changes to leave. Maybe when a discussion is opened from the feed or directly after opening a group, the membership status is not known yet.

**Comment by flgnl** [comment]
I even have this issue in my own groups. And indeed, when I open a discussion directly after opening a group, the field is missing. When I wait a few seconds, it's there. Did you recently make the presence of the field dependent on the membership status? Where before it was shown regardless of that? Then that's probably the issue. Membership status of the group is just not known yet when a discussion is opened too fast after opening the group or a discussion is opened from the feed.

**Comment by kistitan** [comment]
Hi there,

Thank you for clarifying the issue.
Indeed this is the case. Based on user requests we made the input field hidden if someone is not a member as that also caused confusion for some users.

And as you noticed right ineed we have to make a server call to verify the membership that takes a bit of time 
I would say not displaying the messages until the second call finishes also not a nice options as more frequently people want to read as soon as possible.

Hmm...

Would it be less confusing if the input field wasn't hidden only the send button disabled?
So by the time the message is typed most probably it can be already sent if you are a member.

**Comment by flgnl** [comment]
That would be an option, or you could make the field appear as soon as membership is confirmed.

Or keep a list of the memberships in cache and check this in the background every once in a while (and of course update it if a group is joined or left using the app). After all they're also needed to determine which groups should be in the group list. You could always do an additional check when something is posted to prevent accidental posts in groups someone has just left. The only issue then would be how to deal with groups which have been joined in the mean time using for example the website. But that also depends on how often 'once in a while' is.

But maybe my first suggestion is clearer. Although I must say the fact that groups first appear as not joined might be a bit confusing to people as well.

(As you might have figured out, I'm a developer myself. So kind of familiar with these kinds issues.)

**Comment by kistitan** [comment]
New version contains update.
Please feel free to reopen this issue if it was still inconvenient.

Thank you
