### ISSUE TITLE
Allow removing comments (which could contain PII)

### ISSUE THREAD

**Issue by jidanni** [fetlife/android#407]
Please coordinate with upstream that now with the release of the App it is more important than ever to allow users to delete or at least edit comments they posted.

Simple copy and paste errors might result in users posting Personally Identifiable Information, bank account passwords, family records, love letters, even entire resumes.

With no way to quickly delete them, in some cultures that could be pure suicide. What was seen as a liberating website suddenly becomes the worst Outing Machine.

Just as one would not want the member database hacked leaking private information, this leak should be plugged too.

No, all Suggestions, Ideas, Wishlist Items to upstream about this issue have been refused.

**Comment by jidanni** [comment]
@johnbaku Please have a look. Thanks.

**Comment by kistitan** [comment]
Hi @jidanni ,

This might be a very valid point, so I keep this post open for a few days, but after I really would like to remove it as this GitHub project is only for issues that can be solved within the App.

If you are in doubt where is the best place to post your feedback, can you please get in contact with our caretakers via caretakers@fetlife.com?

Thank you for your help and understandings

**Comment by jidanni** [comment]
OK I'll ask caretakers@fetlife.com to please comment on this bug.

**Comment by jidanni** [comment]
> From: Caretakers <caretakers@fetlife.com>
> Subject: Re: github
> To: jidanni@jidanni.org
> Date: Fri, 12 Jan 2018 09:35:16 +0800
> 
> Hi there!
> 
> Thank you for your input.
> 
> Unfortunately, as it states in our Community Guidelines (https://fetlife.com/guidelines/community):
> 
>  > Think Twice Before You Hit “Say It!”
>  > You can remove any content on your profile at any time. It is your profile after all!
>  >
>  > You should think twice though before you start or comment on any discussions. To maintain the integrity of discussions
>  > we don’t remove the original post or any comments unless they break one of our guidelines or our Terms of Use.
> 
>  While this is a question that we will continue to consider and review, currently this is why we don’t allow that.
> 
> James

**Comment by kistitan** [comment]
Hi @jidanni,

Thanks for posting this for clarity.
For obvious reasons if this feature is not available at the website we also cannot do it in the Android App.
If this will change we can add it in the All too.

Thanks
