### ISSUE TITLE
Stuff you Love loops back to the beginning

### ISSUE THREAD

**Issue by Two-Finger** [fetlife/android#410]
Scrolling past the 22-nd story causes the stories to repeat from the beginning.
This started happening in v2.14.0.

Galaxy S4 Mini Plus, Android 4.4.4.

**Comment by kistitan** [comment]
Hi @Two-Finger,

Wow. This is a nasty bug.
Thanks for letting us know. 
We will fix as soon as we can!

Thanks again

**Comment by Two-Finger** [comment]
Fixed in v2.14.3. Thanks, @kistitan!
