### ISSUE TITLE
See release notes notification should give us a chance to tap it

### ISSUE THREAD

**Issue by jidanni** [fetlife/android#412]
We install the new version. At the bottom of the screen we see a message pop up momentarily, it says to see what's new in the release notes. Well if we are fortunate to tap that message in time before it disappears, it should take us to the release notes. Well apparently it didn't. Or maybe I wasn't fast enough. It would be more polite if it just stayed on the screen giving us to a chance to tap it.

**Comment by jidanni** [comment]
(Sure, the release notes are available in the left menu.)

**Comment by kistitan** [comment]
Yes it is indeed a available in the left menu, but we can indeed add a tap options.

**Comment by kistitan** [comment]
This new feature is available in latest version.
