### ISSUE TITLE
Left panel not available when viewing pictures

### ISSUE THREAD

**Issue by jidanni** [fetlife/android#415]
Make the left panel still be available to slide out even when viewing pictures. I'm certain that there must be some room at the edge that will not be in conflict with moving the pictures left and right.

**Comment by kistitan** [comment]
Hi @jidanni,

Thanks for your message.
I am sure it could be useful sometimes but in this manner we follow the UI guidelines. Also even if it was probably possible technically it would be tricky and with limited gain.
So as we have limited resources and lot to do, so probably we won't change this any time soon.

Thanks for your understandings
