### ISSUE TITLE
Event map

### ISSUE THREAD

**Issue by Lilchik2086** [fetlife/android#416]
I noticed this across the board as in an avid user of the app.  I post events often.  But I am noticing that events that are on the event page "website/desktop" are not on the events map in the app.  There are some events that show, and some events that don't show.  My Sir placed an event and his showed, but when I placed an event, it did not show up.  I noticed this because I had 3 events that never showed up on the event map, even though I did everything exactly right.  But then I asked my Sir to do a test event, his did show up.  Also, I looked into it in my community, and then in other local communities.  It would appear that this is a problem everywhere.  Some people post events and they show up on the map, and others post events and they don't show up on the map.  Also, I made sure that I posted the address and location to advertise in, in all the appropriate fields.  Please fix this!!!

**Comment by ironjan** [comment]
Hi,

Not directly associated with the app, only trying to help. Can you provide
looks to the events in question, i.e. the ones you created in the web that
didn't show up?

Lilchik2086 <notifications@github.com> schrieb am Di., 16. Jan. 2018 09:04:

**Comment by kistitan** [comment]
Hi @Lilchik2086,

Can you please make sure the full address (including city, state, etc) is presented in the Address field?
(There are separate fields for the city, etc, but those as of now not taken into consideration for the event map.
There is already a bug report for that for the server side code. 
Please let me know if it worked

**Comment by CyBradMachina** [comment]
It directly is in direct connection to what location the event maker lists the location of the event being at, if it says anything other than any semblance of an actual address such as private residence or TBA or TBD or anything else it won't show up in said geographical location, as a side bar though would be nice if a city and state listing was required and the other information like exact street address and zip code could be masked and kept private and/or exact location without issues like this happening imo

**Comment by kistitan** [comment]
Thanks for your comment, indeed without full address we cannot show an event on the Map.
If only the city is specified we could still mark it in the middle of the city but that could lead to confusion.
(Like App users would start a navigation to that location based on our Map and when they arrive they realize it is not there actually)

**Comment by Lilchik2086** [comment]
The events map seems to be working correctly now, finally.   Before, all information was in there.  No field was left blank.  No field had tba or tbd.  And my events just weren't showing at all.   The last event I put up did show up on the map.  But, I am concerned that in an area near me, they had 14 events, all were filled with the correct information or at least the minimum required for it to show up on the map, and only half were showing up.   So, this had to have been a glitch in the app/FL system.
