### ISSUE TITLE
Lock/unlock by PIN

### ISSUE THREAD

**Issue by Keen-man** [fetlife/android#417]
Please add possibility set up lock/unlock Access to contents after start application.
It could be better for privacy.

**Comment by FernandoMiguel** [comment]
do you usually leave your phone unlock? 
i know i dont

**Comment by Keen-man** [comment]
sometime I lent my phone to someone for show photos or show something for example on YouTube. But without this ability I am afraid that someone browse my phone and look for interesting application. It can happen. With this ability I can be cool.

**Comment by FernandoMiguel** [comment]
On recent versions of android you can pin an app, so folks can't leave and
access anything else till they unlock

-- 
Fernando Miguel

**Comment by kistitan** [comment]
hi @Keen-man,

Thank you for your message.
You can go to the App settings and select "Go Vanilla" at General Settings. 
That will change the App icon and name to FL.
Than make sure that you log out from the App (also from the Settings) and next time when you log in you leave the "remember me" check box unchecked.

This will keep you signed out and make sure that whoever finds the App will see only a general FL logo so (unless (s)he actually knows the App and this feature ,) nobody will recognize it as  kinky App.

I hope this helps

**Comment by CyBradMachina** [comment]
@Keen-man get another app that locks or disguises apps, i have an app that i could use to lock them sure but that's fairly suspicious they have another feature that allows "disguising" what happens is unless you know the trick to get past it, the app you're trying to protect makes it look like it just crashed so no matter how many times they try opening it will always result the same unless trick to use is known

**Comment by Keen-man** [comment]
thank you for comments and tips.
I tried secure an apps. But security of Apps in my phone is only by swipe (not PIN).So IT IS easy to see. May be in newer version of android there is possible secure by PIN. But I have to using KitKat (4.4) still

**Comment by Keen-man** [comment]
Oh, i found out how to disable to showing finger's way during swiping secure code. So sorry for my last comment.
