### ISSUE TITLE
Notifications: Show correct time (of e.g. message) instead of current time

### ISSUE THREAD

**Issue by mist** [fetlife/android#420]
Ahoi,

when I return from having no internet connection I get my fetlife Notifications shown. But the time in the Notifications is always the time I got the notification, not the time when the message (or @) was sent.

It is possible to set this time with `Notification.Builder setWhen (long when)`, see [Notification.Builder.html#setWhen(long)](https://developer.android.com/reference/android/app/Notification.Builder.html#setWhen) for details.

I'd love to have this feature implemented. Besides that: You're great and I love the app :*

Cheers,
mist

**Comment by kistitan** [comment]
Hi @mist ,

Thank you for your suggestion.
I agree it would indeed be nice, however as of now we do not receive in the App the actual time when the message was created, so it might be a bit more complex than just simply add the time to the Notification. 
On the other hand we might can get easily the time stamp when the message was actually sent from the server what is very close to the actual message creation time.

Let me see what can we do in short term about this.

**Comment by mist** [comment]
Ahoi @kistitan,

I guess the timestamp of the push message should be fine aswell (if it has one, never worked with push before).

if you point me to the method which is run by the push service (or whatever is doing the job) I could probably do it myself and file a pull request.

Cheers,
mist

**Comment by kistitan** [comment]
Hi again,

Thanks for your offer. I really appreciate it.
It was a low hanging fruit so I quickly modified it.
It is part of our latest preview release.

If you were interested you can also find the change in our latest merged pull requests.

Thanks again.
