### ISSUE TITLE
Group tab with your group listings crashes after a small time period but being actually inside a group doesn't

### ISSUE THREAD

**Issue by CyBradMachina** [fetlife/android#423]
Title says it main group tab for user (such as my group listings from my perspective) crashes the app shortly after clicking it but if you're inside a specific group that error doesn't occur and oddly it used to be more frequent but as new versions have rolled out despite my inability to update further this issue has lessened so i wonder if it's a general server issue rather than a specific app version issue?

**Comment by kistitan** [comment]
Hi @CyBradMachina ,

Sorry for the late answer.
I actually started to investigate the issue in the meanwhile.
It seems some of the group info does not arrive to your phone from the server.

As a first step I will make the App not crashing, but it wont be the solution yet as we still should figure out why in same case not all the info is there.

Thanks for yoiur patience

**Comment by CyBradMachina** [comment]
Alright cool that's fine whatever works 🙂

**Comment by kistitan** [comment]
Crashes should be eliminated now in latest version, however some information might not arrive so I keep this issue open for further investigation.

**Comment by Two-Finger** [comment]
Still crashes for me in v2.14.7.
Android 4.4.4.

**Comment by kistitan** [comment]
hey @ghost,

We found another possible reason that we fixed in 2.15.4.

Please feel free to reopen the issue if it was not the case.
