### ISSUE TITLE
search feature

### ISSUE THREAD

**Issue by Trife66** [fetlife/android#425]
If there was any way to implement a better search feature where you can search for FetLife people regionally, I know you can search for members name, but I think if you could search by city or state it would help connect a lot of people, just a suggestion

**Comment by kistitan** [comment]
Hi @Trife66 ,

Thanks for the suggestion, but in this manner we follow the website search policy.
What we are working on in the moment if to embed also the recently added general search in the App.
This will help at least to reach content of those who are you connected with easier.

I know this is not what you meant, but this is what we plan to add in the near future. 
In a bit longer term we will also investigate what is the best way to add "places" in the app similar how it exits now at the website.
