### ISSUE TITLE
Unknown apk

### ISSUE THREAD

**Issue by LupaCattiva** [fetlife/android#427]
I just wanted to double check that the follow apk is not from Fetlife:
a1001012806.apk

It has shown up on my phone with Bitdefender identifying it as malicious. It is giving me 'trojan.fakeapp.gz' as the description. 

Thanks!

**Comment by navyguyg** [comment]
Anything from Fet has always been labeled fetlife when I downloaded it.

**Comment by ironjan** [comment]
Do you remember what page you downloaded this apk from and can you provide
the link?

AL <notifications@github.com> schrieb am Mo., 12. Feb. 2018, 19:24:

**Comment by kistitan** [comment]
@LupaCattiva ,

Yes I can confirm it is not the official FetLife App.
Indeed it is a very important question, have you downloaded it as a FetLife App?
If yes, can you please help us out where did you download it from?

Thank you

**Comment by kistitan** [comment]
Closing this issue for now.
Please reopen in case of new information about the issue.
