### ISSUE TITLE
Deleted conversation

### ISSUE THREAD

**Issue by izzywolfe** [fetlife/android#430]
I've deleted conversations from the website but they still show up on the app. And when I go into them they tell me there is a connection error but they will still let me converse in them even when they are still deleted on the website. I've looked but haven't found anyone else having this issues of  yet and I apologize if someone has and I missed it. Plus it would be really nice to be able to delete them in the app instead of having to swap back and forth.

**Comment by kistitan** [comment]
Hi @izzywolfe ,

The App should remove deleted conversations at the next sync, however we get reports that it does not always happen.
We are working on a new synchornization concept to solve the issue.

What you can do in the meanwhile is to go to the FetLife App's Settings > Profile Settings > Clear local User Data.

That will remove the cached content.

Thank you and sorry for the inconveniences

**Comment by izzywolfe** [comment]
Thank you. That did work. I appreciate your time and understanding

Sent from Yahoo Mail on Android 
 
  On Thu, Feb 22, 2018 at 5:56, kistitan<notifications@github.com> wrote:   
Hi @izzywolfe ,

The App should remove deleted conversations at the next sync, however we get reports that it does not always happen.
We are working on a new synchornization concept to solve the issue.

What you can do in the meanwhile is to go to the FetLife App's Settings > Profile Settings > Clear local User Data.

That will remove the cached content.

Thank you and sorry for the inconveniences

**Comment by kistitan** [comment]
I am happy it did.
Thanks for letting us know.

We will make sure to have it solved completly sooner than later.

**Comment by OkkiNL** [comment]
Hello,
Its the same for groups which i am no longer member of, they stay in the list.
And maybe there is more, i suppose you will know.

**Comment by kistitan** [comment]
Hi @OkkiNL ,

Thank you, we indeed still face some syncing issue in the live app in some cases, that e should still investigate.
One option is that we consider is to drop the offline support and have the app online only.
That would remove all these issues, and having internet covering more common, probably it would rarely matter.

**Comment by OkkiNL** [comment]
Hi, yes i understand. How do other apps deal with a problem like this, maybe they have the solution. Meanwhile I am trying to think with you.

**Comment by kistitan** [comment]
Merging this issue with  other similar ones.
Please follow this thread:

https://github.com/fetlife/android/issues/496
