### ISSUE TITLE
New Kotlin App: Login screen & Navigation bugs/issues

### ISSUE THREAD

**Issue by alphaStryke2k3** [fetlife/android#438]
Testing the new Kotlin app on a Nexus 5X emulator, API 27.

> On the login screen, enter username + password and tap on the "Login" button

**ER:** The keyboard should be dismissed
**AR:** The keyboard remains visible despite the fact that there are no editable fields on the main app screen.  The keyboard should have been dismissed when I tapped the "login" button before navigating

> On the login screen, I enter username and password correctly and tap the "login" button

**ER:** Some kind of indicator is shown to indicate a service call is in progress
**AR:** The app appears to do nothing before navigating into the main (tabbed) screen

> On the login screen, I mis-type my password and tap the "login" button

**ER:** I am informed of the login failure
**AR:** The app appears to do nothing, no progress indicator, no messaging

> Once logged in, select one of the other tabs then rotate the device.

**ER:** The selected tab is remembered
**AR:** The selected tab is reset to the first

> On the main screen of the app after tapping "messages" I am able to open two navigation drawers

**ER:** the main "hambuger menu" would be suppressed if the content contains its own navigation
**AR:** I am able to open both

> Inside messages, with the app nav drawer open I tap the back button

**ER:** the nav drawer would close
**AR:** the underlying web-view content navigates back and the main nav-drawer remains open

**Comment by kistitan** [comment]
Hi @alphaStryke2k3 ,

New alpha version is decided to be discontinoued for now.
Thanks again for giving your feedback about.
