### ISSUE TITLE
About this app - Install "button"

### ISSUE THREAD

**Issue by troybarrytoo** [fetlife/android#439]
Please move the install "button" to the top of the "About this app" screen. 

This screen is currently pitching the app, which is already installed on the phone, no need for the pitch.

Users looking to update to a new version will benefit.

**Comment by kistitan** [comment]
@troybarrytoo 

It is a good suggestion, however we that page is a reused version of the website. We reuse it in order the spare resources for other features.
Can you please give more details in what context do you use the install button, once you have the App already.

**Comment by troybarrytoo** [comment]
button is used to link to latest released app. a button on the web page or in the app page should be at the top, regardless. few people need the marketing BS if they navigate to that page, 1st time nor update. the button at top of page also establishes the expected action, it's not merely an info page. which, is what it looks like now. it will take a programmer 1 minute to change the page and 1 minute to regression test the page. job done. Sent with SolMail App

**Comment by kistitan** [comment]
Hi @troybarrytoo ,

I understand it annoys you, but it really not about push unwanted promotion about the App to those who are using it.
By the original idea you would go to the Android page only if you actually want to look at some of the available features about the App to know what you can expect. So in that sense the button has lower priority.
To get the latest version of App we have a Check to Update menu item in the menu, that will bring you the default notifications that is a more convenient way to update the App than download it manually.

But as I understand you rather prefer to update the App via the Android page.
Would you mind gving us some insight why do you find that more convenient than the check for update option?

Thanks again

**Comment by troybarrytoo** [comment]
thx for the reply. if I understand you correctly, I should be able to select the 'check for updates' menu option from within the app then see that an update is in fact available then the update will download and install itself... it's been months since I have updated the app, this may be how it works now. if so, great, problem solved. I recall, though, selecting the menu item and having the system flash a message saying an update is available, then disappear, then nothing. no magic download, no automatic install... I recall, then having to hunt around, sometimes on github, sometimes in an app menu somewhere, scrolling  scrolling... reading how great the app is (which I already use, paid to support, etc...) then finding a button to update. please tell me that the next time I 'check for updates' in the app menu, and there is an update, that the magic will happen - I don't have to do anything else except wait while the apk is downloaded and android automatically installs the new apk. if no magic, then please make the 'install updates' method super obvious.

**Comment by kistitan** [comment]
Hi @troybarrytoo ,

Check for updates indeed will make a system notification appear, that you should click on to start the update.
This method was not obvious for many users so we already have a request to improve it.

**Comment by troybarrytoo** [comment]
2 months later....

I load the android app and tap the 'check for updates' menu item....

a pop-up message is displayed for 10 seconds then disappears, there is a new preview release. yeah. 

the message does NOT indicated how to get the release nor how to install it... there is no button to install the new apk... 

I tap on the 'about and install' menu item. 

I scroll to the bottom of a long 'about' promo piece 

there is no need for this promo piece - 

1: app already installed... , already sold on its merits, 

2: menu item '... install' is most important, should be 'update' by the way, app is already 'installed', install button should be at the top of this page. OR... 

3:.. install button should be moved to "check for updates", PLEASE stop with the pop-up messages... really really bad design.

"UPDATE" button should cause the apk to be downloaded to the device, NOT jump to github.

people testing and downloading the apk should NOT be confronted with such poor work flow. I've done design, build, test for decades - I would never ask testers to go through this process. 

I get this is not the thinking amongst apk developers, that this is not a priority, that everyone is volunteering time (as am I...), but really? 

make it simpler to help out in the testing process, please.

PS

second and subsequent returns to the 'about and install' menu item CRASHES the app.

**Comment by troybarrytoo** [comment]
PPS

I tap the check for updates menu item, having already installed the update 2 minutes ago, the pop-up messages informs me there is a new update.... doubtful. seems like a bug.

**Comment by troybarrytoo** [comment]
PPS

the github comments seems to be the only way to provide feedback, unless my in-app searches overlooked a 'provide feedback' main menu item.

please add a 'Provide Feedback' main menu item, above the 'Check for updates' main menu item.

**Comment by kistitan** [comment]
Splitting these suggestion into two other issues due to duplication:

https://github.com/fetlife/android/issues/175
https://github.com/fetlife/android/issues/411

Please follow those.

Note: the install page refactor is out of the scope of this github repository as it is the direct display of the website page. 
However with improving install possibilities described in the other issues (direct download, link, check for update popup etc), the actual issue (complicated update/installation process) will be solved/improved even without page refactor.
