### ISSUE TITLE
Events Map

### ISSUE THREAD

**Issue by troybarrytoo** [fetlife/android#440]
At this time the Events Map is the ONLY apparent means of showing events, correct me if I am wrong.

Please at a "List" button to show a text only list of events sorted by date, newest to oldest date.

Also, the "My Events" button on the Events Map screen does not work, presumably a future feature?

I have the latest LG Android build, and the latest FetLife build.

**Comment by toxalot** [comment]
@troybarrytoo ~ The "My Events" text is not a button. It's a label for the next screen. Try touching it and swiping left. And if you swipe left again, there is an option to search for events by keyword.

Also, there is already an open issue for events: [Events not showing up](https://github.com/fetlife/android/issues/432). There is some discussion there about the need for a list.

**Comment by kistitan** [comment]
Hi @troybarrytoo and @toxalot 

Thanks for reporting the question and helping us out with answering it.
Indeed the My Events is not a button, you can swipe there just as you can to the search event page, where you can look for textual events.
Indeed there is not a by default event list from all over the world, but you can search for any location or type of event using the free search.

Sorry of sliding was not obvious.
We are working on a new version where hopefully this won't be any issue.
