### ISSUE TITLE
App crashes when click in banned profile

### ISSUE THREAD

**Issue by missyuri12** [fetlife/android#444]
I tried to click in a banned profile and the app crashed, sending me to login screen.

**Comment by kistitan** [comment]
Hi @missyuri12 ,

Sorry for the late reply. Than is indeed true.
We are looking at the issue.

Thank you for your patience.

**Comment by kistitan** [comment]
Hi @missyuri12 ,

The issues should be solve din our latest version: 2.15.4.
Please feel free to reopen this issue if it occured again.
