### ISSUE TITLE
App Crashes

### ISSUE THREAD

**Issue by thomasj94** [fetlife/android#445]
I have a Samsung Galaxy S8 and I get logged out of the app frequently sometimes it's once or twice every 5-15 minutes other times it's twice within 1 minute. It's unbearable. It makes it impossible to actually use the app. Please help...

**Comment by kistitan** [comment]
Hey @thomasj94 ,

May I ask which version do you use?
Since when you are facing the issue?

Thanks
Dreamlite

**Comment by thomasj94** [comment]
I have v2.15.0. It's been happening ever since I downloaded the app. I've only had it for a week tops.

**Comment by luciferche** [comment]
Hi guys, same issue over here . With last two versions of the app

**Comment by kistitan** [comment]
@thomasj94 @luciferche 
It is not a solution, but a workaround that might work:

Would you mind deleting all local storage of the App and login again?
In order to do so, please use your device's settings / Apps / FetLife App / Storage / Clear Storage.

Please let me know if it helps

**Comment by thomasj94** [comment]
I'll give it a shot. I'll let you know if that works.

**Comment by thomasj94** [comment]
So, It didn't seem to do anything. I still get logged out.

**Comment by kistitan** [comment]
@thomasj94 @luciferche ,

I am sorry it did not work.
Can you maybe give us some hints when the actuall logging out happen?
Is it connected to some specific activity like oppening a profile of a user, or something else, or it seems to be totally random?

Thank you again

**Comment by luciferche** [comment]
@kistitan Hey, sorry for not going into details before. 
It started happening with v2.15.0 of the app. Clicking "remember me" didn't do the trick. After going out of the app, and opening it again after a couple of minutes, it required me to login again.
However, push notifications were still being received (also for things I unchecked)
I uninstalled the app, but I will try again and possibly give you some more feedback about the issue.
I was thinking also about checking out the whole project and maybe help you guys on smaller issues

**Comment by thomasj94** [comment]
It doesn't seem to happen when  I perform a certain action. It is random, I could just stay on the Home Page and it will log me out, it happens when I click on a deleted account, when I type a text in Groups or even viewing a profile. It will not load and log me out completely and log out. I've uninstalled the app and reinstalled it too.

**Comment by kistitan** [comment]
Hey @thomasj94 

we found the source of the issue. 
It should be fixed in 2.15.4.

Feel free to reopen the issue if it occured again in the newest version.
