### ISSUE TITLE
Enhancement Ideas: Combing through the app

### ISSUE THREAD

**Issue by ImperfMage** [fetlife/android#448]
So after using the app I have some various things that I think would be some improvements to the app.
## The Live App

- Instead of having to click pictures to love them have it underneath the picture
- When viewing groups have a swipe option to view the groups that you have recently posted in like it does with the desktop version
## Fetlife preview v0.3-alpha1
- have an option to update it in the app instead of having to go to the live version
- have the ability to see when people are typing in private messages
**An issue I noticed**
- there was an issue I noticed when trying to update my feed, it would show feed from months ago and isn't showing anything new.
As of right now there are many things we can do atm because things haven't been implemented yet

**Comment by kistitan** [comment]
Hi there,

These are good suggestions, however fetlife alpha project has been stopped and we are having a new App concept, replacing native screens with webview based screens, so these impementation won't take place in the temporary native screens, rather we will follow the same layout as the website reponsive screens.

Thank you
