### ISSUE TITLE
Scrollbar size is relative to the length of the message in the middle of the screen

### ISSUE THREAD

**Issue by reneklacan** [fetlife/android#45]
😆

**Comment by JohnBaku** [comment]
@reneklacan public repo! :-p

**Comment by kistitan** [comment]
I am sorry but this is how to built in Android UI element works in case of long messages.

I will take a look if there is any workaround, but might be it works as designed and can't do anything about it.

Give me some time to solve higher priority issues before taking a look at it.

**Comment by reneklacan** [comment]
Sure, it's ok, it's not degrading functionality in any way, I just found it funny 😆 ... maybe we can even close this issue

**Comment by kistitan** [comment]
Just keep it open until I make a quick search.
It can be low hanging fruit.

I will close if there is no straightfirward solution.

**Comment by reneklacan** [comment]
👍

**Comment by kistitan** [comment]
The size changing scrollbar is an optimization from Android.
Correct size of the scroll bar could be calculated only if all the item size of the list would be pre-calculated that could be end up in some performance draw back.

smooth scroll bar option can be turned off, so Android would make more accurate calculation but as not all the items would be rendered even in that case the result would be still not perfect and scrolling would be less smooth.

I close this issue as any solution would end up in worse situation than how it is now.
