### ISSUE TITLE
Android 8.0: says it can't reach network 

### ISSUE THREAD

**Issue by jidanni** [fetlife/android#455]
Constantly says that it can't reach the network.

**Comment by jidanni** [comment]
But it can definitely check if it is the latest version.

**Comment by kistitan** [comment]
@jidanni ,

We are having an issue with connectivity from certain location.
2.15.5 has been releases moments ago to fix the issue.

Sorry for you inconveniences.

**Comment by johnbaku** [comment]
@jidanni has the issue been resolved for you?

**Comment by malachid** [comment]
As a side note, this was not 8 specific.  I haven't noticed it in a few days, but had seen it on 7 as well.

**Comment by jidanni** [comment]
OK now with what Release Notes says is 2.16.0 the problem is gone.
