### ISSUE TITLE
About & Install crashes the app 

### ISSUE THREAD

**Issue by flgnl** [fetlife/android#460]
When I go to the About & Install screen the app immediately crashes. This is with the 2.15.5 apk I got from the 2.16.0 notification. (See the other issue I just opened.) Don't know whether it happened with other versions as well, as I normally don't go there.

**Comment by kistitan** [comment]
@flgnl 

Indeed it is an issue with only 2.15.5.
It will be fixed as soon as 2.16.0 will be the stable version.
Please use it in the meanwhile.

**Comment by johnbaku** [comment]
@flgnl can you confirm that on version 2.16.0 this issue is fixed for you please? Thanks.

**Comment by flgnl** [comment]
Yes, I can confirm that.
