### ISSUE TITLE
v2.16 is very slow 

### ISSUE THREAD

**Issue by FernandoMiguel** [fetlife/android#462]
v2.16 interface is very slow, almost jarred, when moving across the feed, opening menus, and pressing the back button (app freezes trying to exit for example).
On an high end device like a pixel 2XL, moving across the feed this version feels like it's dragging. 
Previous versions were always buttery smooth

**Comment by malachid** [comment]
Agreed. Flinging down the page only goes a few items before it pauses. Very janky.

**Comment by ImperfMage** [comment]
Agreed things are running way slower especially messages

**Comment by kistitan** [comment]
Hi guys,

Thank you for letting us know, however there were no related changes at all that could effect the general user experience of the App.
The only changes were done, was to replace the notification and the friend request screens, all the other part are untouched.

Please maybe try to clear your local data (via App or device settings) and use a bit for a few more days, and let us know if the slowness still stays, than I can use some profiler to investigate, however as I mentioned earlier, there was no related code changes.

Thank you for your help

**Comment by FernandoMiguel** [comment]
I've cleared cache and storage data and relogin to the app.
Scrolling down the feed is still slow and jarred. Pressing the menu still hangs for a fraction of seconds

**Comment by malachid** [comment]
Maybe a change on the backend slowed down the api calls?

**Comment by FernandoMiguel** [comment]
@malachid from what i'm seeing it's not backend... even pressing the back key or the side menus seems to make the app stall.
this one android P ... but i've been running P since the 1st alpha without issue

**Comment by malachid** [comment]
It's not P-specific. I'm seeing it on 7.0

**Comment by malachid** [comment]
Maybe related, I see this in logcat while I am trying to scroll the feed:
```
07-11 09:29:28.828 I/art     ( 5125): Starting a blocking GC NativeAlloc
07-11 09:29:28.828 I/art     ( 5125): Starting a blocking GC NativeAlloc
07-11 09:29:28.849 I/art     ( 5125): Starting a blocking GC NativeAlloc
07-11 09:29:28.849 I/art     ( 5125): Starting a blocking GC NativeAlloc
07-11 09:29:28.875 I/art     ( 5125): Starting a blocking GC NativeAlloc
07-11 09:29:28.875 I/art     ( 5125): Starting a blocking GC NativeAlloc
07-11 09:29:28.895 I/art     ( 5125): Starting a blocking GC NativeAlloc
07-11 09:29:28.895 I/art     ( 5125): Starting a blocking GC NativeAlloc
07-11 09:29:28.914 I/art     ( 5125): Starting a blocking GC NativeAlloc
07-11 09:29:28.914 I/art     ( 5125): Starting a blocking GC NativeAlloc
07-11 09:29:28.934 I/art     ( 5125): Starting a blocking GC NativeAlloc
07-11 09:29:28.934 I/art     ( 5125): Starting a blocking GC NativeAlloc
07-11 09:29:28.953 I/art     ( 5125): Starting a blocking GC NativeAlloc
07-11 09:29:28.953 I/art     ( 5125): Starting a blocking GC NativeAlloc
07-11 09:29:28.971 I/art     ( 5125): Starting a blocking GC NativeAlloc
07-11 09:29:28.971 I/art     ( 5125): Starting a blocking GC NativeAlloc
07-11 09:29:28.990 I/art     ( 5125): Starting a blocking GC NativeAlloc
07-11 09:29:28.990 I/art     ( 5125): Starting a blocking GC NativeAlloc
07-11 09:29:29.011 I/art     ( 5125): Starting a blocking GC NativeAlloc
07-11 09:29:29.011 I/art     ( 5125): Starting a blocking GC NativeAlloc
07-11 09:29:29.029 I/art     ( 5125): Starting a blocking GC NativeAlloc
07-11 09:29:29.029 I/art     ( 5125): Starting a blocking GC NativeAlloc
07-11 09:29:29.049 I/art     ( 5125): Starting a blocking GC NativeAlloc
07-11 09:29:29.049 I/art     ( 5125): Starting a blocking GC NativeAlloc
07-11 09:29:29.068 I/art     ( 5125): Starting a blocking GC NativeAlloc
07-11 09:29:29.068 I/art     ( 5125): Starting a blocking GC NativeAlloc
07-11 09:29:29.089 I/art     ( 5125): Starting a blocking GC NativeAlloc
07-11 09:29:29.089 I/art     ( 5125): Starting a blocking GC NativeAlloc
07-11 09:29:29.109 I/art     ( 5125): Starting a blocking GC NativeAlloc
07-11 09:29:29.109 I/art     ( 5125): Starting a blocking GC NativeAlloc
07-11 09:29:29.129 I/art     ( 5125): Starting a blocking GC NativeAlloc
07-11 09:29:29.129 I/art     ( 5125): Starting a blocking GC NativeAlloc
```

**Comment by malachid** [comment]
I did some local testing. Stuff you Love and Friends perform better than Feed and Groups.  Maybe check if there is any differences on those sections (threading, paging count, etc).

**Comment by kistitan** [comment]
I think I found it, gonna check tomorrow

**Comment by ImperfMage** [comment]
Another thing i've noticed is that in this version there is still the bug where it says there is no internet connection. I have also tried the clear local cache and still seems to be running slow

**Comment by FernandoMiguel** [comment]
16.4 interface is fast again.
No more jerking, no more hangs clicking menus. 

Now if paging and pulling content was faster, app would be close to perfect

**Comment by malachid** [comment]
Confirmed for me as well
