### ISSUE TITLE
Mail 

### ISSUE THREAD

**Issue by Germanbight** [fetlife/android#464]
The 'all mail' icon or button isn't visible.

**Comment by johnbaku** [comment]
@Germanbight is it possible to take a screenshot and share it with us so that we can see what you see? Make sure to blur out any private information you don't want anyone else seeing.

**Comment by kistitan** [comment]
@Germanbight 
You mean in the conversation screen?
All conversations are not yet available in the current version, however we are working on replacing our current inbox that will make it work!

Thank you for your patience.

**Comment by johnbaku** [comment]
@kistitan if you know what @Germanbight is referring to mind sharing a screenshot with me so I can better understand please?

**Comment by kistitan** [comment]
@Germanbight Please correct me if I am wrong, but you are using App version before 2.16.0?
Is that right? 
If not, indeed please reopen this message and share a screenshot with us.

Your help is truly appreciated.

**Comment by Germanbight** [comment]
Hope the attached helps thanks 

--
Securely sent with Tutanota. Claim your encrypted mailbox today!
https://tutanota.com <https://tutanota.com>

11. Jul 2018 17:15 by notifications@github.com <mailto:notifications@github.com>:

**Comment by Germanbight** [comment]
I'm using 2. 15.5Can't see version 16
Hope the attached  helps Thanks 

--
Securely sent with Tutanota. Claim your encrypted mailbox today!
https://tutanota.com <https://tutanota.com>

11. Jul 2018 17:22 by notifications@github.com <mailto:notifications@github.com>:

**Comment by FernandoMiguel** [comment]
No attachment.
You have to use github. Cant email it as it gets filtered

**Comment by malachid** [comment]
@Germanbight you can see all the versions here
https://github.com/fetlife/android/releases
