### ISSUE TITLE
Notification Drawer redirect blank

### ISSUE THREAD

**Issue by tcdfl** [fetlife/android#465]
All notifications are being properly reported in the status and notification drawer.  When the notification is clicked (seems to be the only the comments and likes notifications), the fetlife app launches but it is opened to the notification tab and it is blank.  If the sidebar is opened and the notification tab is clicked, the notifications are populated.

**Comment by kistitan** [comment]
Hi @tcdfl ,

Thank you for reporting this issue.
We are investigating it.

**Comment by kistitan** [comment]
This issue has been fixed since we are displaying webview based notifications.

Closing this.

Please feel free to reopen if similar issue would occur.
