### ISSUE TITLE
Profile avatar not updated on sidebar

### ISSUE THREAD

**Issue by tcdfl** [fetlife/android#466]
If the profile avatar is updated on the site, the sidebar avatar is not.  It will only change if user is logged out and logged back in on the app.

**Comment by johnbaku** [comment]
@tcdfl good observation. Thanks for the report.

**Comment by kistitan** [comment]
@tcdfl ,

It is a known mechanism that you indeed have some delay as there is no direct push notification from the website to the App in case of profile update.
The avatar will be changed as soon as the acrtual profile is going to be retrieved again from the server so the change can be noticed.
You can try this by actually opening the give profile and wait for the sync finished.

Please let us know if it is indeed worked that way.

**Comment by kistitan** [comment]
Closing as it works as designed. 
And no report from end user from any deviations.
