### ISSUE TITLE
Entire Profile Description Gone 

### ISSUE THREAD

**Issue by shiregray** [fetlife/android#470]
On user profile (my own, everyone else works), nothing except header shows, with raw code attached.
Ex: all of the "###"s are showing. 

To note: worked immediately before updating. 

Version: 2.16.4

**Comment by flgnl** [comment]
Hmm, I haven't checked it recently before updating, but my description is still there. I do agree all the formatting signs are shown (and newlines are gone), but I have seen that before in profiles. I agree it's annoying that formatting code isn't applied in the app.

**Comment by shiregray** [comment]
Ah, yeah. I have about 6 paragraphs after header 1 and header 2. Below that is a line break, and everything below THAT is missing. I've cross-referenced with the desktop version (momentary panic), but it's all still there.

**Comment by flgnl** [comment]
In my experience, most longer profile texts have always been 'cropped' in the app. But if yours was longer before, that's probably an unintended issue.

**Comment by shiregray** [comment]
If anyone cares to reference, user "jezebelvane." 

My profile with this current release reads: "# DICK'N' AND POLITIC'N' --- ### Intellect is the biggest turn on" ... And that's it.

**Comment by kistitan** [comment]
Should be fixed for a while so closing this :)

Please feel free to reopen if it would occur again.
