### ISSUE TITLE
Line Breaks Entered In Private Message Box Don't Wind Up Sending

### ISSUE THREAD

**Issue by kdom13** [fetlife/android#472]
Android 8.0 on Google Pixel, FetLife v2.16.4

Line
Breaks

Entered

Any of these ways

do not show up in the final message posted to the private conversation.

**Comment by kistitan** [comment]
Thanks for reporting, we are on it!

**Comment by kdom13** [comment]
Glad to help =)

**Comment by kistitan** [comment]
Hey there,
This one should be fixed in 2.16.7.

Please reopen it if you see the issue again.

Thank you!
