### ISSUE TITLE
No line breaks in group posts 

### ISSUE THREAD

**Issue by flgnl** [fetlife/android#473]
All line breaks seem to be missing in group posts. Saves space, but makes them harder to read. Especially, it makes it impossible to see where a quote ends and regular text continues.

2.16.4

**Comment by FernandoMiguel** [comment]
bios are also broken

**Comment by FernandoMiguel** [comment]
sounds like dupe of 
https://github.com/fetlife/android/issues/472

**Comment by flgnl** [comment]
Or related anyway.

**Comment by flgnl** [comment]
Fixed in the new version I see!

**Comment by kistitan** [comment]
Hey there,
This one should be fixed in 2.16.7.

Please reopen it if you see the issue again.

Thank you!
