### ISSUE TITLE
New version available_ and then what?

### ISSUE THREAD

**Issue by jidanni** [fetlife/android#475]
2.16.0 just says New version available.

Nobody remembers what one has to do to get the new version, so it should please help them with a next step.

**Comment by ImperfMage** [comment]
it should say in your notifications that if you want to install the latests (once you check to see if there is an update)

**Comment by kistitan** [comment]
@jidanni @ImperfMage 

Thanks for reporting this issue.
In theory clicking on the notification should start the update process.
Isn't it the case for you?

**Comment by jidanni** [comment]
Well whatever I report here always has to do with the previous edition
before I clicked anything/much. ... so I will just have to take your
word for it.
