### ISSUE TITLE
Why can't the app be in the Play Store?

### ISSUE THREAD

**Issue by Jake-Mok-Nelson** [fetlife/android#476]
Hey, guys,

Very sorry if this has been asked before, I've browsed the issues and only seen some passing comments to the app not being allowed in the Google Play Store.

What I want to understand is **why** it isn't allowed and which condition does it breach in the [terms of service](https://play.google.com/about/play-terms.html)?

Can you guys please help me understand exactly why it's blocked?

**Comment by malachid** [comment]
The previous app was in the play store, with adult content selected. When Google started doing the Google Play for Education, they started banning those apps. They contacted us and told us that the app was now prohibited and that attempting to republish it with connections to the FetLife website would result in having our Google account deleted. MiKandi reached out to us and offered to host it for us, which they did for quite some time.

Although this app is by BitLove proper, it would still have the same limitations imposed by Google.

**Comment by Jake-Mok-Nelson** [comment]
Interesting. I don't see what makes the app different from Tinder, Grindr, or any of those other social apps that CAN contain adult content but thanks for explaining it to me @malachid

**Comment by FernandoMiguel** [comment]
Expecting Google policies to make sense is an illusion

**Comment by kistitan** [comment]
@Jake-Mok-Nelson 

The big difference from Tinder, Grindr, is the policy for user content.
In those app you are not allowed to have explicit sexual content within public content.
Also they have pre-approve policy.

Changing FetLife in this direction would change the very core user experience and FetLife would not be anymore what it is today.

We still did not give up to improve our install/update experience, so hopefully in the future we will reach the state when it won't be that annoying not being in the play sores.
