### ISSUE TITLE
2.17.6 upgrade failure: Parse error: There was a problem parsing the package

### ISSUE THREAD

**Issue by malachid** [fetlife/android#483]
On my LG v20 running 8.0, the upgrade went fine.

On my Nexus 10 running 5.1.1, the upgrade failed to install with "Parse error: There was a problem parsing the package"

This is all I see in logcat:
```
09-14 11:05:01.989 I/PackageManager(  411): Setting last chosen activity com.android.packageinstaller/.PackageInstallerActivity for user 0:
09-14 11:05:01.989 I/PackageManager(  411):   Action: "android.intent.action.VIEW"
09-14 11:05:01.989 I/PackageManager(  411):   Category: "android.intent.category.DEFAULT"
09-14 11:05:01.990 I/PackageManager(  411):   Type: "application/vnd.android.package-archive"
09-14 11:05:01.994 I/ActivityManager(  411): START u0 {act=android.intent.action.VIEW dat=file:///storage/emulated/0/Download/fetlife-2.17.6.apk typ=application/vnd.android.package-archive flg=0x17000000 cmp=com.android.packageinstaller/.PackageInstallerActivity} from uid 10092 on display 0
09-14 11:05:02.088 I/ActivityManager(  411): Start proc 11068:com.android.packageinstaller/u0a43 for activity com.android.packageinstaller/.PackageInstallerActivity
09-14 11:05:02.235 W/PackageInstaller(11068): Parse error when parsing manifest. Discontinuing installation
```

**Comment by adkins17** [comment]
@Malachid, I just tried the link and am getting the same message on my
Galaxy S6.

**Comment by malachid** [comment]
@kistitan yes same error downloading directly from github.

**Comment by DevN1mr0d** [comment]
Probably the same error on Nokia, I have not checked logcat. Reinstalling last stable from github

**Comment by kistitan** [comment]
@adkins17 @DevN1mr0d 
Would you mind helping us out with your OS version?

It seems this issue occurs only on certain versions.

Thank you

**Comment by DevN1mr0d** [comment]
@kistitan I have Android 8.0 running.

**Comment by adkins17** [comment]
I am running Android 5.0.2 on my Galaxy S6.

**Comment by kistitan** [comment]
Can you all please try the fixed version?

https://github.com/fetlife/android/releases/download/v2.17.11/fetlife-2.17.11.apk

**Comment by malachid** [comment]
That one works.

Note that I apparently had avast installed on that device, and it popped up saying FetLife has been reported as a suspicious app.

**Comment by DevN1mr0d** [comment]
On Nokia 3 with Android 8.0 I had 2.6.17 downloaded from Fet, logged out, cleared cache and uninstalled. Installed 2.7.11 from Git, now I am logged in, unable to check messages but showing properly who sent me what and when. 
On Lenovo tablet with Android 5.0, no previous install of Fet (maybe there was a long time ago), Git version install first attempt stated it failed and made another app to crash. Then it went successfully with the second attempt, no reminder popup on new version.
Checking logcat...

**Comment by adkins17** [comment]
Works great now, thank you.

**Comment by kistitan** [comment]
Thanks for lettng us know it works now.
Closing the issue.

**Comment by cladmi** [comment]
Both versions also have the same parsing error on Android 4.2.2.
Should I open a dedicated issue or stay in this one?
