### ISSUE TITLE
Android notifications not opening app

### ISSUE THREAD

**Issue by ntysecrets** [fetlife/android#484]
Loving the new look btw!! 

Clicking notification bar items aren't opening the app..

**Comment by kistitan** [comment]
Thank you for reporting this issue.
We are working on it and keep you updated.

We are happy you like the new design :)

**Comment by kistitan** [comment]
Hey guys, does it work with 2.17.13?

**Comment by ntysecrets** [comment]
Yes.. It seemed to work fine on 13

**Comment by kistitan** [comment]
@ntysecrets 

I am sorry I am not sure if I understood correctly.
You are saying 2.17.13 works only with kindle fire 7 but it does not work with your Android 8 device?
Or now it works with both?

thank you

**Comment by ntysecrets** [comment]
Fire os 5.6.2.0 = android 5.0. 
Fetlife 2.17.13 - receives notifications and selecting notifications launches the app to appropriate selection. All works correctly so far.

Android 8 on LG G6 with Sept 2018 security patch
Fetlife 2.17.13 - selecting received notifications will not launch app. Notifications haven't worked properly since the switch to bottom bar in fetlife app. Last working fetlife version was 2.16.7.

**Comment by ntysecrets** [comment]
I decided to try a complete uninstall of fetlife app and reinstall of 2.17.13 on LG g6 with android 8.0. Seems to have tentatively fixed notifications.

**Comment by kistitan** [comment]
Thanks for all the information.
I am happy it fixed. 

Closing for now.
Please feel free to reopen if it occured again.
