### ISSUE TITLE
no notification in beta

### ISSUE THREAD

**Issue by FernandoMiguel** [fetlife/android#486]
v2.17.6 isnt showing notifications on android P
i get an occasional toast about issue with Channel

**Comment by kistitan** [comment]
hi @FernandoMiguel ,

Thank you for reporting it.
I have been trying to reproduce it, no luck so far.

I keep you updated.

**Comment by kistitan** [comment]
Does it work with 2.17.13?

**Comment by pervertable** [comment]
I'm experiencing the same thing since installing 2.17.5 a few days ago. I'm not seeing an option to update beyond that version, even though I've run "Check for Updates" several times.

**Comment by kistitan** [comment]
@pervertable 

Can you please try with this link?

https://github.com/fetlife/android/releases/download/v2.17.13/fetlife-2.17.13.apk

**Comment by pervertable** [comment]
Hi kistitan,
Yes, that seems to have fixed it. Thank you very much!

**Comment by kistitan** [comment]
Thanks for letting u know.
