### ISSUE TITLE
persistent notification

### ISSUE THREAD

**Issue by FernandoMiguel** [fetlife/android#487]
in the new v2.17.6, the bar moved to the bottom... dont dislike it
but, now notifications are always there, even after you see them...
so i have a few friend requests (that i dont want to refuse), but the notification is always there
from UX pov that is bad, cause i already saw them, it should clear

**Comment by FernandoMiguel** [comment]
@johnbaku i should have been more clear.
i dont want to ignore :p 
yeah, i'm being picky

i want to keep some of those requests of easy access so i can check their profile

**Comment by johnbaku** [comment]
Sorry, the requests is not meant as a way to easily access someone's profile. It's meant as a place where you process requests so if something is not processed a counter will stay to remind you to process it.

**Comment by kistitan** [comment]
Closing as it won't be fixed

**Comment by toxik-io** [comment]
shouldn't... you still be able to click on a profile photo... from any page view?
