### ISSUE TITLE
2.17.11 unable to log in 

### ISSUE THREAD

**Issue by ImperfMage** [fetlife/android#489]
So just downloaded it from GitHub and I am unable to login , but occasionally now im getting notifications but still is showing the image provided 
http://imgur.com/a/ocvr9BL

Android version: 9

**Comment by FernandoMiguel** [comment]
I could login, but no feed would load.
Had to uninstall and revert to stable version

**Comment by kistitan** [comment]
@ImperfMage 
@FernandoMiguel 

Thank you for letting us know, we did not face any similar issues in our test devices.

@ImperfMage 
Can you go to your device's App settings and clear all Data for FetLife App?
Does it help?

Thank you

**Comment by ImperfMage** [comment]
I tried what u suggested and it does not work

**Comment by kistitan** [comment]
@ImperfMage 

Thank you, that also helps.
Invetsigating...
We will try to find solution asap.

@FernandoMiguel 
Feed not loaded as it was loading and loading without result or there was an error message or crash?
Did the other part of the app work?

**Comment by FernandoMiguel** [comment]
@kistitan no errors. just blank feed.
messages and notifications didnt show either.

for now, i've reverted to stable version

**Comment by kistitan** [comment]
Hey guys,

Can you please try this version?

https://github.com/fetlife/android/releases/download/v2.17.13/fetlife-2.17.13.apk

**Comment by ImperfMage** [comment]
It works on my end :)

**Comment by hxcde** [comment]
Had the same error. Uninstalling and reinstalling the 2.17.13 Version fixed the problem.

**Comment by kistitan** [comment]
Thnaks for letting us know.
Closing this issue
