### ISSUE TITLE
No "say it" button for writing comments in the app

### ISSUE THREAD

**Issue by flgnl** [fetlife/android#490]
When I open a writing in the app want to leave a comment at the bottom, the text field is there but the button to post my comment is missing.

When I reply to an existing comment, the button is there.

**Comment by FernandoMiguel** [comment]
AH i knew i forgot to file a bug
thanks for doing it.

the new beta moved to webviews, but the post button is missing

**Comment by flgnl** [comment]
You're welcome. :-)

**Comment by kistitan** [comment]
Hi all,

Comments in the App is not yet supported unfortunately.
Writings appear in the as a webview only as a preview. 
In the stable release it will be released for now as it used to be, a native screen with no comment area.

When we get there and release the writings as webview, we will make sure that the comment field is working.
But thanks for letting us know, it is still useful :)

**Comment by flgnl** [comment]
Just some feedback on this. Would have been nice to actually know this. Does this mean that comments to comments I (may have) posted in the app haven't been published?

Also, in the old version, I at least had a quick way to get to the writing in the browser to comment there. Now I have to get there using a roundabout way.

I will be reconsidering using beta versions. I don't mind giving feedback on new functionality, but for that, in my opinion, the new functionality has to actually be functional and not halfway implemented. I'd call this something for an alfa release.

Like the basically useless alpha release of the 3.x version of the app. In which content didn't even update. It just kept showing the same stuff.

**Comment by flgnl** [comment]
Reinstalled 2.16.7 and disabled the preview release notifications.

Sorry, but I use this app on a daily basis. Preview releases with reduced functionality are just not worth it for me.

**Comment by FernandoMiguel** [comment]
I will agree it's quite frustrating to have the post in the app an no quick way to reply.
In the beta, you can't even open the post in the browser

**Comment by flgnl** [comment]
So now there is a new production release, with webview writings and subcomments working, but this issue hasn't been fixed yet.
