### ISSUE TITLE
V2.17.5 failure 

### ISSUE THREAD

**Issue by AldathaTe** [fetlife/android#491]
Since updating to this version the app won't do anything. No new messages, no access to any other screen... however, I do get persistent pop-up notifications. Even if I open the app independently and try to access my messages... nada. Even allowing it to load for 3 min still left just the circular loading icon.

**Comment by johnbaku** [comment]
@kistitan mind looking into this please?

**Comment by kistitan** [comment]
@AldathaTe 
Mind trying 2.17.13?

https://github.com/fetlife/android/releases/download/v2.17.13/fetlife-2.17.13.apk

**Comment by AldathaTe** [comment]
I tried updating but it won't do anything but show me the continuously
turning circle... should I try uninstalling and reinstalling it?

Thanks for looking into it.
Vanessa (AldathaTe)

**Comment by kistitan** [comment]
@AldathaTe 

We did not encounter any similar issues with our test devices.
Would you mind go to your device's settings > apps > FetLife > Storage and there clear all data.
After that you should login again.
Please let me know if it works afterwards.

Thank you and sorry for the inconveniences

**Comment by kistitan** [comment]
Closing this issue now, please reopen it if installation would be still not possible or you would facing issue with the latest versions too.

Thank you
