### ISSUE TITLE
Fetlife not working on Android phone while on data 

### ISSUE THREAD

**Issue by BleachNirvana** [fetlife/android#495]
I'm using a Samsung Galaxy S5 Neo and while I'm on WIFI Fetlife works without issue on the app and on my browser but when I try to access it while I'm using data the website won't load and just tells me the site can't be reached and to check my connection. I've searched for hours online but have failed to find any solution. The second I connect back to WIFI it works instantly.

**Comment by kistitan** [comment]
@BleachNirvana 
Closing this issue for now, hoping you managed to solve it with the network operator. 

Please get back to us if it is not the case.
