### ISSUE TITLE
[API] Returned events data, returned by the API is not aligned with backend data

### ISSUE THREAD

**Issue by kistitan** [fetlife/android#497]
Merging two issues here:

Events not showing up on Map
Events showing up at a wrong address on the Map

Both issues are backend/API issues and need to be fixed by backend developer.
This issue is kept open here only to notify reporting user in case of the issues have been fixed.
Internal bug cards have been opened.

Otherwise nothing to do at client side.

**Comment by kistitan** [comment]
See more at:
https://github.com/fetlife/android/issues/432
and

**Comment by markusb** [comment]
Just to confirm a new occurrence of this phenomena. I added the dates for a munch today (12 dates, one event per date). Of the 12 munches only 9 show up in the mobile app. All are identical except for the date.

**Comment by kistitan** [comment]
@markusb 
Just as a headup, we added this issue to our backend issues queue.
Waiting for backend team to get there.

**Comment by kistitan** [comment]
Hi all,

Finally our server team found an issue and fixed it.
Can you please confirm the issues solved or we should look further?

Thanks a lot.

**Comment by kistitan** [comment]
Closing this for now, please feel free to reopen if the issue was still there.

Thank you
