### ISSUE TITLE
Scrolling upwards in writing comments sometimes difficult 

### ISSUE THREAD

**Issue by flgnl** [fetlife/android#498]
When trying to scroll upwards in the comments underneath a webview writing within the app (so in the direction of the writing) I sometimes get a refresh icon like a spinning circle and the scrolling doesn't work.

I can't reproduce this consistently. I now opened the same writing three times. The first time I got this issue a lot. Maybe managed to scroll upwards in one out of three attempts or even less. The other two times scrolling worked without any issues.

**Comment by kistitan** [comment]
Hey @flgnl,

Thanks for reporting this issue.
May I ask which version do you use?

Writing webview page has several issues, and will be removed from the App temporary until all the issues has been fixed. (In theory it should not be there already in the latest version.)

**Comment by flgnl** [comment]
As far as I can tell I'm using the latest preview version. 2.17.15? That's what the release notes say.

Writings from loves in my feed and from profiles open in web view within the app. Comment links open in my browser.

**Comment by kistitan** [comment]
Thanks for the update.
We are going to make it sure, that webview writings are out until they properly functioning.

**Comment by flgnl** [comment]
I just noticed, when I open a writing from a love, I get the web view version. Then when I hit back, I get the old, native app version. Another back gets me back to my feed.

**Comment by FernandoMiguel** [comment]
@flgnl i see the same. i'm sure it's a bug, but sometimes it can be useful. i find the reading better in that mode

**Comment by kistitan** [comment]
Yes it is a bug.
We released the new webview version, but than we found some issues, that need some time to fix on the web side, so it got revoked, and now indeed cause this issue.
Will be fixed in the next version.

**Comment by kistitan** [comment]
Issues should be fixed, please feel free to reopen if it wasn't the case
