### ISSUE TITLE
Option to use conventional Android navigation

### ISSUE THREAD

**Issue by jcogilvie** [fetlife/android#499]
Would love to be able to have standard top left nav hamburger as in prior versions so I don't have to relearn platform UX for this app.

**Comment by kistitan** [comment]
@jcogilvie 

I am sorry that our new design caused inconveniences.
We are trying to follow the latest guidelines and trends.

Personalization would be nice, so each user could have their own UX, and we would like to have it one day, but I have to confess it is far on our Todo list.

Thanks for your understandings
