### ISSUE TITLE
2.17.15 - My Events not populating.

### ISSUE THREAD

**Issue by matthewsir** [fetlife/android#500]
Once again, I am getting the server could not be reached error message when trying to get my list of events to populate.   I have cleared all data and uninstalled the app multiple times and nothing works.   

This seems to be a hit or miss function and is what I use the app for the most.

**Comment by kistitan** [comment]
hey @matthewsir 

We do not see anything from our side, so would you mind installing the attached debug version of the App (you should rename the attached .zip file to .apk to be able to install it)?
It will produce extra logs that can help us to see more what's happening on your device.

After reproducing the issue you can find the extra log file on your device:
/sdcard/Android/data/package.name/files/extra.log

Please send it in email to: krisztian@fetlife.com

Thank you

[fetlife-2.17.15_debug.zip](https://github.com/fetlife/android/files/2550293/fetlife-2.17.15_debug.zip)

**Comment by nielsenramon** [comment]
Archiving this issue for now. Please let us know if you encounter this issue again!
