### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by tb116** [fetlife/android#503]
I have a galaxy s5 and had to do a factory reset on it. I had the app downloaded prior to the reset and had no issue downloading it. After doing the reset I am getting a parse error and can't figure out how to fix it. I have enabled third party app downloads. Turned off any Antivirus software on the device. Downloaded the apk file numerous times to make sure I didn't get a corrupt version. I don't know what to do at this point. Any tips?

**Comment by tb116** [comment]
On android 4.4.2 which is what I was on before doing the reset

**Comment by kistitan** [comment]
@tb116 

Thanks for reporting this issue.
Latest FetLife App releases do not support OS versions below 5.0 for security reasons.

You can download the latest version available for 4.4.2 via this link:

https://github.com/fetlife/android/releases/download/v2.16.7/fetlife-2.16.7.apk

Thank you for your understandings.

**Comment by tb116** [comment]
No thank you. Spent 2 weeks and couldn't figure it out. That makes sense why the updates didn't seem to work before I reset my phone. Thank you very much

**Comment by kistitan** [comment]
To install FetLife App on device with OS version below 5.0:

1. download this file [fetlife-2.16.7.zip](https://github.com/fetlife/android/files/2624852/fetlife-2.16.7.zip)
2. rename it from fetlife-2.16.7.zip to [fetlife-2.16.7.apk (after downloading it should be in your downloads folder)
3. tab on the renamed file in your file manager
4. follow the installation instructions that appear

**Comment by essence-of-orange** [comment]
Not sure if this is outdated, but this solution doesn't work for me in Android 4.2.2 on HTC Desire 310

**Comment by essence-of-orange** [comment]
Just to be clear, is this part of the readme correct:

"Latest stable version supporting older **OS version is 2.16.7** Please see our installation instructions"

Or this:

"You can download the latest version **available for 4.4.2** via this link"

**Comment by beatnickgr** [comment]
I got an android 4.3, and at the bottom of [this page](https://fetlife.com/android#instructions) it says it should work on Android 4.0.3 or newer.
So why should we have 5.0 when only 4.0.3 is requested?

**Comment by kistitan** [comment]
Hi @beatnickgr 

Unfortunately both for security and technical reasons we had cut off supporting Android OS version below 5.0.
However as you pointed out, we forgot to update our Android page.
I am sorry this confusion. 

However if you are willing to use the FetLife Android App on your device you can still do it with our last stable version as described above, however if you do so please keep in mind, that we cannot provide support for that version any more.

Thank you for your understandings
