### ISSUE TITLE
Messages synchronisation - Autorefresh

### ISSUE THREAD

**Issue by islasstanis** [fetlife/android#504]
Hi,

When I'm talking to a user who uses the Android App and me on a Laptop/Desktop using a browser, I see the incoming message notification (Up right and the Inbox) but no auto-refresh on the conversation itself.

I can see the messages again if I refresh manually (F5, CTRL+R...) or I re-click on the conversation in the Inbox.

I don't have this issue with same people if they use the website instead of the Android App.

Best regards.

**Comment by kistitan** [comment]
@islasstanis 

Thanks for reporting this issue.

I will let our Desktop App developers know about the issue.

**Comment by kistitan** [comment]
Hi @islasstanis 

Just a quick head up, we are going to replace the conversations screens in Android very soon and that will help to get rid of this issue once and for all.

Thanks a lot for your help and patience.
Dreamlite

**Comment by islasstanis** [comment]
Hi,

Thank you for the reply, very nice to see a follow up !

Best regards.

**Comment by kistitan** [comment]
Hey @islasstanis ,

We have just released the new webview based conversation screen in 3.0.0 beta, that should solve the issue above.

If that was not the case, please feel free to reopen this issue.

Thanks again
Dreamlite
