### ISSUE TITLE
Error on notification 

### ISSUE THREAD

**Issue by FernandoMiguel** [fetlife/android#505]
![screenshot_20181127-173230](https://user-images.githubusercontent.com/168366/49100126-0ee34d00-f26b-11e8-8a13-6a37739dcb27.png)
The just released new version mentions changes to notifications 
Seems its broken 
I get this balloon at the bottom for each interaction with the backend server

**Comment by kistitan** [comment]
@FernandoMiguel 

Thanks for reporting this issue.
We are investigating it.

**Comment by FernandoMiguel** [comment]
![screenshot_20181220-161329](https://user-images.githubusercontent.com/168366/50296391-51ff9d00-0472-11e9-9003-18bcb98c0261.png)

**Comment by kistitan** [comment]
@FernandoMiguel 
Thanks for the info.

That is new enough.

If you go to 
Device Settings > Apps > FetLife > Notifications

What channels do you see there?

**Comment by FernandoMiguel** [comment]
![screenshot_20181220-191025](https://user-images.githubusercontent.com/168366/50305512-f392e880-048a-11e9-8999-a40709e88b5c.png)

I'll uninstall and install again

**Comment by FernandoMiguel** [comment]
Freshly installed and still showing the pop-up on any love, update, or message received

**Comment by FernandoMiguel** [comment]
![screenshot_20181221-085508](https://user-images.githubusercontent.com/168366/50333849-7b660a80-04fe-11e9-8923-58264cbca2d5.png)
![screenshot_20181221-085613](https://user-images.githubusercontent.com/168366/50333855-7f922800-04fe-11e9-97e9-5b51ac730124.png)
Even after clearing data, on the first time I open the app, you can see in the bottom (bad timing) a bit of the pop up showing up before I even login

**Comment by FernandoMiguel** [comment]
![screenshot_20181221-085508](https://user-images.githubusercontent.com/168366/50333988-d1d34900-04fe-11e9-9bf0-2dbaf1850c51.png)
![1188276469](https://user-images.githubusercontent.com/168366/50333995-d7309380-04fe-11e9-9cd6-1012d68a900d.png)
Even after clearing data, on the first time I open the app, you can see in the bottom (bad timing) a bit of the pop up showing up before I even login

**Comment by kistitan** [comment]
@FernandoMiguel 

If it appears already on the logon screen, than unfortunately it really does not come from our App, so we cannot do much about it on code level, however we can still try to help to investigate.

I know the package name is there, but it can be misleading. 
Like the same issue appears if you test on emulator with Android 9, but without Google Play app, as the system tries to send you an update needed notification.

I assume you do have Google Play Store App, right?
Can you maybe try to update it?

**Comment by FernandoMiguel** [comment]
This is a pixel 2XL with latest android version.
No root, no weird stuff.
Just vanilla (pun intended) experience

**Comment by FernandoMiguel** [comment]
I've never seen this pop up on any other apps, FYI

**Comment by kistitan** [comment]
Thanks for the contribution.

We indeed did not send explicit notification, but from Android O foreground services require to have notifications, that possible the reason for that message.

We change our service to be a background service and add a JobScheduler.
It is anyway a better solution.

Will have the update soon.

thanks for your help and patience

**Comment by kistitan** [comment]
@FernandoMiguel 
Fix is released.

Sorry for the inconveniences and thanks for keeping up

**Comment by FernandoMiguel** [comment]
Confirmed fixed.
Thanks
