### ISSUE TITLE
Update to preview goes endless loop

### ISSUE THREAD

**Issue by DevN1mr0d** [fetlife/android#506]
Update from 2.18.0 to preview version goes to endless loop. Now for 24 minutes I can see the notification that version downloading. App info telling the same. Nokia 3 with Android 8.0.

Let me know where to look in logcat logs for further info :)

Update
Closing the app and opening the downloaded file - it actually downloads but no completion message - works to install. Just the installer keeps running in App Switcher then even after the installation is done and tapped on ' Done '

**Comment by kistitan** [comment]
@DevN1mr0d 

Thanks for reporting this issue, unfortunately the installer is out of our hand.
So if you open the downloaded file and the installer does not stop after installation, that we cannot do much about :(

The endless notification of downloading can be related to our code.
We rely on the device's download manager.
If it does not give us the signal that the download is finished we cannot remove the notification.

I will double check our code if there is any bug that might end up keeping the notification on even if we get the "donwloaded" signal

**Comment by nielsenramon** [comment]
If someone encounters this issue, please let us know and reopen the issue.
