### ISSUE TITLE
Group comment notifications crash the app. 

### ISSUE THREAD

**Issue by flgnl** [fetlife/android#507]
Preview version 2.19.0

When I go to the app notifications and tap on a group comment notification, the app crashes.

**Comment by kistitan** [comment]
@flgnl 

Thanks for reporting this issue.
We are investigating it.

**Comment by flgnl** [comment]
Hitting the plus icon in the notifications screen (no idea why that is there) also crashes the app.

**Comment by DevN1mr0d** [comment]
I will check later if I can reproduce on my device and that I can find something in logs

**Comment by DevN1mr0d** [comment]
I could not reproduce it.

**Comment by flgnl** [comment]
It had been fixed in 2.19.2

**Comment by kistitan** [comment]
Indeed it should be fixed in 2.19.2
