### ISSUE TITLE
Infinite update loop

### ISSUE THREAD

**Issue by calvinwiii** [fetlife/android#508]
Latest update hung on load. Now detects a new version. Instantly says the update is ready. Then when install is ok'd says version 2.19.0 cannot be opened.

**Comment by kistitan** [comment]
@calvinwiii 
Our newest version is 2.19.2.

We did two update close to each other, so it might happen, that by the time you opened the notification about 2.19.0 there was already a new one and the old one was not available.

Can you please try to download 2.19.2?

https://github.com/fetlife/android/releases/download/v2.19.2/fetlife-2.19.2.apk

Thank you

**Comment by kistitan** [comment]
Closing this for now, please reopen if the issue still occured after the next version
