### ISSUE TITLE
Update is not installing

### ISSUE THREAD

**Issue by DevN1mr0d** [fetlife/android#509]
The new preview version 2.19.2 notification appears in stable app, downloads but when states that ready to install then installation does not starts. Seems like the command to install being interrupted in the background, app is not updated to new version.

**Comment by DevN1mr0d** [comment]
Logcat log:

12-06 01:03:16.825   900  2092 I ActivityManager: START u0 {cmp=com.bitlove.fetlife/.view.screen.standalone.SettingsActivity} from uid 10246
12-06 01:03:16.905   900  2092 I WindowManager: Relayout Window{9fe653a u0 com.bitlove.fetlife/com.bitlove.fetlife.view.screen.standalone.SettingsActivity}: oldVis=4 newVis=0 focusMayChange = true
12-06 01:03:24.338   900  6662 I WindowManager: Relayout Window{da5ca3d u0 com.bitlove.fetlife/com.bitlove.fetlife.view.screen.resource.TurboLinksViewActivity}: oldVis=8 newVis=0 focusMayChange = true
12-06 01:03:28.410   900   986 I WindowManager: Failed to capture screenshot of Token{6386ce8 ActivityRecord{5b960b u0 com.bitlove.fetlife/.view.screen.resource.TurboLinksViewActivity t2532}} appWin=Window{da5ca3d u0 com.bitlove.fetlife/com.bitlove.fetlife.view.screen.resource.TurboLinksViewActivity EXITING} drawState=4
12-06 01:03:30.762   900  4626 I ActivityManager: Killing 28472:com.google.android.gm/u0a129 (adj 906): empty #17
12-06 01:03:30.763   900  4626 I ActivityManager: Killing 29969:com.google.android.apps.maps/u0a143 (adj 906): empty #18
12-06 01:03:30.764   900  4626 I ActivityManager: Killing 29695:com.evenwell.UsageStatsLogReceiver/1000 (adj 906): empty #19
12-06 01:03:30.772   900  4626 I ActivityManager: Killing 29199:com.bitlove.fetlife/u0a246 (adj 902): remove task
12-06 01:03:30.776   900  4626 I ActivityManager: Killing 29268:com.android.chrome:sandboxed_process0/u0a246i617 (adj 900): remove task
12-06 01:03:30.876   900  4626 W ActivityManager: Scheduling restart of crashed service com.bitlove.fetlife/org.chromium.content.app.SandboxedProcessService0 in 1000ms
12-06 01:03:30.991   900  2087 I WindowManager: WIN DEATH: Window{6b365cc u0 com.bitlove.fetlife/com.bitlove.fetlife.view.screen.resource.TurboLinksViewActivity}
12-06 01:03:30.993   900  1091 E ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ LISTEN id=1781, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND] ]

**Comment by kistitan** [comment]
@DevN1mr0d 

Thanks for letting us know about the issue and the information.
I can confirm that the apk is a valid apk for OS versions 5.0 and app.
Unfortunately the installation process is our of our hand do if the apk does not install we cannot do much about it.
Maybe you can try to download again, to be sure it did not get corrupted during download.

If you are using device with OS version below 5.0, please check out our legacy support version:
https://github.com/fetlife/android/issues/503

**Comment by DevN1mr0d** [comment]
@kistitan 
It was actually on Android 8.0
Manually downloaded from Git and installed, no errors that way.
