### ISSUE TITLE
updating issues - Connection failed, Please try again later.

### ISSUE THREAD

**Issue by adkins17** [fetlife/android#510]
when a new version is released, I am being notified when I open the app... but under 'About Install' when I click on the update link, it is producing the error about connection failed.

**Comment by kistitan** [comment]
@adkins17 

Thanks for letting us know.
We are able to reproduce it.
Working on it.

**Comment by ImperfMage** [comment]
Any update on this ?

**Comment by kistitan** [comment]
@adkins17 @ImperfMage 
This issue should bi fixed since 2.19.7.

Please use this link to install the latest version for now:

https://github.com/fetlife/android/releases/download/v2.20.0/fetlife-2.20.0.apk

Please feel free to reopen this issue if it occurred again.

Thank you
