### ISSUE TITLE
Latest release has some issues. 

### ISSUE THREAD

**Issue by Merseygeek** [fetlife/android#512]
Before I begin, I do have screenshots if needed, and happy to email the coders. 

Issue 1: When checking the 'update settings' option, the tick box for Android notification of a new message is not available, only the email one is available. 

Issue 2: there is some overlapping of options, wording and other things, making it a tad difficult to navigate. 

Both issues I mentioned have screenshots for them, and the screenshot will show what my issues mean.

**Comment by kistitan** [comment]
@Merseygeek 

Thanks a lot for letting us know.
In the meanwhile we fix the issue you can still use the website settings.

Please send us the screenshot to : 
krisztian@fetlife.com

Thanks a lot

**Comment by kistitan** [comment]
Thei issue should be fixed, please feel free to repoen if it wasn't the case.

**Comment by Merseygeek** [comment]
Thanks for the update


Having issues with app 2.23.5, screenshot is added to this email.

The issue is that when release notes is tapped , it lingers and doesn't show any information.
[Image]




Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by kistitan** [comment]
@Merseygeek 

Sorry for the late reply.
Please feel free to reopen the issue next time if you think it was not fixed.

However it seems the issue you mentioned in your last message was different than the original ones, so to be able to target the current issues properly, 

can you please double check if any of the following issues are still happening;
- No checkbox at update settings
- Overlapping wording
- Release notes doe snot open

Thanks a lot for your help

**Comment by kistitan** [comment]
@Merseygeek 

A new version, 3.0.0-beta.2 is out, so you might want to try with that too..

**Comment by FernandoMiguel** [comment]
@kistitan the new release is missing release notes

**Comment by kistitan** [comment]
@FernandoMiguel 

Thanks you, good catch, 
We will make sure to add in the next version.

Temporarily you can see the release notes here: 

https://github.com/fetlife/android/releases/tag/v3.0.0-beta.2

**Comment by kistitan** [comment]
Closing this issue now due to inactivity and recent changes, that probably solved the original issues
Please feel free to reopen this issue if it would occur again.
