### ISSUE TITLE
Difficult to swipe

### ISSUE THREAD

**Issue by malachid** [fetlife/android#513]
I realized that the app was failing to update beyond 2.18 so manually updated it to 2.20.2.

When swiping through a profile, it seems to keep getting stuck requiring multiple attempts to get it to respond. For example when trying to swipe left from status tab, it took about a dozen tries before it responded.

I usually swipe in the content area. I think the red header is ok, but the content area on that tab seems to lose the listener.

**Comment by FernandoMiguel** [comment]
I experience the same.
Somehow, I think it used to be better before. 

The read header always works

**Comment by kistitan** [comment]
@malachid @FernandoMiguel 

Sorry for the late reply.
We could not reproduce the actual issue, but we are aware of that profile screen is a bit poorly designed.
It triggers to many unnecessary network request during swiping, what can end up having too many requests in short amount of time.

In the next version we are going to improve the design so hopefully we won't have that many issue with the network connection.

**Comment by adkins17** [comment]
I was experiencing the same problem... trying to scroll up and down on
profiles... when I tried to scroll up, by swiping down, it would bring up
the reload icon instead.

**Comment by FernandoMiguel** [comment]
The latest version  v2.21.20
Lost the ENTIRE ability to swipe between panes. 

Please revert

**Comment by kistitan** [comment]
Did some update on the profile screen, also added back the swipe functionality, however, keep in mind, swiping through the profile screens might and up more data load, that actually needed.

This was one of the reason we added the swipeable headers so users do not need to download and sipe through pages they do not really need.

Please reopen this issue, if any of the issues above is still there.
