### ISSUE TITLE
Messages available after deletion

### ISSUE THREAD

**Issue by DevN1mr0d** [fetlife/android#516]
Maybe it will be a won't fix issue but just noticed that after I deleted some private messages on desktop then a couple of them still available on the app.
When trying to view the deleted message it opens it with a pop-up message that connection fails.
Have to add that only those messages remained in the application that originally sent from it instead of desktop.
Application version is 2.19.2

I did not tried to clean cache so I can reproduce error message.

**Comment by kistitan** [comment]
Hi @DevN1mr0d ,


Thanks for reaching to us with this issue.

By message you mean converstions?
Did you try the to use pull to refresh in the conversations screen?

**Comment by DevN1mr0d** [comment]
Yes @kistitan I meant Conversations.
If you are referring to when scrolling over the top the reload the conversations then yes I did tried it. I shows the red loading circle but then deleted Conversations are still present.

**Comment by kistitan** [comment]
@DevN1mr0d 

Sorry for the late reply.
Do I understand correctly that you started a conversation no reply came in, than you deleted a conversation and it is still in the App?

If this is the case than it is unfortuantelly a known issue, that needs arhitectural change that we did not find yet.
The reason behind is that the website handles started but not answered conversations the same as archived conversations so you cannot see them at your inbox.
However at the App, this concept was not very intuitive, so we save started message separately until they are answered and we do not sync them with the server.

This issue will be gone as soon as we start using webviews for inbox too.
For the time being you can reset your local user data, in the App settings.
That will make the extra conversations go away.

Thanks for your understandings.

**Comment by DevN1mr0d** [comment]
@kistitan 
Thanks, your understanding is correct and your suggestion solved the issue. However in addition I also had to clean the application cache on Android level (outside app) as kept logging me out every time that I switched to another application.

**Comment by kistitan** [comment]
@DevN1mr0d 
Thanks for the update.
I close this issue now, as we are going to replace the whole conversations screen soon, but we have a different issue tracker for that story.

Thanks again
