### ISSUE TITLE
V2.21.0 new profile screen issues

### ISSUE THREAD

**Issue by ntysecrets** [fetlife/android#518]
Friend/follow options, profile topics content, etc don't load properly until visit web version then go back.

**Comment by kingstongrafix** [comment]
Yeah going to people's profile, each tab doesn't refresh immediately. You need to click on another tab then return and it refreshes.
Like if you go to the photos tab nothing appears, then click on the videos tab and go back to photos, and then they appear. 
Please fix.

**Comment by MasterA6** [comment]
I get the same issue. Running Android 6.0.1
Fetlife app version v2.21.0

**Comment by ntysecrets** [comment]
Thanks.. yall do great work!!

**Comment by MasterA6** [comment]
I loaded the latest stable version and this is fixed. Thank you.

**Comment by kistitan** [comment]
Yes, fixed released in latest version.
Thanks for reporting.
