### ISSUE TITLE
App does not have an audio/LED/pull down notification for new events. 

### ISSUE THREAD

**Issue by MasterA6** [fetlife/android#519]
I get the same issue. Running Android 6.0.1
Fetlife app version v2.21.0

In my Android Settings on the app I have selected a Ringtone, a LED colour, no Vibration, Anonymous Notifications are checked along with everything below it except for Group Discussion Notifications. When I have a friend request/follow/love I do not receive an audible tone nor does the LED flash and there is no notification on the pull down on the top of the phone. All those things work for other apps and used to work for the Fetlife app but has not for the last three versions for me. Please let me know if I can provide any other information to assist.

**Comment by MasterA6** [comment]
@kistitan The latest version has fixed this issue. Thank you.

**Comment by kistitan** [comment]
Yes, indeed we found out, that anonym notifications do not work correctly.

Thanks for letting us know about.
