### ISSUE TITLE
Pre-release 2.21.20 naming issue

### ISSUE THREAD

**Issue by DevN1mr0d** [fetlife/android#520]
Title and .apk filename for pre-release 2.21.20 has been not named properly, shows 2.21.0 and application detects a new release - falsely. Guess the app notifies on the new pre-release because of some file naming issue - ie. somewhere still shows for the app that currently running 2.21.0 when actually it is already 2.21.20

On Git the tag and tree shows properly but title is the old one.
For the files zips are OK, only .apk has old naming.

**Comment by kistitan** [comment]
Merging this into https://github.com/fetlife/android/issues/517>
Please follow answer there
