### ISSUE TITLE
Custom Notification Sounds Not Working

### ISSUE THREAD

**Issue by pervertable** [fetlife/android#522]
A custom notification sound was working for me, but stopped several months ago. I run the app in a Secure Folder on a Samsung Galaxy S9, so I wondered if that was the problem. However, all the other applications in the Secure Folder work fine with custom notification sounds. 

Today, I saw someone reported the [same problem](https://fetlife.com/groups/154117/group_posts/14028491), so I'm opening this as an issue. 

I've also noticed that multiple notifications seem to want to all play the sound at once. That is, if there are multiple notifications, the default sound starts to play, then is interrupted and starts over, and then finally plays (the actual start-restart sequence might happen several times, depending on how many notifications are coming in).

**Comment by kistitan** [comment]
@pervertable 

Thanks for letting us know about this issue.
We will take look into it

**Comment by kistitan** [comment]
@pervertable 
After running tests the custom notification sounds worked on our test devices.

Do you happen to use a device with Android Oreo or later OS (8.0 or later)?
Please note, from Android Oreo, Android OS takes over the settings from the Apps for custom notification Ids.
So if you are Android O or later you can go to your device Settings -> Apps > FetLife -> Notification Settings and you there you can set the sounds for each notification channels.

(Note: we also discovered an issue on our side,  that we do not hide the notification settings for these OS versions, so it can cause a confusion.)

Please let us know

**Comment by pervertable** [comment]
Thanks for looking into this so quickly. I did make the changes in the app settings, and I now have custom notification sounds. I had no idea that could be managed from the system app settings. I am sure that is going to confuse a lot of people for a lot of apps.

However, I am still getting the "stutter." Even with a single notification, the sound starts to play, stops, then starts over and completes. This happens with both the default and the custom tones. It doesn't happen with any other applications.

**Comment by kistitan** [comment]
@pervertable 
Thank you for letting us know.

The stutter you get probably because there are several notifications (might be grouped together in your notification area) and by the default the system tries to notify you one by one.
We added changes to our code to make sure only one notification sound will be sent out in those case>

Change will available in our next release.
Thank you

please feel free to reopen this issue in case the issue occurerd again after your next App update.

**Comment by pervertable** [comment]
Hi kistitan,
Actually, before I posted, I had someone send me a single PM, to check that it wasn't the multiple notifications scenario. I should have mentioned that in my original comment. So I have confirmed that this happens when only a single notification is received.
