### ISSUE TITLE
Set navigation bar colour

### ISSUE THREAD

**Issue by aetha** [fetlife/android#524]
Hi, just asking to have the navigation bar colour set (to black) while in app. I know that stock Android sets it black anyway, but OnePlus' OxygenOS has this annoying "feature" of making it light grey by default.

![screenshot_20190301-172736](https://user-images.githubusercontent.com/3007450/53620823-77fea600-3c48-11e9-886e-4e9876a46ec0.jpg)

**Comment by kistitan** [comment]
@aetha 
Thanks for letting us know about this issue.

It will be fixed in the next version.
Please feel free to reopen if your OS would still use the not nice color after your next update.

Thanks you
Krisztian
