### ISSUE TITLE
Issues with English in the readme

### ISSUE THREAD

**Issue by Jake-Mok-Nelson** [fetlife/android#526]
Some issues with English sentences and grammar in the readme. I'd like to help out.
Some brief issues and what they should be changed to:
"Wa" = Guessing that shouldn’t be there?
"Please use also the progress flags to make it clear if your are currently working on the specific issue." = Please use flags so others know that you’re working on the issue.
"If you prefer not registering to GitHub you can still send your" = If you prefer not to register with GitHub, you can still send your 
"Want to Contribute" = Want to Contribute?
"any feedback or comment you have" =  any feedback or comments you have

**Comment by kistitan** [comment]
Hey @Jake-Mok-Nelson 

Thanks a ton for your help!
Readme is updated.

Krisztian
