### ISSUE TITLE
Connection failed. Please try again

### ISSUE THREAD

**Issue by djgg101** [fetlife/android#528]
I have been have this issue on random profile when i try to view them. Sometimes if I go to the previous page and try the profile again it works. Sometimes it doesn't

**Comment by kistitan** [comment]
Hi djgg101,

It can happen if the user your looking at is deleted, blocked you, or
blocked by you, but it is still in the cache.
It is a known issue, we will find a solution for.

As a workaround you can delete your local cache either from your App
settings or from your device settings.

Please let me know if you needed more information about how to do this.

Thanks for reaching to us and sorry for inconveniences.
Dreamlite

**Comment by kistitan** [comment]
Closing this issue now, please feel to reopen if the workaround did not work.
