### ISSUE TITLE
Latest Stable Version problems

### ISSUE THREAD

**Issue by drubinger** [fetlife/android#531]
Requests and notification do not update. Always blank side in App.

**Comment by drubinger** [comment]
Hi

Oneplus 3, Lineage OS Android Pie

Example attached. Same effect for notification and requests.

Independant if using LTE, Wifi or any VPN connection. Always same effect,
blank and connection error.

Thanks

kistitan <notifications@github.com> schrieb am Mo., 25. März 2019, 15:12:

**Comment by kistitan** [comment]
Merging into https://github.com/fetlife/android/issues/529 as having the same source of problem
