### ISSUE TITLE
Downloading the new update

### ISSUE THREAD

**Issue by adkins17** [fetlife/android#533]
In version 2.22.0, I could not download the update to 2.23.0. The upgrade link was not responding. In previous version, the upgrade link kept re-downloading that version. In both instances, I had to download manually from the git website.

**Comment by malachid** [comment]
I get the problem with it redownloading the same version a lot. I'm not entirely sure yet, but I think it is happening if I fall to close the current instance before clicking install.

Recently, I've also seen an issue where I received a notification telling me to download the version that was currently installed.

I have also had to install it manually a few times from GitHub.

**Comment by kistitan** [comment]
@adkins17 @malachid 
Thank you for your information about update issues.

On current update process we rely on external solutions like download manager to download a new version, so we have less influence on what is happening.

We are working on a new update process now, when we take over the actual download and start of installation so hopefully we can come with a more reliable solution.

Thank you for your patience

**Comment by FernandoMiguel** [comment]
Even with the latest preview update, it failed to install after downloading from the notification.
I had to use the browser to download from github and install 

Running android Q alpha1 on pixel 3 XL

**Comment by FernandoMiguel** [comment]
Dot 7 update seems to push and install the update just fine (after I grant it access to install apps out of the store)
Thank you

**Comment by kistitan** [comment]
Thanks for the confirmation it works better.
We indeed added some redirection in case we notice we do not have some permissions.

We still planning to improve further the update process. 
There is an ongoing investigation about how to do so.
