### ISSUE TITLE
Share screen shows nothing in private messages

### ISSUE THREAD

**Issue by SpaceOctopus** [fetlife/android#535]
# 🐛Bug Report

### Bug description 
Shows nothing in the share window, after choosing the share icon in a private message

### Steps to reproduce
1. Go to 'private message'
2. Click on 'share icon'
3. See blank screen

### Expected behavior
Normal photo selection screen, I think? 

### Screenshots
![Screenshot_20190406144921](https://user-images.githubusercontent.com/8183379/55675726-45655000-587b-11e9-9ab0-7e58e62bcc14.jpg)

### Environment

 - Device: [Oneplus 3T]
 - OS version: [7.1.2]
 - App version. [2.23.7]

**Comment by kistitan** [comment]
Hi @SpaceOctopus ,

Thanks a lot for reporting this issue.
We are sorry for the confusion about this feature.

Unfortunately FetLife app doesn't offer you a full image sharing feature. 
There are safety, privacy and technical reasons behind it, but we hope in the future we can provide you a better experience in this area.

At the moment the image sharing feature of the FetLife App can only be used to share already uploaded images from FetLife. 
The image sharing screen will offer you images, that are 

- Marked for sharing by you (can be done in the App by pressing the share icon after opening an individual picture)
- Recently visited by you

If you start the App the first time or after installation you indeed might see an empty screen.

Please check you photos of you explore section or photos of some users, mark them to share and visit the picture sharing screen again.

Please let us know if your marked pictures will appear as expected.

P.S: Unfortunately we are going to remove this feature soon completely for technical reasons.

**Comment by kistitan** [comment]
Closing this for now, please feel to reopen if you had any further questions.
