### ISSUE TITLE
Autocorrect

### ISSUE THREAD

**Issue by WalrusInAnus** [fetlife/android#537]
# 🐛Bug Report

### Bug description 
I am not even sure if this is a bug.
Basically, it seems like the app ignores system **partially** autocorrect settings, specifically when you expect a space after typing a comma.
For whatever it's worth, I am also using Swift keyboard.
Not sure what other info to supply, feel free to ask.

### Environment

 - Device: Sony Xperia XZ1 Compact
 - OS version: stock Android Pie
 - App version. 2.23.14 (but it happened before too)

**Comment by kistitan** [comment]
Hey @WalrusInAnus,

Thanks a lot for reporting this issue.

Indeed as a first look it does not like FetLife App related, as auto-correct usually happens before the textual input actually reaches our code.
But just to be sure we will have a quick look to see if have anything to do with it, or give some hints how to avoid the issue.

Krisztian

**Comment by kistitan** [comment]
@WalrusInAnus 
I have downloaded Swift keyboard, and started testing the app with it on our test devices.
So far space auto added after coma correctly.

Also as I mentioned earlier, our app start interacting with the input text only by the time the text is given to us by the keyboard.
We also not do any text formatting after, so there is a big chance we cannot help you with this issue on our side.

Did you happen to try maybe resetting your keyboard settings or reinstalling it?
(Please keep in mind, that some keyboard stores frequent input words, that you might want to back up first before any reset).

Also if you have any specific auto correction usecase that fails for you frequently, please let us know, so we can test that one specifically. 

Thank you

**Comment by WalrusInAnus** [comment]
I'm afraid this is not troubleshootable at all :(
If it works for you, it must be something on my end. I'd need a lot of alcohol to dig into the damn Sony stock ROM though :D

**Comment by kistitan** [comment]
Ah good luck with that :)

Please let us know if you find any sign, that we can do anything from our side.

**Comment by whoissylvia** [comment]
Thanks guys very much for trying to rectify the problem. I am not very good
with computers and hope that you have not stressed out too much trying to
sort things out.

Is the problem solvable or do I need to start the registration process all
over again?  Am I able to use the same username?  I assume that I can use
the same email address?

I really liked my username!  💋💋💋
Greetings from South Australia and thanks for the help

Sylvia

**Comment by navyguyg** [comment]
@whoissylvia I believe you may have responded to the wrong issue.
