### ISSUE TITLE
Connection failed. Please try again

### ISSUE THREAD

**Issue by kistitan** [fetlife/android#543]
# 🐛Bug Report

### Bug description 
Still getting occasional Connection failed. Please try again later

### Steps to reproduce

1. Go to the fetlife app as you normally woul
2. Click on click on feed or whatever
3. Scroll down to anywhere

### Expected behavior
It should not be showing Connection failed even though I have internet acces

### Environment

- Device: Google Pixel 3 xl
- OS version: Android Version 9
- App version. v.3.0.0-beta.1

**Comment by kistitan** [comment]
Issue created from original report of https://github.com/fetlife/android/issues/542

**Comment by kistitan** [comment]
@ImperfMage

I ping you here so we can separate the two original issue tracking from each other.

As I mentioned in the original report, it is a tricky one, as we cannot reproduce it, and there are several places where it can go wrong. 
To be able to see what is going wrong on your device, would you be interested in helping us out and install a debug version of the app with extra logging?

Thanks a lot
Dreamlite

**Comment by ImperfMage** [comment]
@kistitan I dont mind helping out at all , where do I install the debug version from ?

**Comment by kistitan** [comment]
@ImperfMage 
Thanks a lot for your positive feedback.

I need find the places in the code that could be related to that error message and add the extra logging.
If the build is ready I will let you know about how to install it here.

Thanks again

**Comment by ImperfMage** [comment]
@kistitan 
My pleasure , ^_^ I like helping when I can.

**Comment by ImperfMage** [comment]
@kistitan  any update on the debugger ?

**Comment by kistitan** [comment]
Hi @ImperfMage, 

Good timing, I have just finished with adding the extra logs :)

[fetlife-3.0.0-beta.3+1556859451.zip](https://github.com/fetlife/android/files/3140691/fetlife-3.0.0-beta.3%2B1556859451.zip)

In order to test, please:
- Rename the attached file to .apk from .zip
- Install on your device
- Use the app and reproduce the issue a few times
- Open side menu and select "Share Logs"
- Please send the logs to krisztian@fetlife.com

Thanks a lot!

**Comment by ImperfMage** [comment]
@kistitan 
So far the issue hasn't showed up , but will send when it happens

**Comment by malachid** [comment]
I will note that when I see it (over various previous versions), it is upon first launching the app and then it's all over the place. Killing the app and restarting it usually resolves it.

**Comment by kistitan** [comment]
Thanks for the udpate.

I am very curious about to see the logs to know what is going on.
So whenever you manage to reproduce it, please let us know.

Hopefully we can track down the issue soon.

Thank you for your help

**Comment by ImperfMage** [comment]
@Kistitan 
Finally got it too happen and the logs have been sent

**Comment by kistitan** [comment]
@ImperfMage 

I am really sorry, but I cannot see the logs.
Did you send it to krisztian@fetlife.com?

Thanks

**Comment by kistitan** [comment]
Hey there,

Thanks to the sent logs, we managed to localize at least one issue.
The connection failed message in this case is happening as our server refuse the connection, due to too many incoming requests in short ammount of time (429)
In that case, based on the logs there were many incoming group notifications in short amount of time, so we also fired as many requests towards our api.

We are going to think what is the best way to address this issue.

Thank you for your help

**Comment by kistitan** [comment]
Server side implementation is done, so for now on this specific connection failed issues should be already less frequent.

We also done client side implementation that will released in the next version.

If the issue persist even after installing the next version please feel free to reopen this issue.
