### ISSUE TITLE
"New in this version."

### ISSUE THREAD

**Issue by Daddy** [fetlife/android#58]
Make a popup dialog window that displays any recent changes to the client since the past version, which can be dismissed upon launching the app for the first time. This is a good alternative as the app is not listed on the Google Play Store where update notes and change logs are visable before updating.

**Goal:**
Alert non-tech savvy users of the Fetlife application to acknowledge and be aware of any changes to the client in a brief manner to cut down on questions either on Fetlife Tech Support, Github Issues, or emails to the team. This also provides a bit more transparency.

**Comment by kistitan** [comment]
Hi Daddy,

Thank you for the suggestion.
I would avoid popup as it can be bothering for some users, but otherwise, indeed it's a great idea to give some more information about the new features.
Maybe some highlight over the version indication that you can click on it and see what happened in different versions.
Probably will be done after version 1.0 (that is pretty close actually)

**Comment by JohnBaku** [comment]
You know.. it's not such a bad idea... Basecamp currently blogged about doing something like that here:
https://m.signalvnoise.com/getting-from-%EF%B8%8F-%EF%B8%8F-to-%EF%B8%8F-%EF%B8%8F-%EF%B8%8F-%EF%B8%8F-%EF%B8%8F-c65cc3bb7cb1#.2mzynnw4e

Here is the screenshot:

![1 7p0j8pdpbswuahz0-nbo9a](https://cloud.githubusercontent.com/assets/22100/15751511/39f18c66-289f-11e6-843d-0e5d6923b76e.png)

**Comment by Daddy** [comment]
@JohnBaku Nice example! @kistitan A lot of update dialogs aren't too obtrusive as they are a one-time dismissible and provide enough useful information to be worth the user's time.

That isn't to say every single version has to use it (i.e: strictly bug fixes or crashes), but any major updates or new feature implementations can take advantage of this.

**Comment by reneklacan** [comment]
I think it's good idea 👍

**Comment by kistitan** [comment]
Hahaha it's seems I am outnumbered.
I personally hate when I got unexpected unwanted information.
I rather would imagine what's new icon with nice highlights etc.

But this app is not for me, but for all of us, so sure, why not? (I keen keep my separate version without :p)

**Comment by Daddy** [comment]
@kistitan Just make a catch case for disabling it if the logged in user is you, haha. ;)

**Comment by JohnBaku** [comment]
@kistitan not saying we need to do it! :-p Just saying we can do it like above.

**Comment by kdom13** [comment]
I like this idea.  I also like Basecamp!

**Comment by GojuSuzi** [comment]
I've seen some that give a check box option to opt out of the change log pop up, so people can, on first install, see it once and never again if it bothers them. That might be the kind of thing that would need to wait until a later version where settings can be reliably retained through updates, however.

**Comment by akhepcat** [comment]
just re-pinging this enhancement, now that we're at 1.2.0, and setting seems to hold through updates.

Absolutely for the 'opt-in/opt-out' configurability of this - because I often like to see what's changed between releases - especially while new features are being added to a not-feature-complete app.

**Comment by kistitan** [comment]
Thanks for the re-ping.
I am going to raise the priority of this request.

**Comment by kistitan** [comment]
Feature Added in version 1.3.0
