### ISSUE TITLE
Conversation should be opened twice to make the new icon disappeared

### ISSUE THREAD

**Issue by kistitan** [fetlife/android#63]

**Comment by kistitan** [comment]
Happens only in case of connection issue, that actually make sense.

**Comment by kistitan** [comment]
Still reproducable

**Comment by kistitan** [comment]
Cannot reproduce any more.
Help wanted to try to reproduce and confirm the bug still exist or not.

**Comment by GojuSuzi** [comment]
Just to add I was seeing this before, not happening now. Seems fixed.

**Comment by reneklacan** [comment]
@GojuSuzi thanks for feedback 🎊

**Comment by kistitan** [comment]
Yep, thank you!
I am closing this for now.
Can be reopened if it occured again.
