### ISSUE TITLE
Outdated README graphic.

### ISSUE THREAD

**Issue by Daddy** [fetlife/android#84]
The current graphic / application preview should be updated to display all of the changes and additions added since Version 1. 
- The first panel and second panel still displays FetChat.
- Profile pictures (avatars) are not displayed in the preview.
- Links are not parsed or appear to be in the last panel.
- The last panel displays the user's generated ID instead of a proper username.

The first panel which displays the login panel should be considered to be abandoned, and have the final panel now display the friends list display instead.

**Comment by JohnBaku** [comment]
@Daddy good catches!

**Comment by kistitan** [comment]
@Help would be welcome to make screenshots for this.

WARNING: screenshots must not contain personal information from other users.

**Comment by kistitan** [comment]
New screenshots:

![screenshot_fetlife_android_conversations](https://cloud.githubusercontent.com/assets/4168967/21647769/d844410a-d29b-11e6-9b92-c210bc1ccf98.jpg)
![screenshot_fetlife_android_feed](https://cloud.githubusercontent.com/assets/4168967/21647770/d854d74a-d29b-11e6-9dd0-47f616305962.jpg)
![screenshot_fetlife_android_messages](https://cloud.githubusercontent.com/assets/4168967/21647771/d85e4c44-d29b-11e6-8546-24dece703da2.jpg)
![screenshot_fetlife_android_picture](https://cloud.githubusercontent.com/assets/4168967/21647772/d8688a6a-d29b-11e6-8069-17c7c5bdd650.jpg)

**Comment by FernandoMiguel** [comment]
you have waayyyy too many notifications 
and an update pending :p

**Comment by kistitan** [comment]
@FernandoMiguel : Thanks, it is indeed better without :)
