### ISSUE TITLE
First words in sentences aren't auto-capitalized

### ISSUE THREAD

**Issue by kdom13** [fetlife/android#87]
In all other apps, the first word of a sentence will be automatically capitalized.  In the FetLife app, they are not.  I remember this also used to be an issue with FetLife on Chrome for Android, but that got fixed years ago.

**Comment by Daddy** [comment]
This is not necessarily a bug as it can be a preference for some users, but there is something that can be added to the text field to allow the system to control it being toggled on and off.

**Comment by scruffynerf** [comment]
+1

**Comment by johnbaku** [comment]
+1

**Comment by kistitan** [comment]
This should be a simple flag setting, but it simply does not work on my test device...
Under investigation...

**Comment by kistitan** [comment]
Issue parked due to low priority

**Comment by kistitan** [comment]
Auto cap support added to conversation edit text based on Android documentation.
However based on texting not every keyboard support this settings by default.

For example Google keyboard in general have setting to have Auto Sentence Capitalization by default for all input texts.
Please check your keyboard settings for more information.

**Comment by kistitan** [comment]
Support added in 1.7, however feature is very much keyboard dependant.
