### ISSUE TITLE
Friends List ordered by Capitals first then lowercase

### ISSUE THREAD

**Issue by DerangedMind** [fetlife/android#96]
As a *member,* I tried to *view my friends list*, but *it showed the usernames that started with a capital letter first and then the usernames that started with a lowercase letter*.  

Example:

Allen23
KittyKat
ZebraMan
babyboy33
sally69

**Comment by kistitan** [comment]
Confirmed, and it cause the flickering.
Will be fixed in next version.

Thanks for reporting

**Comment by kistitan** [comment]
No, it just default sorting is different with mysql database

**Comment by kistitan** [comment]
Fixed. Fix will be available in version 1.3.
Thanks for the patience.

**Comment by kistitan** [comment]
Fixed in 1.3.0
